// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 引擎版本：0.0.0.4 (2019/07/31 10:06)

#ifndef ARTIFICIAL_INTELLIGENCE_EXPORT_H
#define ARTIFICIAL_INTELLIGENCE_EXPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_ARTIFICIAL_INTELLIGENCE_EXPORT
  #define BUILDING_ARTIFICIAL_INTELLIGENCE_EXPORT
#endif // BUILDING_ARTIFICIAL_INTELLIGENCE_EXPORT

#endif // ARTIFICIAL_INTELLIGENCE_EXPORT_H