///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.0 (2021/01/23 16:06)

#ifndef PROFESSIONAL_CPP_HELPER_USER_MACRO_H
#define PROFESSIONAL_CPP_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define PROFESSIONAL_CPP_ClOSE_BEGIN (0x01)

#define CLOSE_USE_PROFESSIONAL_CPP (PROFESSIONAL_CPP_ClOSE_BEGIN)

#define PROFESSIONAL_CPP_ClOSE_END CLOSE_USE_PROFESSIONAL_CPP

#define CLOSE_PROFESSIONAL_CPP_MAX ((PROFESSIONAL_CPP_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_PROFESSIONAL_CPP_CLOSE 0x00

static_assert(0 <= COMPILE_PROFESSIONAL_CPP_CLOSE, "COMPILE_PROFESSIONAL_CPP_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_PROFESSIONAL_CPP_CLOSE <= CLOSE_PROFESSIONAL_CPP_MAX, "COMPILE_PROFESSIONAL_CPP_CLOSE Must be less than or equal CLOSE_PROFESSIONAL_CPP_MAX.");

#if !defined(COMPILE_PROFESSIONAL_CPP_CLOSE) || (COMPILE_PROFESSIONAL_CPP_CLOSE & CLOSE_USE_PROFESSIONAL_CPP) != CLOSE_USE_PROFESSIONAL_CPP

#endif  // !defined(COMPILE_PROFESSIONAL_CPP_CLOSE) || (COMPILE_PROFESSIONAL_CPP_CLOSE & CLOSE_USE_PROFESSIONAL_CPP) != CLOSE_USE_PROFESSIONAL_CPP

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_PROFESSIONAL_CPP_STATIC
#endif  // BUILDING_STATIC

#endif  // PROFESSIONAL_CPP_HELPER_USER_MACRO_H
