// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.0.3 (2019/10/02 9:17)

#ifndef IRRLICHT_LIB_EXAMPLE_DLL_H
#define IRRLICHT_LIB_EXAMPLE_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(IRRLICHT_LIB_EXAMPLE_NO_IMPORT) || defined(BUILDING_IRRLICHT_LIB_EXAMPLE_STATIC)

  #define IRRLICHT_LIB_EXAMPLE_DEFAULT_DECLARE
  #define IRRLICHT_LIB_EXAMPLE_HIDDEN_DECLARE
  #define IRRLICHT_LIB_EXAMPLE_VISIBLE

#else // !defined(IRRLICHT_LIB_EXAMPLE_NO_IMPORT) && !defined(IRRLICHT_LIB_EXAMPLE_STATIC)

   #if defined(IRRLICHT_LIB_EXAMPLE_EXPORT)
 
        #define IRRLICHT_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define IRRLICHT_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(IRRLICHT_LIB_EXAMPLE_EXPORT)

		#define IRRLICHT_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define IRRLICHT_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // IRRLICHT_LIB_EXAMPLE_EXPORT

   #define IRRLICHT_LIB_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(IRRLICHT_LIB_EXAMPLE_NO_IMPORT) || defined(IRRLICHT_LIB_EXAMPLE_STATIC)

#endif // IRRLICHT_LIB_EXAMPLE_DLL_H
