///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	版本：0.9.1.2 (2023/07/25 16:54)

#ifndef TIME_REFRESH_DLL_H
#define TIME_REFRESH_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_TIME_REFRESH_NO_IMPORT) || defined(BUILDING_TIME_REFRESH_STATIC)

    #define TIME_REFRESH_DEFAULT_DECLARE
    #define TIME_REFRESH_VISIBLE

    #if defined(BUILDING_TIME_REFRESH_EXPORT)

        #define TIME_REFRESH_HIDDEN_DECLARE

    #else  // !defined(BUILDING_TIME_REFRESH_EXPORT)

        #define TIME_REFRESH_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_TIME_REFRESH_EXPORT

#else  // !defined(BUILDING_TIME_REFRESH_NO_IMPORT) && !defined(BUILDING_TIME_REFRESH_STATIC)

    #if defined(BUILDING_TIME_REFRESH_EXPORT)

        #define TIME_REFRESH_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define TIME_REFRESH_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_TIME_REFRESH_EXPORT)

        #define TIME_REFRESH_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define TIME_REFRESH_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_TIME_REFRESH_EXPORT

    #define TIME_REFRESH_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_TIME_REFRESH_NO_IMPORT) || defined(BUILDING_TIME_REFRESH_STATIC)

#endif  // TIME_REFRESH_DLL_H
