///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.3 (2021/05/12 16:55)

#ifndef WINDOWS_SYSTEM_PROGRAMMING_EXPORT_H
#define WINDOWS_SYSTEM_PROGRAMMING_EXPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_WINDOWS_SYSTEM_PROGRAMMING_EXPORT
    #define BUILDING_WINDOWS_SYSTEM_PROGRAMMING_EXPORT
#endif  // BUILDING_WINDOWS_SYSTEM_PROGRAMMING_EXPORT

#endif  // WINDOWS_SYSTEM_PROGRAMMING_EXPORT_H
