///	Copyright (c) 2010-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.0 (2020/12/26 21:31)

#ifndef CPP_FOR_THE_IMPATIENT_DLL_H
#define CPP_FOR_THE_IMPATIENT_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_CPP_FOR_THE_IMPATIENT_NO_IMPORT) || defined(BUILDING_CPP_FOR_THE_IMPATIENT_STATIC)

    #define CPP_FOR_THE_IMPATIENT_DEFAULT_DECLARE
    #define CPP_FOR_THE_IMPATIENT_HIDDEN_DECLARE
    #define CPP_FOR_THE_IMPATIENT_VISIBLE

#else  // !defined(BUILDING_CPP_FOR_THE_IMPATIENT_NO_IMPORT) && !defined(BUILDING_CPP_FOR_THE_IMPATIENT_STATIC)

    #if defined(BUILDING_CPP_FOR_THE_IMPATIENT_EXPORT)

        #define CPP_FOR_THE_IMPATIENT_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define CPP_FOR_THE_IMPATIENT_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_CPP_FOR_THE_IMPATIENT_EXPORT)

        #define CPP_FOR_THE_IMPATIENT_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define CPP_FOR_THE_IMPATIENT_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_CPP_FOR_THE_IMPATIENT_EXPORT

    #define CPP_FOR_THE_IMPATIENT_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_CPP_FOR_THE_IMPATIENT_NO_IMPORT) || defined(BUILDING_CPP_FOR_THE_IMPATIENT_STATIC)

#endif  // CPP_FOR_THE_IMPATIENT_DLL_H
