///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	版本：0.9.1.2 (2023/07/31 14:50)

#ifndef SCRIPT_EDITOR_DLL_DLL_H
#define SCRIPT_EDITOR_DLL_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_SCRIPT_EDITOR_NO_IMPORT) || defined(BUILDING_SCRIPT_EDITOR_STATIC)

    #define SCRIPT_EDITOR_DEFAULT_DECLARE
    #define SCRIPT_EDITOR_VISIBLE

    #if defined(BUILDING_SCRIPT_EDITOR_EXPORT)

        #define SCRIPT_EDITOR_HIDDEN_DECLARE

    #else  // !defined(BUILDING_SCRIPT_EDITOR_EXPORT)

        #define SCRIPT_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_SCRIPT_EDITOR_EXPORT

#else  // !defined(BUILDING_SCRIPT_EDITOR_NO_IMPORT) && !defined(BUILDING_SCRIPT_EDITOR_STATIC)

    #if defined(BUILDING_SCRIPT_EDITOR_EXPORT)

        #define SCRIPT_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define SCRIPT_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_SCRIPT_EDITOR_EXPORT)

        #define SCRIPT_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define SCRIPT_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_SCRIPT_EDITOR_EXPORT

    #define SCRIPT_EDITOR_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_SCRIPT_EDITORNO_IMPORT) || defined(BUILDING_SCRIPT_EDITOR_STATIC)

#endif  // SCRIPT_EDITOR_DLL_DLL_H
