// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.1 (2020/01/21 21:30)

#ifndef SCRIPT_EDITOR_DLL_DLL_H
#define SCRIPT_EDITOR_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(BUILDING_SCRIPT_EDITOR_NO_IMPORT) || defined(BUILDING_SCRIPT_EDITOR_STATIC)

  #define SCRIPT_EDITOR_DEFAULT_DECLARE
  #define SCRIPT_EDITOR_HIDDEN_DECLARE
  #define SCRIPT_EDITOR_VISIBLE

#else // !defined(BUILDING_SCRIPT_EDITOR_NO_IMPORT) && !defined(BUILDING_SCRIPT_EDITOR_STATIC)

   #if defined(BUILDING_SCRIPT_EDITOR_EXPORT)
 
        #define SCRIPT_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define SCRIPT_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_SCRIPT_EDITOR_EXPORT)

		#define SCRIPT_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define SCRIPT_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_SCRIPT_EDITOR_EXPORT

   #define SCRIPT_EDITOR_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_SCRIPT_EDITORNO_IMPORT) || defined(BUILDING_SCRIPT_EDITOR_STATIC)

#endif // SCRIPT_EDITOR_DLL_DLL_H
