// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.0.3 (2019/10/02 14:37)

#ifndef WILD_MAGIC_LIB_EXAMPLE_DLL_H
#define WILD_MAGIC_LIB_EXAMPLE_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(WILD_MAGIC_LIB_EXAMPLE_NO_IMPORT) || defined(BUILDING_WILD_MAGIC_LIB_EXAMPLE_STATIC)

  #define WILD_MAGIC_LIB_EXAMPLE_DEFAULT_DECLARE
  #define WILD_MAGIC_LIB_EXAMPLE_HIDDEN_DECLARE
  #define WILD_MAGIC_LIB_EXAMPLE_VISIBLE

#else // !defined(WILD_MAGIC_LIB_EXAMPLE_NO_IMPORT) && !defined(WILD_MAGIC_LIB_EXAMPLE_STATIC)

   #if defined(WILD_MAGIC_LIB_EXAMPLE_EXPORT)
 
        #define WILD_MAGIC_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define WILD_MAGIC_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(WILD_MAGIC_LIB_EXAMPLE_EXPORT)

		#define WILD_MAGIC_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define WILD_MAGIC_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // WILD_MAGIC_LIB_EXAMPLE_EXPORT

   #define WILD_MAGIC_LIB_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(WILD_MAGIC_LIB_EXAMPLE_NO_IMPORT) || defined(WILD_MAGIC_LIB_EXAMPLE_STATIC)

#endif // WILD_MAGIC_LIB_EXAMPLE_DLL_H
