/// Copyright (c) 2010-2023
/// Threading Core Render Engine
///
/// 作者：彭武阳，彭晔恩，彭晔泽
/// 联系作者：94458936@qq.com
///
/// 标准：std:c++20
/// 版本：1.0.0.0 (2023/11/18 17:09)

#ifndef MESSAGE_CLIENT_MIDDLE_LAYER_NO_IMPORT_H
#define MESSAGE_CLIENT_MIDDLE_LAYER_NO_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_MESSAGE_CLIENT_MIDDLE_LAYER_NO_IMPORT

    #define BUILDING_MESSAGE_CLIENT_MIDDLE_LAYER_NO_IMPORT

#endif  // BUILDING_MESSAGE_CLIENT_MIDDLE_LAYER_NO_IMPORT

#endif  // MESSAGE_CLIENT_MIDDLE_LAYER_NO_IMPORT_H