// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.0 (2020/01/05 18:58)

#ifndef SOUND_EFFECT_TOOLSET_DLL_DLL_H
#define SOUND_EFFECT_TOOLSET_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "SoundEffect/Helper/UserMacro.h"

#if defined(BUILDING_SOUND_EFFECT_TOOLSET_NO_IMPORT) || defined(BUILDING_SOUND_EFFECT_STATIC)

  #define SOUND_EFFECT_TOOLSET_DEFAULT_DECLARE
  #define SOUND_EFFECT_TOOLSET_HIDDEN_DECLARE
  #define SOUND_EFFECT_TOOLSET_VISIBLE

#else // !defined(BUILDING_SOUND_EFFECT_TOOLSET_NO_IMPORT) && !defined(BUILDING_SOUND_EFFECT_STATIC)

   #if defined(BUILDING_SOUND_EFFECT_TOOLSET_EXPORT)
 
        #define SOUND_EFFECT_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define SOUND_EFFECT_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_SOUND_EFFECT_TOOLSET_EXPORT)

		#define SOUND_EFFECT_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define SOUND_EFFECT_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_SOUND_EFFECT_TOOLSET_EXPORT

   #define SOUND_EFFECT_TOOLSET_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_SOUND_EFFECT_TOOLSET_NO_IMPORT) || defined(BUILDING_SOUND_EFFECT_STATIC)

#endif // SOUND_EFFECT_TOOLSET_DLL_DLL_H
