///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.0 (2021/01/30 11:03)

#ifndef ALGORITHMS_UNLOCKED_DLL_H
#define ALGORITHMS_UNLOCKED_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_ALGORITHMS_UNLOCKED_NO_IMPORT) || defined(BUILDING_ALGORITHMS_UNLOCKED_STATIC)

    #define ALGORITHMS_UNLOCKED_DEFAULT_DECLARE
    #define ALGORITHMS_UNLOCKED_HIDDEN_DECLARE
    #define ALGORITHMS_UNLOCKED_VISIBLE

#else  // !defined(BUILDING_ALGORITHMS_UNLOCKED_NO_IMPORT) && !defined(BUILDING_ALGORITHMS_UNLOCKED_STATIC)

    #if defined(BUILDING_ALGORITHMS_UNLOCKED_EXPORT)

        #define ALGORITHMS_UNLOCKED_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define ALGORITHMS_UNLOCKED_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_ALGORITHMS_UNLOCKED_EXPORT)

        #define ALGORITHMS_UNLOCKED_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define ALGORITHMS_UNLOCKED_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_ALGORITHMS_UNLOCKED_EXPORT

    #define ALGORITHMS_UNLOCKED_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_ALGORITHMS_UNLOCKED_NO_IMPORT) || defined(BUILDING_ALGORITHMS_UNLOCKED_STATIC)

#endif  // ALGORITHMS_UNLOCKED_DLL_H
