///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.0 (2021/02/27 12:44)

#ifndef GENERIC_PROGRAMMING_AND_THE_STL_DLL_H
#define GENERIC_PROGRAMMING_AND_THE_STL_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_GENERIC_PROGRAMMING_AND_THE_STL_NO_IMPORT) || defined(BUILDING_GENERIC_PROGRAMMING_AND_THE_STL_STATIC)

    #define GENERIC_PROGRAMMING_AND_THE_STL_DEFAULT_DECLARE
    #define GENERIC_PROGRAMMING_AND_THE_STL_HIDDEN_DECLARE
    #define GENERIC_PROGRAMMING_AND_THE_STL_VISIBLE

#else  // !defined(BUILDING_GENERIC_PROGRAMMING_AND_THE_STL_NO_IMPORT) && !defined(BUILDING_GENERIC_PROGRAMMING_AND_THE_STL_STATIC)

    #if defined(BUILDING_GENERIC_PROGRAMMING_AND_THE_STL_EXPORT)

        #define GENERIC_PROGRAMMING_AND_THE_STL_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define GENERIC_PROGRAMMING_AND_THE_STL_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_GENERIC_PROGRAMMING_AND_THE_STL_EXPORT)

        #define GENERIC_PROGRAMMING_AND_THE_STL_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define GENERIC_PROGRAMMING_AND_THE_STL_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_GENERIC_PROGRAMMING_AND_THE_STL_EXPORT

    #define GENERIC_PROGRAMMING_AND_THE_STL_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_GENERIC_PROGRAMMING_AND_THE_STL_NO_IMPORT) || defined(BUILDING_GENERIC_PROGRAMMING_AND_THE_STL_STATIC)

#endif  // GENERIC_PROGRAMMING_AND_THE_STL_DLL_H
