// Copyright (c) 2011-2020
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
//
// 引擎辅助版本：0.0.3.0 (2020/03/24 23:26)

#ifndef DESIGN_PATTERNS_EXPLAINED_MACRO_USER_MACRO_H
#define DESIGN_PATTERNS_EXPLAINED_MACRO_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define CLOSE_USE_DESIGN_PATTERNS_EXPLAINED (0x01) 
#define CLOSE_DESIGN_PATTERNS_EXPLAINED_MAX ((CLOSE_USE_DESIGN_PATTERNS_EXPLAINED << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_DESIGN_PATTERNS_EXPLAINED_CLOSE 0x00

static_assert(0 <= COMPILE_DESIGN_PATTERNS_EXPLAINED_CLOSE, "COMPILE_DESIGN_PATTERNS_EXPLAINED_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_DESIGN_PATTERNS_EXPLAINED_CLOSE <= CLOSE_DESIGN_PATTERNS_EXPLAINED_MAX, "COMPILE_DESIGN_PATTERNS_EXPLAINED_CLOSE Must be less than or equal CLOSE_DESIGN_PATTERNS_EXPLAINED_MAX.");

// 是否编译为静态库
#ifdef BUILDING_STATIC
	#define  BUILDING_DESIGN_PATTERNS_EXPLAINED_STATIC
#endif // BUILDING_STATIC

#if !defined(COMPILE_DESIGN_PATTERNS_EXPLAINED_CLOSE) || (COMPILE_DESIGN_PATTERNS_EXPLAINED_CLOSE & CLOSE_USE_DESIGN_PATTERNS_EXPLAINED) != CLOSE_USE_DESIGN_PATTERNS_EXPLAINED

#endif // !defined(COMPILE_DESIGN_PATTERNS_EXPLAINED_CLOSE) || (COMPILE_DESIGN_PATTERNS_EXPLAINED_CLOSE & CLOSE_USE_DESIGN_PATTERNS_EXPLAINED) != CLOSE_USE_DESIGN_PATTERNS_EXPLAINED 
 
#endif // DESIGN_PATTERNS_EXPLAINED_MACRO_USER_MACRO_H
