///	Copyright (c) 2010-2022
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	引擎辅助版本：0.8.0.10 (2022/07/12 18:16)

#ifndef RESOURCE_MANAGER_EXAMPLE_DLL_DLL_H
#define RESOURCE_MANAGER_EXAMPLE_DLL_DLL_H

#include "Macro/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_RESOURCE_MANAGER_EXAMPLE_NO_IMPORT) || defined(BUILDING_RESOURCE_MANAGER_EXAMPLE_STATIC)

    #define RESOURCE_MANAGER_EXAMPLE_DEFAULT_DECLARE
    #define RESOURCE_MANAGER_EXAMPLE_HIDDEN_DECLARE
    #define RESOURCE_MANAGER_EXAMPLE_VISIBLE

#else  // !defined(BUILDING_RESOURCE_MANAGER_EXAMPLE_NO_IMPORT) && !defined(BUILDING_RESOURCE_MANAGER_EXAMPLE_STATIC)

    #if defined(BUILDING_RESOURCE_MANAGER_EXAMPLE_EXPORT)

        #define RESOURCE_MANAGER_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define RESOURCE_MANAGER_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_RESOURCE_MANAGER_EXAMPLE_EXPORT)

        #define RESOURCE_MANAGER_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define RESOURCE_MANAGER_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_RESOURCE_MANAGER_EXAMPLE_EXPORT

    #define RESOURCE_MANAGER_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_RESOURCE_MANAGER_EXAMPLE_NO_IMPORT) || defined(BUILDING_RESOURCE_MANAGER_EXAMPLE_STATIC)

#endif  // RESOURCE_MANAGER_EXAMPLE_DLL_DLL_H
