// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 最后的霸王版本：0.0.0.1 (2019/10/11 17:44)

#ifndef GAME_SERVER_MIDDLE_LAYER_IMPORT_H
#define GAME_SERVER_MIDDLE_LAYER_IMPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_GAME_SERVER_MIDDLE_LAYER_IMPORT
  #define BUILDING_GAME_SERVER_MIDDLE_LAYER_IMPORT
#endif // BUILDING_GAME_SERVER_MIDDLE_LAYER_IMPORT

#endif // GAME_SERVER_MIDDLE_LAYER_IMPORT_H
