// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.0 (2020/01/08 21:34)

#ifndef USER_INTERFACE_TOOLSET_DLL_DLL_H
#define USER_INTERFACE_TOOLSET_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "UserInterface/Helper/UserMacro.h"

#if defined(BUILDING_USER_INTERFACE_TOOLSET_NO_IMPORT) || defined(BUILDING_USER_INTERFACE_STATIC)

  #define USER_INTERFACE_TOOLSET_DEFAULT_DECLARE
  #define USER_INTERFACE_TOOLSET_HIDDEN_DECLARE
  #define USER_INTERFACE_TOOLSET_VISIBLE

#else // !defined(BUILDING_USER_INTERFACE_TOOLSET_NO_IMPORT) && !defined(BUILDING_USER_INTERFACE_STATIC)

   #if defined(BUILDING_USER_INTERFACE_TOOLSET_EXPORT)
 
        #define USER_INTERFACE_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define USER_INTERFACE_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_USER_INTERFACE_TOOLSET_EXPORT)

		#define USER_INTERFACE_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define USER_INTERFACE_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_USER_INTERFACE_TOOLSET_EXPORT

   #define USER_INTERFACE_TOOLSET_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_USER_INTERFACE_TOOLSET_NO_IMPORT) || defined(BUILDING_USER_INTERFACE_STATIC)

#endif // USER_INTERFACE_TOOLSET_DLL_DLL_H
