///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.3 (2021/05/01 19:04)

#ifndef MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_HELPER_USER_MACRO_H
#define MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_ClOSE_BEGIN (0x01)

#define CLOSE_USE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION (MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_ClOSE_BEGIN)

#define MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_ClOSE_END CLOSE_USE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION

#define CLOSE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_MAX ((MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_CLOSE 0x00

static_assert(0 <= COMPILE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_CLOSE, "COMPILE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_CLOSE <= CLOSE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_MAX, "COMPILE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_CLOSE Must be less than or equal CLOSE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_MAX.");

#if !defined(COMPILE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_CLOSE) || (COMPILE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_CLOSE & CLOSE_USE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION) != CLOSE_USE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION

#endif  // !defined(COMPILE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_CLOSE) || (COMPILE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_CLOSE & CLOSE_USE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION) != CLOSE_USE_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION

#ifdef BUILDING_STATIC
    #define BUILDING_MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_STATIC
#endif  // BUILDING_STATIC

#endif  // MICROSOFT_WINDOWS_INTERNALS_SIXTH_EDITION_HELPER_USER_MACRO_H
