// Copyright (c) 2011-2020
// Threading Core Render Engine
// „ч’я£Ї≈нќд—ф£ђ≈нк ґч£ђ≈нк ‘у
//
// “э«жЄ®÷ъ∞ж±Њ£Ї0.0.3.0 (2020/03/24 23:23)

#ifndef DESIGN_PATTERNS_EXPLAINED_IMPORT_H
#define DESIGN_PATTERNS_EXPLAINED_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_DESIGN_PATTERNS_EXPLAINED_IMPORT
	#define BUILDING_DESIGN_PATTERNS_EXPLAINED_IMPORT
#endif // BUILDING_DESIGN_PATTERNS_EXPLAINED_IMPORT

#endif // DESIGN_PATTERNS_EXPLAINED_IMPORT_H
