// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.3.0 (2020/03/24 23:25)

#ifndef DESIGN_PATTERNS_EXPLAINED_DLL_H
#define DESIGN_PATTERNS_EXPLAINED_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Helper/UserMacro.h"

#if defined(BUILDING_DESIGN_PATTERNS_EXPLAINED_NO_IMPORT) || defined(BUILDING_DESIGN_PATTERNS_EXPLAINED_STATIC)

  #define DESIGN_PATTERNS_EXPLAINED_DEFAULT_DECLARE
  #define DESIGN_PATTERNS_EXPLAINED_HIDDEN_DECLARE 
  #define DESIGN_PATTERNS_EXPLAINED_VISIBLE

#else // !defined(BUILDING_DESIGN_PATTERNS_EXPLAINED_NO_IMPORT) && !defined(BUILDING_DESIGN_PATTERNS_EXPLAINED_STATIC)
 
   #if defined(BUILDING_DESIGN_PATTERNS_EXPLAINED_EXPORT)
 
        #define DESIGN_PATTERNS_EXPLAINED_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define DESIGN_PATTERNS_EXPLAINED_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_DESIGN_PATTERNS_EXPLAINED_EXPORT)

		#define DESIGN_PATTERNS_EXPLAINED_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define DESIGN_PATTERNS_EXPLAINED_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_DESIGN_PATTERNS_EXPLAINED_EXPORT

   #define DESIGN_PATTERNS_EXPLAINED_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_DESIGN_PATTERNS_EXPLAINED_NO_IMPORT) || defined(BUILDING_DESIGN_PATTERNS_EXPLAINED_STATIC)
 
#endif // DESIGN_PATTERNS_EXPLAINED_DLL_H
