///	Copyright (c) 2010-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.0 (2020/12/23 20:50)

#ifndef THINKING_IN_CPP_VOLUME_TWO_DLL_H
#define THINKING_IN_CPP_VOLUME_TWO_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_THINKING_IN_CPP_VOLUME_TWO_NO_IMPORT) || defined(BUILDING_THINKING_IN_CPP_VOLUME_TWO_STATIC)

    #define THINKING_IN_CPP_VOLUME_TWO_DEFAULT_DECLARE
    #define THINKING_IN_CPP_VOLUME_TWO_HIDDEN_DECLARE
    #define THINKING_IN_CPP_VOLUME_TWO_VISIBLE

#else  // !defined(BUILDING_THINKING_IN_CPP_VOLUME_TWO_NO_IMPORT) && !defined(BUILDING_THINKING_IN_CPP_VOLUME_TWO_STATIC)

    #if defined(BUILDING_THINKING_IN_CPP_VOLUME_TWO_EXPORT)

        #define THINKING_IN_CPP_VOLUME_TWO_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define THINKING_IN_CPP_VOLUME_TWO_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_THINKING_IN_CPP_VOLUME_TWO_EXPORT)

        #define THINKING_IN_CPP_VOLUME_TWO_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define THINKING_IN_CPP_VOLUME_TWO_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_THINKING_IN_CPP_VOLUME_TWO_EXPORT

    #define THINKING_IN_CPP_VOLUME_TWO_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_THINKING_IN_CPP_VOLUME_TWO_NO_IMPORT) || defined(BUILDING_THINKING_IN_CPP_VOLUME_TWO_STATIC)

#endif  // THINKING_IN_CPP_VOLUME_TWO_DLL_H
