// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.0 (2020/01/05 17:36)

#ifndef MATHEMATICS_TOOLSET_DLL_DLL_H
#define MATHEMATICS_TOOLSET_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Mathematics/Helper/UserMacro.h"

#if defined(BUILDING_MATHEMATICS_TOOLSET_NO_IMPORT) || defined(BUILDING_MATHEMATICS_STATIC)

  #define MATHEMATICS_TOOLSET_DEFAULT_DECLARE
  #define MATHEMATICS_TOOLSET_HIDDEN_DECLARE
  #define MATHEMATICS_TOOLSET_VISIBLE

#else // !defined(BUILDING_MATHEMATICS_TOOLSET_NO_IMPORT) && !defined(BUILDING_MATHEMATICS_STATIC)

   #if defined(BUILDING_MATHEMATICS_TOOLSET_EXPORT)
 
        #define MATHEMATICS_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define MATHEMATICS_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_MATHEMATICS_TOOLSET_EXPORT)

		#define MATHEMATICS_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define MATHEMATICS_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_MATHEMATICS_TOOLSET_EXPORT

   #define MATHEMATICS_TOOLSET_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_MATHEMATICS_TOOLSET_NO_IMPORT) || defined(BUILDING_MATHEMATICS_STATIC)

#endif // MATHEMATICS_TOOLSET_DLL_DLL_H
