// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.1.0.1 (2020/04/06 14:20)

#ifndef THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_HELPER_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_CUSTOM_ASSERT_MACRO_H
#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_HELPER_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_CUSTOM_ASSERT_MACRO_H

#include "UserMacro.h"
#include "CoreTools/Helper/Assertion/UserCustomAssertMacro.h"

#if defined(OPEN_IMPORTANT_EXCPTION_ASSERT)
	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL 0
#endif // OPEN_IMPORTANT_EXCPTION_ASSERT

#if !defined(THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL)
	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL 4
#endif // THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL

static_assert(THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL <= USER_ASSERT_LEVEL, "Assert level definition error.");

#if 0 <= THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL

	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_0(condition, format, ...) \
			USER_ASSERTION_0((condition), (format), __VA_ARGS__)
	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_USE_FUNCTION_DESCRIBED_0(condition,functionDescribed,format, ...) \
			USER_ASSERTION_USE_FUNCTION_DESCRIBED_0((condition),(functionDescribed),(format), __VA_ARGS__)

	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_DEBUG(condition, format, ...) \
			USER_ASSERTION_DEBUG((condition), (format), __VA_ARGS__)
	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_DEBUG_USE_FUNCTION_DESCRIBED(condition,functionDescribed,format, ...) \
			USER_ASSERTION_DEBUG_USE_FUNCTION_DESCRIBED((condition),(functionDescribed),(format), __VA_ARGS__)

#else // THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL < 0

	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_0(condition, format, ...) ((void)0)
	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_USE_FUNCTION_DESCRIBED_0(condition,functionDescribed,format, ...) ((void)0)

	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_DEBUG(condition, format, ...) ((void)0)
	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_DEBUG_USE_FUNCTION_DESCRIBED(condition,functionDescribed,format, ...) ((void)0)

#endif // 0 <= THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL

#if 1 <= THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL

	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_1(condition, format, ...) \
			USER_ASSERTION_1((condition), (format), __VA_ARGS__)
	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_USE_FUNCTION_DESCRIBED_1(condition,functionDescribed,format, ...) \
			USER_ASSERTION_USE_FUNCTION_DESCRIBED_1((condition),(functionDescribed),(format), __VA_ARGS__)

#else // THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL < 1

	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_1(condition, format, ...) ((void)0)
	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_USE_FUNCTION_DESCRIBED_1(condition,functionDescribed,format, ...) ((void)0)

#endif // 1 <= THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL

#if 2 <= THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL

	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_2(condition, format, ...) \
			USER_ASSERTION_2((condition), (format), __VA_ARGS__)
	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_USE_FUNCTION_DESCRIBED_2(condition,functionDescribed,format, ...) \
			USER_ASSERTION_USE_FUNCTION_DESCRIBED_2((condition),(functionDescribed),(format), __VA_ARGS__)

#else // THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL < 2

	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_2(condition, format, ...) ((void)0)
	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_USE_FUNCTION_DESCRIBED_2(condition,functionDescribed,format, ...) ((void)0)

#endif // 2 <= THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL

#if 3 <= THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL

	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_3(condition, format, ...) \
			USER_ASSERTION_3((condition), (format), __VA_ARGS__)
	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_USE_FUNCTION_DESCRIBED_3(condition,functionDescribed,format, ...) \
			USER_ASSERTION_USE_FUNCTION_DESCRIBED_3((condition),(functionDescribed),(format), __VA_ARGS__)

#else // THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL < 3

	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_3(condition, format, ...) ((void)0)
	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_USE_FUNCTION_DESCRIBED_3(condition,functionDescribed,format, ...) ((void)0)

#endif // 3 <= THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL

#if 4 <= THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL

	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_4(condition, format, ...) \
			USER_ASSERTION_4((condition), (format), __VA_ARGS__)
	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_USE_FUNCTION_DESCRIBED_4(condition, functionDescribed, format, ...) \
			USER_ASSERTION_USE_FUNCTION_DESCRIBED_4((condition),(functionDescribed),(format), __VA_ARGS__)

#else // THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL < 4

	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_4(condition, format, ...) ((void)0)
	#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERTION_USE_FUNCTION_DESCRIBED_4(condition,functionDescribed,format, ...) ((void)0)

#endif // 4 <= THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_ASSERT_LEVEL

#endif // THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_HELPER_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_CUSTOM_ASSERT_MACRO_H
