// Copyright (c) 2011-2020
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
//
// 引擎辅助版本：0.1.0.1 (2020/04/06 14:20)

#ifndef THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_MACRO_USER_MACRO_H
#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_MACRO_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define CLOSE_USE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT (0x01) 
#define CLOSE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_MAX ((CLOSE_USE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_CLOSE 0x00

static_assert(0 <= COMPILE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_CLOSE, "COMPILE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_CLOSE <= CLOSE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_MAX, "COMPILE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_CLOSE Must be less than or equal CLOSE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_MAX.");

// 是否编译为静态库
#ifdef BUILDING_STATIC
	#define  BUILDING_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_STATIC
#endif // BUILDING_STATIC

#if !defined(COMPILE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_CLOSE) || (COMPILE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_CLOSE & CLOSE_USE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT) != CLOSE_USE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT

#endif // !defined(COMPILE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_CLOSE) || (COMPILE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_CLOSE & CLOSE_USE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT) != CLOSE_USE_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT 
 
#endif // THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_MACRO_USER_MACRO_H
