// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.0.3 (2019/10/01 12:53)

#ifndef FREEGLUT_LIB_EXAMPLE_DLL_H
#define FREEGLUT_LIB_EXAMPLE_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(FREEGLUT_LIB_EXAMPLE_NO_IMPORT) || defined(BUILDING_FREEGLUT_LIB_EXAMPLE_STATIC)

  #define FREEGLUT_LIB_EXAMPLE_DEFAULT_DECLARE
  #define FREEGLUT_LIB_EXAMPLE_HIDDEN_DECLARE
  #define FREEGLUT_LIB_EXAMPLE_VISIBLE

#else // !defined(FREEGLUT_LIB_EXAMPLE_NO_IMPORT) && !defined(FREEGLUT_LIB_EXAMPLE_STATIC)

   #if defined(FREEGLUT_LIB_EXAMPLE_EXPORT)
 
        #define FREEGLUT_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define FREEGLUT_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(FREEGLUT_LIB_EXAMPLE_EXPORT)

		#define FREEGLUT_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define FREEGLUT_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // FREEGLUT_LIB_EXAMPLE_EXPORT

   #define FREEGLUT_LIB_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(FREEGLUT_LIB_EXAMPLE_NO_IMPORT) || defined(FREEGLUT_LIB_EXAMPLE_STATIC)

#endif // FREEGLUT_LIB_EXAMPLE_DLL_H
