///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.3 (2021/09/23 9:11)

#ifndef BOOK_NETWORK_PROGRAMMING_TOOLSET_NO_IMPORT_H
#define BOOK_NETWORK_PROGRAMMING_TOOLSET_NO_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_BOOK_NETWORK_PROGRAMMING_TOOLSET_NO_IMPORT
    #define BUILDING_BOOK_NETWORK_PROGRAMMING_TOOLSET_NO_IMPORT
#endif  // BUILDING_BOOK_NETWORK_PROGRAMMING_TOOLSET_NO_IMPORT

#endif  // BOOK_NETWORK_PROGRAMMING_TOOLSET_NO_IMPORT_H
