///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.1 (2021/02/07 0:27)

#ifndef ALGORITHMS_IN_CPP_PARTS_1_4_HELPER_USER_MACRO_H
#define ALGORITHMS_IN_CPP_PARTS_1_4_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define ALGORITHMS_IN_CPP_PARTS_1_4_ClOSE_BEGIN (0x01)

#define CLOSE_USE_ALGORITHMS_IN_CPP_PARTS_1_4 (ALGORITHMS_IN_CPP_PARTS_1_4_ClOSE_BEGIN)

#define ALGORITHMS_IN_CPP_PARTS_1_4_ClOSE_END CLOSE_USE_ALGORITHMS_IN_CPP_PARTS_1_4

#define CLOSE_ALGORITHMS_IN_CPP_PARTS_1_4_MAX ((ALGORITHMS_IN_CPP_PARTS_1_4_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_ALGORITHMS_IN_CPP_PARTS_1_4_CLOSE 0x00

static_assert(0 <= COMPILE_ALGORITHMS_IN_CPP_PARTS_1_4_CLOSE, "COMPILE_ALGORITHMS_IN_CPP_PARTS_1_4_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_ALGORITHMS_IN_CPP_PARTS_1_4_CLOSE <= CLOSE_ALGORITHMS_IN_CPP_PARTS_1_4_MAX, "COMPILE_ALGORITHMS_IN_CPP_PARTS_1_4_CLOSE Must be less than or equal CLOSE_ALGORITHMS_IN_CPP_PARTS_1_4_MAX.");

#if !defined(COMPILE_ALGORITHMS_IN_CPP_PARTS_1_4_CLOSE) || (COMPILE_ALGORITHMS_IN_CPP_PARTS_1_4_CLOSE & CLOSE_USE_ALGORITHMS_IN_CPP_PARTS_1_4) != CLOSE_USE_ALGORITHMS_IN_CPP_PARTS_1_4

#endif  // !defined(COMPILE_ALGORITHMS_IN_CPP_PARTS_1_4_CLOSE) || (COMPILE_ALGORITHMS_IN_CPP_PARTS_1_4_CLOSE & CLOSE_USE_ALGORITHMS_IN_CPP_PARTS_1_4) != CLOSE_USE_ALGORITHMS_IN_CPP_PARTS_1_4

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_ALGORITHMS_IN_CPP_PARTS_1_4_STATIC
#endif  // BUILDING_STATIC

#endif  // ALGORITHMS_IN_CPP_PARTS_1_4_HELPER_USER_MACRO_H
