///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.3 (2021/09/02 8:45)

#ifndef CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_DLL_H
#define CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_NO_IMPORT) || defined(BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_STATIC)

    #define CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_DEFAULT_DECLARE
    #define CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_VISIBLE

    #if defined(BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_EXPORT)

        #define CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_HIDDEN_DECLARE

    #else  // !defined(BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_EXPORT)

        #define CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_EXPORT

#else  // !defined(BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_NO_IMPORT) && !defined(BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_STATIC)

    #if defined(BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_EXPORT)

        #define CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_EXPORT)

        #define CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_EXPORT

    #define CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_NO_IMPORT) || defined(BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_STATIC)

#endif  // CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_DLL_H
