///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.3 (2021/09/02 8:44)

#ifndef CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_IMPORT_H
#define CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_IMPORT
    #define BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_IMPORT
#endif  // BUILDING_CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_IMPORT

#endif  // CLIENT_SERVER_PROGRAMMING_AND_APPLICATIONS_IMPORT_H
