/// Copyright (c) 2010-2024
/// Threading Core Render Engine
///
/// 作者：彭武阳，彭晔恩，彭晔泽
/// 联系作者：94458936@qq.com
///
/// 标准：std:c++20
/// 版本：1.0.0.7 (2024/03/04 19:59)

#ifndef SYSTEM_HELPER_PRAGMA_MYSQL_X_XDEV_API_H
#define SYSTEM_HELPER_PRAGMA_MYSQL_X_XDEV_API_H

#ifdef DATABASE_USE_MYSQL_CPP_CONNECTOR

    #include "System/Helper/PragmaWarning.h"

    #include SYSTEM_WARNING_PUSH

    #include SYSTEM_WARNING_DISABLE(4244)
    #include SYSTEM_WARNING_DISABLE(4996)

    #include SYSTEM_WARNING_DISABLE(26416)
    #include SYSTEM_WARNING_DISABLE(26426)
    #include SYSTEM_WARNING_DISABLE(26429)
    #include SYSTEM_WARNING_DISABLE(26434)
    #include SYSTEM_WARNING_DISABLE(26432)
    #include SYSTEM_WARNING_DISABLE(26433)
    #include SYSTEM_WARNING_DISABLE(26436)
    #include SYSTEM_WARNING_DISABLE(26439)
    #include SYSTEM_WARNING_DISABLE(26440)
    #include SYSTEM_WARNING_DISABLE(26446)
    #include SYSTEM_WARNING_DISABLE(26455)
    #include SYSTEM_WARNING_DISABLE(26456)
    #include SYSTEM_WARNING_DISABLE(26466)
    #include SYSTEM_WARNING_DISABLE(26473)
    #include SYSTEM_WARNING_DISABLE(26474)
    #include SYSTEM_WARNING_DISABLE(26481)
    #include SYSTEM_WARNING_DISABLE(26486)
    #include SYSTEM_WARNING_DISABLE(26487)
    #include SYSTEM_WARNING_DISABLE(26489)
    #include SYSTEM_WARNING_DISABLE(26492)
    #include SYSTEM_WARNING_DISABLE(26493)
    #include SYSTEM_WARNING_DISABLE(26495)
    #include SYSTEM_WARNING_DISABLE(26496)
    #include SYSTEM_WARNING_DISABLE(26812)
    #include SYSTEM_WARNING_DISABLE(26819)

    #include <mysqlx/xdevapi.h>

    #include SYSTEM_WARNING_POP

#endif  // DATABASE_USE_MYSQL_CPP_CONNECTOR

#endif  // SYSTEM_HELPER_PRAGMA_MYSQL_X_XDEV_API_H
