/// Copyright (c) 2010-2024
/// Threading Core Render Engine
///
/// 作者：彭武阳，彭晔恩，彭晔泽
/// 联系作者：94458936@qq.com
///
/// 标准：std:c++20
/// 版本：1.0.0.4 (2024/01/11 15:39)

#ifndef INPUT_OUTPUT_MACRO_USER_MACRO_H
#define INPUT_OUTPUT_MACRO_USER_MACRO_H

#include "CoreTools/Helper/UserMacro.h"

#define INPUT_OUTPUT_ClOSE_BEGIN (0x01)

#define CLOSE_USE_INPUT_OUTPUT (INPUT_OUTPUT_ClOSE_BEGIN)

#define INPUT_OUTPUT_ClOSE_END CLOSE_USE_INPUT_OUTPUT

#define CLOSE_INPUT_OUTPUT_MAX (((INPUT_OUTPUT_ClOSE_END) << 1) - 1)

// 编译测试（默认为0B0000，最大值为0B0001）
#define COMPILE_INPUT_OUTPUT_CLOSE 0B0000

static_assert(0 <= COMPILE_INPUT_OUTPUT_CLOSE, "COMPILE_INPUT_OUTPUT_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_INPUT_OUTPUT_CLOSE <= CLOSE_INPUT_OUTPUT_MAX, "COMPILE_INPUT_OUTPUT_CLOSE Must be less than or equal CLOSE_INPUT_OUTPUT_MAX.");

#if !defined(COMPILE_INPUT_OUTPUT_CLOSE) || (COMPILE_INPUT_OUTPUT_CLOSE & CLOSE_USE_INPUT_OUTPUT) != CLOSE_USE_INPUT_OUTPUT

#endif  // !defined(COMPILE_INPUT_OUTPUT_CLOSE) || (COMPILE_INPUT_OUTPUT_CLOSE & CLOSE_USE_INPUT_OUTPUT) != CLOSE_USE_INPUT_OUTPUT

#ifdef BUILDING_STATIC

    #define BUILDING_INPUT_OUTPUT_STATIC

#endif  // BUILDING_STATIC

#endif  // INPUT_OUTPUT_MACRO_USER_MACRO_H
