///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	引擎辅助版本：0.9.0.12 (2023/06/09 10:38)

#ifndef MATHEMATICS_EXAMPLE_HELPER_USER_MACRO_H
#define MATHEMATICS_EXAMPLE_HELPER_USER_MACRO_H

#include "System/Helper/ConfigMacro.h"
#include "CoreTools/Helper/UserMacro.h"

#define CLOSE_USE_XXX (0x01)
#define CLOSE_MATHEMATICS_EXAMPLE_MAX (((CLOSE_USE_XXX) << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_MATHEMATICS_EXAMPLE_CLOSE 0x00

static_assert(0 <= COMPILE_MATHEMATICS_EXAMPLE_CLOSE, "COMPILE_MATHEMATICS_EXAMPLE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_MATHEMATICS_EXAMPLE_CLOSE <= CLOSE_MATHEMATICS_EXAMPLE_MAX, "COMPILE_MATHEMATICS_EXAMPLE_CLOSE Must be less than or equal CLOSE_MATHEMATICS_EXAMPLE_MAX.");

#if !defined(COMPILE_MATHEMATICS_EXAMPLE_CLOSE) || (COMPILE_MATHEMATICS_EXAMPLE_CLOSE & CLOSE_USE_XXX) != CLOSE_USE_XXX

#endif  // !defined(COMPILE_MATHEMATICS_EXAMPLE_CLOSE) || (COMPILE_MATHEMATICS_EXAMPLE_CLOSE & CLOSE_USE_XXX) != CLOSE_USE_XXX

#ifdef BUILDING_STATIC

    #define BUILDING_MATHEMATICS_EXAMPLE_STATIC

#endif  // BUILDING_STATIC

#endif  // MATHEMATICS_EXAMPLE_HELPER_USER_MACRO_H
