///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.1 (2021/03/11 17:53)

#ifndef BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_HELPER_USER_MACRO_H
#define BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_ClOSE_BEGIN (0x01)

#define CLOSE_USE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK (BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_ClOSE_BEGIN)

#define BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_ClOSE_END CLOSE_USE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK

#define CLOSE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_MAX ((BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_CLOSE 0x00

static_assert(0 <= COMPILE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_CLOSE, "COMPILE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_CLOSE <= CLOSE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_MAX, "COMPILE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_CLOSE Must be less than or equal CLOSE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_MAX.");

#if !defined(COMPILE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_CLOSE) || (COMPILE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_CLOSE & CLOSE_USE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK) != CLOSE_USE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK

#endif  // !defined(COMPILE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_CLOSE) || (COMPILE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_CLOSE & CLOSE_USE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK) != CLOSE_USE_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_STATIC
#endif  // BUILDING_STATIC

#endif  // BOOST_CPP_APPLICATION_DEVELOPMENT_COOKBOOK_HELPER_USER_MACRO_H
