///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.1 (2021/02/09 14:57)

#ifndef DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_HELPER_USER_MACRO_H
#define DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_ClOSE_BEGIN (0x01)

#define CLOSE_USE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP (DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_ClOSE_BEGIN)

#define DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_ClOSE_END CLOSE_USE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP

#define CLOSE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_MAX ((DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_CLOSE 0x00

static_assert(0 <= COMPILE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_CLOSE, "COMPILE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_CLOSE <= CLOSE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_MAX, "COMPILE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_CLOSE Must be less than or equal CLOSE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_MAX.");

#if !defined(COMPILE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_CLOSE) || (COMPILE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_CLOSE & CLOSE_USE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP) != CLOSE_USE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP

#endif  // !defined(COMPILE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_CLOSE) || (COMPILE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_CLOSE & CLOSE_USE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP) != CLOSE_USE_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_STATIC
#endif  // BUILDING_STATIC

#endif  // DATA_STRUCTURES_AND_ALGORITHMS_IN_CPP_HELPER_USER_MACRO_H
