// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.0 (2020/01/08 21:28)

#ifndef ARTIFICIAL_INTELLEGENCE_TOOLSET_NO_IMPORT_H
#define ARTIFICIAL_INTELLEGENCE_TOOLSET_NO_IMPORT_H

#include "ArtificialIntellegence/Helper/UserMacro.h"

#ifndef BUILDING_ARTIFICIAL_INTELLEGENCE_TOOLSET_NO_IMPORT
  #define BUILDING_ARTIFICIAL_INTELLEGENCE_TOOLSET_NO_IMPORT
#endif // BUILDING_ARTIFICIAL_INTELLEGENCE_TOOLSET_NO_IMPORT

#endif // ARTIFICIAL_INTELLEGENCE_TOOLSET_NO_IMPORT_H
