// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.0.3 (2019/10/01 10:33)

#ifndef OPENAL_LIB_EXAMPLE_DLL_H
#define OPENAL_LIB_EXAMPLE_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(OPENAL_LIB_EXAMPLE_NO_IMPORT) || defined(OPENAL_LIB_EXAMPLE_STATIC)

  #define OPENAL_LIB_EXAMPLE_DEFAULT_DECLARE
  #define OPENAL_LIB_EXAMPLE_HIDDEN_DECLARE
  #define OPENAL_LIB_EXAMPLE_VISIBLE

#else // !defined(OPENAL_LIB_EXAMPLE_NO_IMPORT) && !defined(OPENAL_LIB_EXAMPLE_STATIC)

   #if defined(OPENAL_LIB_EXAMPLE_EXPORT)
 
        #define OPENAL_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define OPENAL_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(OPENAL_LIB_EXAMPLE_EXPORT)

		#define OPENAL_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define OPENAL_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // OPENAL_LIB_EXAMPLE_EXPORT

   #define OPENAL_LIB_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(OPENAL_LIB_EXAMPLE_NO_IMPORT) || defined(OPENAL_LIB_EXAMPLE_STATIC)

#endif // OPENAL_LIB_EXAMPLE_DLL_H
