///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.1 (2021/01/08 21:29)

#ifndef EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_HELPER_USER_MACRO_H
#define EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_ClOSE_BEGIN (0x01)

#define CLOSE_USE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES (EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_ClOSE_BEGIN)

#define EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_ClOSE_END CLOSE_USE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES

#define CLOSE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_MAX ((EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_CLOSE 0x00

static_assert(0 <= COMPILE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_CLOSE, "COMPILE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_CLOSE <= CLOSE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_MAX, "COMPILE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_CLOSE Must be less than or equal CLOSE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_MAX.");

#if !defined(COMPILE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_CLOSE) || (COMPILE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_CLOSE & CLOSE_USE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES) != CLOSE_USE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES

#endif  // !defined(COMPILE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_CLOSE) || (COMPILE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_CLOSE & CLOSE_USE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES) != CLOSE_USE_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_STATIC
#endif  // BUILDING_STATIC

#endif  // EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_HELPER_USER_MACRO_H
