///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.3 (2021/09/02 8:45)

#ifndef DESIGN_IMPLEMENTATION_AND_INTERNALS_HELPER_DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_MACRO_H
#define DESIGN_IMPLEMENTATION_AND_INTERNALS_HELPER_DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_MACRO_H

#include "UserMacro.h"
#include "CoreTools/Helper/ClassInvariant/UserClassInvariantMacro.h"

#if !defined(DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL)
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL 8
#endif  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

#if !defined(DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL)
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL 8
#endif  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL

static_assert(DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL <= USER_CLASS_INVARIANT_LEVEL, "Class invariant level definition error.");
static_assert(DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL <= USER_CLASS_INVARIANT_CONST_LEVEL, "Class invariant level definition error.");

#if 0 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_0 USER_CLASS_IS_VALID_0
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_0 USER_SELF_CLASS_IS_VALID_0

#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL < 0

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_0 (static_cast<void>(0))
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_0 (static_cast<void>(0))

#endif  // 0 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

#if 1 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_1 USER_CLASS_IS_VALID_1
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_1 USER_SELF_CLASS_IS_VALID_1

#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL < 1

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_1 (static_cast<void>(0))
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_1 (static_cast<void>(0))

#endif  // 1 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

#if 2 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_2 USER_CLASS_IS_VALID_2
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_2 USER_SELF_CLASS_IS_VALID_2

#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL < 2

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_2 (static_cast<void>(0))
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_2 (static_cast<void>(0))

#endif  // 2 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

#if 3 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_3 USER_CLASS_IS_VALID_3
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_3 USER_SELF_CLASS_IS_VALID_3

#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL < 3

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_3 (static_cast<void>(0))
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_3 (static_cast<void>(0))

#endif  // 3 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

#if 4 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_4 USER_CLASS_IS_VALID_4
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_4 USER_SELF_CLASS_IS_VALID_4

#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL < 4

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_4 (static_cast<void>(0))
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_4 (static_cast<void>(0))

#endif  // 4 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

#if 5 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_5 USER_CLASS_IS_VALID_5
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_5 USER_SELF_CLASS_IS_VALID_5

#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL < 5

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_5 (static_cast<void>(0))
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_5 (static_cast<void>(0))

#endif  // 5 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

#if 6 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_6 USER_CLASS_IS_VALID_6
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_6 USER_SELF_CLASS_IS_VALID_6

#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL < 6

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_6 (static_cast<void>(0))
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_6 (static_cast<void>(0))

#endif  // 6 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

#if 7 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_7 USER_CLASS_IS_VALID_7
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_7 USER_SELF_CLASS_IS_VALID_7

#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL < 7

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_7 (static_cast<void>(0))
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_7 (static_cast<void>(0))

#endif  // 7 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

#if 8 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_8 USER_CLASS_IS_VALID_8
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_8 USER_SELF_CLASS_IS_VALID_8

#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL < 8

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_8 (static_cast<void>(0))
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_8 (static_cast<void>(0))

#endif  // 8 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

#if 9 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_9 USER_CLASS_IS_VALID_9
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_9 USER_SELF_CLASS_IS_VALID_9

#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL < 9

    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_9 (static_cast<void>(0))
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_SELF_CLASS_IS_VALID_9 (static_cast<void>(0))

#endif  // 9 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_LEVEL

#if 0 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_0 USER_CLASS_IS_VALID_CONST_0
#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL < 0
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_0 (static_cast<void>(0))
#endif  // 0 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL

#if 1 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_1 USER_CLASS_IS_VALID_CONST_1
#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL < 1
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_1 (static_cast<void>(0))
#endif  // 1 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL

#if 2 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_2 USER_CLASS_IS_VALID_CONST_2
#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL < 2
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_2 (static_cast<void>(0))
#endif  // 2 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL

#if 3 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_3 USER_CLASS_IS_VALID_CONST_3
#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL < 3
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_3 (static_cast<void>(0))
#endif  // 3 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL

#if 4 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_4 USER_CLASS_IS_VALID_CONST_4
#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL < 4
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_4 (static_cast<void>(0))
#endif  // 4 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL

#if 5 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_5 USER_CLASS_IS_VALID_CONST_5
#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL < 5
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_5 (static_cast<void>(0))
#endif  // 5 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL

#if 6 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_6 USER_CLASS_IS_VALID_CONST_6
#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL < 6
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_6 (static_cast<void>(0))
#endif  // 6 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL

#if 7 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_7 USER_CLASS_IS_VALID_CONST_7
#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL < 7
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_7 (static_cast<void>(0))
#endif  // 7 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL

#if 8 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_8 USER_CLASS_IS_VALID_CONST_8
#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL < 8
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_8 (static_cast<void>(0))
#endif  // 8 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL

#if 9 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_9 USER_CLASS_IS_VALID_CONST_9
#else  // DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL < 9
    #define DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_IS_VALID_CONST_9 (static_cast<void>(0))
#endif  // 9 <= DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_CONST_LEVEL

#endif  // DESIGN_IMPLEMENTATION_AND_INTERNALS_HELPER_DESIGN_IMPLEMENTATION_AND_INTERNALS_CLASS_INVARIANT_MACRO_H
