///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.3 (2021/09/02 8:45)

#ifndef DESIGN_IMPLEMENTATION_AND_INTERNALS_HELPER_USER_MACRO_H
#define DESIGN_IMPLEMENTATION_AND_INTERNALS_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define DESIGN_IMPLEMENTATION_AND_INTERNALS_ClOSE_BEGIN (0x01)

#define CLOSE_USE_DESIGN_IMPLEMENTATION_AND_INTERNALS (DESIGN_IMPLEMENTATION_AND_INTERNALS_ClOSE_BEGIN)

#define DESIGN_IMPLEMENTATION_AND_INTERNALS_ClOSE_END CLOSE_USE_DESIGN_IMPLEMENTATION_AND_INTERNALS

#define CLOSE_DESIGN_IMPLEMENTATION_AND_INTERNALS_MAX ((DESIGN_IMPLEMENTATION_AND_INTERNALS_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_DESIGN_IMPLEMENTATION_AND_INTERNALS_CLOSE 0x00

static_assert(0 <= COMPILE_DESIGN_IMPLEMENTATION_AND_INTERNALS_CLOSE, "COMPILE_DESIGN_IMPLEMENTATION_AND_INTERNALS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_DESIGN_IMPLEMENTATION_AND_INTERNALS_CLOSE <= CLOSE_DESIGN_IMPLEMENTATION_AND_INTERNALS_MAX, "COMPILE_DESIGN_IMPLEMENTATION_AND_INTERNALS_CLOSE Must be less than or equal CLOSE_DESIGN_IMPLEMENTATION_AND_INTERNALS_MAX.");

#if !defined(COMPILE_DESIGN_IMPLEMENTATION_AND_INTERNALS_CLOSE) || (COMPILE_DESIGN_IMPLEMENTATION_AND_INTERNALS_CLOSE & CLOSE_USE_DESIGN_IMPLEMENTATION_AND_INTERNALS) != CLOSE_USE_DESIGN_IMPLEMENTATION_AND_INTERNALS

#endif  // !defined(COMPILE_DESIGN_IMPLEMENTATION_AND_INTERNALS_CLOSE) || (COMPILE_DESIGN_IMPLEMENTATION_AND_INTERNALS_CLOSE & CLOSE_USE_DESIGN_IMPLEMENTATION_AND_INTERNALS) != CLOSE_USE_DESIGN_IMPLEMENTATION_AND_INTERNALS

#ifdef BUILDING_STATIC
    #define BUILDING_DESIGN_IMPLEMENTATION_AND_INTERNALS_STATIC
#endif  // BUILDING_STATIC

#endif  // DESIGN_IMPLEMENTATION_AND_INTERNALS_HELPER_USER_MACRO_H
