///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.4 (2021/10/07 23:22)

#ifndef THE_DEVELOPERS_GUIDE_TO_DEBUGGING_HELPER_USER_MACRO_H
#define THE_DEVELOPERS_GUIDE_TO_DEBUGGING_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define THE_DEVELOPERS_GUIDE_TO_DEBUGGING_ClOSE_BEGIN (0x01)

#define CLOSE_USE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING (THE_DEVELOPERS_GUIDE_TO_DEBUGGING_ClOSE_BEGIN)

#define THE_DEVELOPERS_GUIDE_TO_DEBUGGING_ClOSE_END CLOSE_USE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING

#define CLOSE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_MAX ((THE_DEVELOPERS_GUIDE_TO_DEBUGGING_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_CLOSE 0x00

static_assert(0 <= COMPILE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_CLOSE, "COMPILE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_CLOSE <= CLOSE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_MAX, "COMPILE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_CLOSE Must be less than or equal CLOSE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_MAX.");

#if !defined(COMPILE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_CLOSE) || (COMPILE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_CLOSE & CLOSE_USE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING) != CLOSE_USE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING

#endif  // !defined(COMPILE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_CLOSE) || (COMPILE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_CLOSE & CLOSE_USE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING) != CLOSE_USE_THE_DEVELOPERS_GUIDE_TO_DEBUGGING

#ifdef BUILDING_STATIC
    #define BUILDING_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_STATIC
#endif  // BUILDING_STATIC

#endif  // THE_DEVELOPERS_GUIDE_TO_DEBUGGING_HELPER_USER_MACRO_H
