// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
// 
// “˝«Ê∞Ê±æ£∫0.0.2.1 (2020/01/21 11:57)

#ifndef CORE_TOOLS_MEMORY_TOOLS_THIRD_SUBCLASS_SMART_POINTER_DETAIL_H
#define CORE_TOOLS_MEMORY_TOOLS_THIRD_SUBCLASS_SMART_POINTER_DETAIL_H

#include "ThirdSubclassSmartPointer.h"
#include "SmartPointerManager.h"
#include "CoreTools/Helper/MemoryMacro.h"
#include "CoreTools/Helper/ClassInvariant/CoreToolsClassInvariantMacro.h"

SUBCLASS_SMART_POINTER_DEFINE(Third)
SUBCLASS_SMART_POINTER_DEFINE(Fourth)
SUBCLASS_SMART_POINTER_DEFINE(Fifth)
SUBCLASS_SMART_POINTER_DEFINE(Sixth)
SUBCLASS_SMART_POINTER_DEFINE(Seventh)
SUBCLASS_SMART_POINTER_DEFINE(Eighth)
SUBCLASS_SMART_POINTER_DEFINE(Ninth)
SUBCLASS_SMART_POINTER_DEFINE(Tenth)

#endif // CORE_TOOLS_MEMORY_TOOLS_THIRD_SUBCLASS_SMART_POINTER_DETAIL_H
