///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.6 (2021/11/21 20:59)

#ifndef LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_HELPER_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_CUSTOM_ASSERT_MACRO_H
#define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_HELPER_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_CUSTOM_ASSERT_MACRO_H

#include "UserMacro.h"
#include "CoreTools/Helper/Assertion/UserCustomAssertMacro.h"

#if defined(OPEN_IMPORTANT_EXCPTION_ASSERT)
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL 0
#endif  // OPEN_IMPORTANT_EXCPTION_ASSERT

#if !defined(LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL)
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL 4
#endif  // LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL

constexpr auto g_LinuxCommandLineAndShellScriptingBibleAssert = LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL;

static_assert(LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL <= USER_ASSERT_LEVEL, "Assert level definition error.");

#if 0 <= LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL

    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_0(condition, format, ...) \
        USER_ASSERTION_0((condition), (format), __VA_ARGS__)
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_USE_FUNCTION_DESCRIBED_0(condition, functionDescribed, format, ...) \
        USER_ASSERTION_USE_FUNCTION_DESCRIBED_0((condition), (functionDescribed), (format), __VA_ARGS__)

    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_DEBUG(condition, format, ...) \
        USER_ASSERTION_DEBUG((condition), (format), __VA_ARGS__)
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_DEBUG_USE_FUNCTION_DESCRIBED(condition, functionDescribed, format, ...) \
        USER_ASSERTION_DEBUG_USE_FUNCTION_DESCRIBED((condition), (functionDescribed), (format), __VA_ARGS__)

#else  // LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL < 0

    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_0(condition, format, ...) (static_cast<void>(0))
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_USE_FUNCTION_DESCRIBED_0(condition, functionDescribed, format, ...) (static_cast<void>(0))

    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_DEBUG(condition, format, ...) (static_cast<void>(0))
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_DEBUG_USE_FUNCTION_DESCRIBED(condition, functionDescribed, format, ...) (static_cast<void>(0))

#endif  // 0 <= LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL

#if 1 <= LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL

    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_1(condition, format, ...) \
        USER_ASSERTION_1((condition), (format), __VA_ARGS__)
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_USE_FUNCTION_DESCRIBED_1(condition, functionDescribed, format, ...) \
        USER_ASSERTION_USE_FUNCTION_DESCRIBED_1((condition), (functionDescribed), (format), __VA_ARGS__)

#else  // LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL < 1

    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_1(condition, format, ...) (static_cast<void>(0))
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_USE_FUNCTION_DESCRIBED_1(condition, functionDescribed, format, ...) (static_cast<void>(0))

#endif  // 1 <= LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL

#if 2 <= LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL

    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_2(condition, format, ...) \
        USER_ASSERTION_2((condition), (format), __VA_ARGS__)
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_USE_FUNCTION_DESCRIBED_2(condition, functionDescribed, format, ...) \
        USER_ASSERTION_USE_FUNCTION_DESCRIBED_2((condition), (functionDescribed), (format), __VA_ARGS__)

#else  // LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL < 2

    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_2(condition, format, ...) (static_cast<void>(0))
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_USE_FUNCTION_DESCRIBED_2(condition, functionDescribed, format, ...) (static_cast<void>(0))

#endif  // 2 <= LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL

#if 3 <= LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL

    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_3(condition, format, ...) \
        USER_ASSERTION_3((condition), (format), __VA_ARGS__)
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_USE_FUNCTION_DESCRIBED_3(condition, functionDescribed, format, ...) \
        USER_ASSERTION_USE_FUNCTION_DESCRIBED_3((condition), (functionDescribed), (format), __VA_ARGS__)

#else  // LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL < 3

    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_3(condition, format, ...) (static_cast<void>(0))
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_USE_FUNCTION_DESCRIBED_3(condition, functionDescribed, format, ...) (static_cast<void>(0))

#endif  // 3 <= LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL

#if 4 <= LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL

    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_4(condition, format, ...) \
        USER_ASSERTION_4((condition), (format), __VA_ARGS__)
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_USE_FUNCTION_DESCRIBED_4(condition, functionDescribed, format, ...) \
        USER_ASSERTION_USE_FUNCTION_DESCRIBED_4((condition), (functionDescribed), (format), __VA_ARGS__)

#else  // LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL < 4

    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_4(condition, format, ...) (static_cast<void>(0))
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERTION_USE_FUNCTION_DESCRIBED_4(condition, functionDescribed, format, ...) (static_cast<void>(0))

#endif  // 4 <= LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_ASSERT_LEVEL

#endif  // LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_HELPER_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_CUSTOM_ASSERT_MACRO_H
