// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.0 (2020/01/07 22:36)

#ifndef PHYSICS_TOOLSET_DLL_DLL_H
#define PHYSICS_TOOLSET_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Physics/Helper/UserMacro.h"

#if defined(BUILDING_PHYSICS_TOOLSET_NO_IMPORT) || defined(BUILDING_PHYSICS_STATIC)

  #define PHYSICS_TOOLSET_DEFAULT_DECLARE
  #define PHYSICS_TOOLSET_HIDDEN_DECLARE
  #define PHYSICS_TOOLSET_VISIBLE

#else // !defined(BUILDING_PHYSICS_TOOLSET_NO_IMPORT) && !defined(BUILDING_PHYSICS_STATIC)

   #if defined(BUILDING_PHYSICS_TOOLSET_EXPORT)
 
        #define PHYSICS_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define PHYSICS_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_PHYSICS_TOOLSET_EXPORT)

		#define PHYSICS_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define PHYSICS_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_PHYSICS_TOOLSET_EXPORT

   #define PHYSICS_TOOLSET_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_PHYSICS_TOOLSET_NO_IMPORT) || defined(BUILDING_PHYSICS_STATIC)

#endif // PHYSICS_TOOLSET_DLL_DLL_H
