///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.6 (2021/11/21 20:58)

#ifndef BEGINNING_LINUX_PROGRAMMING_EXPORT_H
#define BEGINNING_LINUX_PROGRAMMING_EXPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_BEGINNING_LINUX_PROGRAMMING_EXPORT
    #define BUILDING_BEGINNING_LINUX_PROGRAMMING_EXPORT
#endif  // BUILDING_BEGINNING_LINUX_PROGRAMMING_EXPORT

#endif  // BEGINNING_LINUX_PROGRAMMING_EXPORT_H
