///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.6 (2021/11/21 20:58)

#ifndef BEGINNING_LINUX_PROGRAMMING_DLL_H
#define BEGINNING_LINUX_PROGRAMMING_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_BEGINNING_LINUX_PROGRAMMING_NO_IMPORT) || defined(BUILDING_BEGINNING_LINUX_PROGRAMMING_STATIC)

    #define BEGINNING_LINUX_PROGRAMMING_DEFAULT_DECLARE
    #define BEGINNING_LINUX_PROGRAMMING_VISIBLE

    #if defined(BUILDING_BEGINNING_LINUX_PROGRAMMING_EXPORT)

        #define BEGINNING_LINUX_PROGRAMMING_HIDDEN_DECLARE

    #else  // !defined(BUILDING_BEGINNING_LINUX_PROGRAMMING_EXPORT)

        #define BEGINNING_LINUX_PROGRAMMING_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_BEGINNING_LINUX_PROGRAMMING_EXPORT

#else  // !defined(BUILDING_BEGINNING_LINUX_PROGRAMMING_NO_IMPORT) && !defined(BUILDING_BEGINNING_LINUX_PROGRAMMING_STATIC)

    #if defined(BUILDING_BEGINNING_LINUX_PROGRAMMING_EXPORT)

        #define BEGINNING_LINUX_PROGRAMMING_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define BEGINNING_LINUX_PROGRAMMING_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_BEGINNING_LINUX_PROGRAMMING_EXPORT)

        #define BEGINNING_LINUX_PROGRAMMING_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define BEGINNING_LINUX_PROGRAMMING_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_BEGINNING_LINUX_PROGRAMMING_EXPORT

    #define BEGINNING_LINUX_PROGRAMMING_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_BEGINNING_LINUX_PROGRAMMING_NO_IMPORT) || defined(BUILDING_BEGINNING_LINUX_PROGRAMMING_STATIC)

#endif  // BEGINNING_LINUX_PROGRAMMING_DLL_H
