///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.2 (2021/03/27 22:02)

#ifndef STL_TUTORIAL_AND_REFERENCE_GUIDE_HELPER_USER_MACRO_H
#define STL_TUTORIAL_AND_REFERENCE_GUIDE_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define STL_TUTORIAL_AND_REFERENCE_GUIDE_ClOSE_BEGIN (0x01)

#define CLOSE_USE_STL_TUTORIAL_AND_REFERENCE_GUIDE (STL_TUTORIAL_AND_REFERENCE_GUIDE_ClOSE_BEGIN)

#define STL_TUTORIAL_AND_REFERENCE_GUIDE_ClOSE_END CLOSE_USE_STL_TUTORIAL_AND_REFERENCE_GUIDE

#define CLOSE_STL_TUTORIAL_AND_REFERENCE_GUIDE_MAX ((STL_TUTORIAL_AND_REFERENCE_GUIDE_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_STL_TUTORIAL_AND_REFERENCE_GUIDE_CLOSE 0x00

static_assert(0 <= COMPILE_STL_TUTORIAL_AND_REFERENCE_GUIDE_CLOSE, "COMPILE_STL_TUTORIAL_AND_REFERENCE_GUIDE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_STL_TUTORIAL_AND_REFERENCE_GUIDE_CLOSE <= CLOSE_STL_TUTORIAL_AND_REFERENCE_GUIDE_MAX, "COMPILE_STL_TUTORIAL_AND_REFERENCE_GUIDE_CLOSE Must be less than or equal CLOSE_STL_TUTORIAL_AND_REFERENCE_GUIDE_MAX.");

#if !defined(COMPILE_STL_TUTORIAL_AND_REFERENCE_GUIDE_CLOSE) || (COMPILE_STL_TUTORIAL_AND_REFERENCE_GUIDE_CLOSE & CLOSE_USE_STL_TUTORIAL_AND_REFERENCE_GUIDE) != CLOSE_USE_STL_TUTORIAL_AND_REFERENCE_GUIDE

#endif  // !defined(COMPILE_STL_TUTORIAL_AND_REFERENCE_GUIDE_CLOSE) || (COMPILE_STL_TUTORIAL_AND_REFERENCE_GUIDE_CLOSE & CLOSE_USE_STL_TUTORIAL_AND_REFERENCE_GUIDE) != CLOSE_USE_STL_TUTORIAL_AND_REFERENCE_GUIDE

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_STL_TUTORIAL_AND_REFERENCE_GUIDE_STATIC
#endif  // BUILDING_STATIC

#endif  // STL_TUTORIAL_AND_REFERENCE_GUIDE_HELPER_USER_MACRO_H
