@echo on
 
start /d %RiseOfHistoryTestingWin32DebugLib% DatabaseServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingWin32ReleaseLib% DatabaseServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingX64DebugLib% DatabaseServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingX64ReleaseLib% DatabaseServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingStaticWin32DebugLib% DatabaseServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingStaticWin32ReleaseLib% DatabaseServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingStaticX64DebugLib% DatabaseServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingStaticX64ReleaseLib% DatabaseServerMiddleLayerTestingStatic.exe

start /d %RiseOfHistoryTestingEngineStaticGameDynamicWin32DebugLib% DatabaseServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicWin32ReleaseLib% DatabaseServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicX64DebugLib% DatabaseServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicX64ReleaseLib% DatabaseServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticWin32DebugLib% DatabaseServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticWin32ReleaseLib% DatabaseServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticX64DebugLib% DatabaseServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticX64ReleaseLib% DatabaseServerMiddleLayerTesting.exe

pause