@echo on
 
start /d %RiseOfHistoryTestingWin32DebugLib% FightingServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingWin32ReleaseLib% FightingServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingX64DebugLib% FightingServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingX64ReleaseLib% FightingServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingStaticWin32DebugLib% FightingServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingStaticWin32ReleaseLib% FightingServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingStaticX64DebugLib% FightingServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingStaticX64ReleaseLib% FightingServerMiddleLayerTestingStatic.exe

start /d %RiseOfHistoryTestingEngineStaticGameDynamicWin32DebugLib% FightingServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicWin32ReleaseLib% FightingServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicX64DebugLib% FightingServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicX64ReleaseLib% FightingServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticWin32DebugLib% FightingServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticWin32ReleaseLib% FightingServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticX64DebugLib% FightingServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticX64ReleaseLib% FightingServerMiddleLayerTesting.exe

pause