@echo on
 
start /d %RiseOfHistoryTestingWin32DebugLib% GatewayServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingWin32ReleaseLib% GatewayServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingX64DebugLib% GatewayServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingX64ReleaseLib% GatewayServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingStaticWin32DebugLib% GatewayServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingStaticWin32ReleaseLib% GatewayServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingStaticX64DebugLib% GatewayServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingStaticX64ReleaseLib% GatewayServerMiddleLayerTestingStatic.exe

start /d %RiseOfHistoryTestingEngineStaticGameDynamicWin32DebugLib% GatewayServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicWin32ReleaseLib% GatewayServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicX64DebugLib% GatewayServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicX64ReleaseLib% GatewayServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticWin32DebugLib% GatewayServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticWin32ReleaseLib% GatewayServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticX64DebugLib% GatewayServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticX64ReleaseLib% GatewayServerMiddleLayerTesting.exe

pause