@echo on
 
start /d %RiseOfHistoryTestingWin32DebugLib% LoginServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingWin32ReleaseLib% LoginServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingX64DebugLib% LoginServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingX64ReleaseLib% LoginServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingStaticWin32DebugLib% LoginServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingStaticWin32ReleaseLib% LoginServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingStaticX64DebugLib% LoginServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingStaticX64ReleaseLib% LoginServerMiddleLayerTestingStatic.exe

start /d %RiseOfHistoryTestingEngineStaticGameDynamicWin32DebugLib% LoginServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicWin32ReleaseLib% LoginServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicX64DebugLib% LoginServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicX64ReleaseLib% LoginServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticWin32DebugLib% LoginServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticWin32ReleaseLib% LoginServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticX64DebugLib% LoginServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticX64ReleaseLib% LoginServerMiddleLayerTesting.exe

pause