@echo on
 
start /d %RiseOfHistoryTestingWin32DebugLib% LeaderboardServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingWin32ReleaseLib% LeaderboardServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingX64DebugLib% LeaderboardServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingX64ReleaseLib% LeaderboardServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingStaticWin32DebugLib% LeaderboardServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingStaticWin32ReleaseLib% LeaderboardServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingStaticX64DebugLib% LeaderboardServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingStaticX64ReleaseLib% LeaderboardServerMiddleLayerTestingStatic.exe

start /d %RiseOfHistoryTestingEngineStaticGameDynamicWin32DebugLib% LeaderboardServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicWin32ReleaseLib% LeaderboardServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicX64DebugLib% LeaderboardServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicX64ReleaseLib% LeaderboardServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticWin32DebugLib% LeaderboardServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticWin32ReleaseLib% LeaderboardServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticX64DebugLib% LeaderboardServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticX64ReleaseLib% LeaderboardServerMiddleLayerTesting.exe

pause