@echo on
 
start /d %RiseOfHistoryTestingWin32DebugLib% UpdateServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingWin32ReleaseLib% UpdateServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingX64DebugLib% UpdateServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingX64ReleaseLib% UpdateServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingStaticWin32DebugLib% UpdateServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingStaticWin32ReleaseLib% UpdateServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingStaticX64DebugLib% UpdateServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingStaticX64ReleaseLib% UpdateServerMiddleLayerTestingStatic.exe

start /d %RiseOfHistoryTestingEngineStaticGameDynamicWin32DebugLib% UpdateServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicWin32ReleaseLib% UpdateServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicX64DebugLib% UpdateServerMiddleLayerTestingStaticD.exe
start /d %RiseOfHistoryTestingEngineStaticGameDynamicX64ReleaseLib% UpdateServerMiddleLayerTestingStatic.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticWin32DebugLib% UpdateServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticWin32ReleaseLib% UpdateServerMiddleLayerTesting.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticX64DebugLib% UpdateServerMiddleLayerTestingD.exe
start /d %RiseOfHistoryTestingEngineDynamicGameStaticX64ReleaseLib% UpdateServerMiddleLayerTesting.exe

pause