///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	引擎辅助版本：0.9.0.12 (2023/06/12 17:05)

#ifndef IMAGICS_TOOLSET_DLL_DLL_H
#define IMAGICS_TOOLSET_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Imagics/Helper/UserMacro.h"

#if defined(BUILDING_IMAGICS_TOOLSET_NO_IMPORT) || defined(BUILDING_IMAGICS_STATIC)

    #define IMAGICS_TOOLSET_DEFAULT_DECLARE
    #define IMAGICS_TOOLSET_VISIBLE

    #if defined(BUILDING_IMAGICS_TOOLSET_EXPORT)

        #define IMAGICS_TOOLSET_HIDDEN_DECLARE

    #else  // !defined(BUILDING_IMAGICS_TOOLSET_EXPORT)

        #define IMAGICS_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_IMAGICS_TOOLSET_EXPORT

#else  // !defined(BUILDING_IMAGICS_TOOLSET_NO_IMPORT) && !defined(BUILDING_IMAGICS_STATIC)

    #if defined(BUILDING_IMAGICS_TOOLSET_EXPORT)

        #define IMAGICS_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define IMAGICS_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_IMAGICS_TOOLSET_EXPORT)

        #define IMAGICS_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define IMAGICS_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_IMAGICS_TOOLSET_EXPORT

    #define IMAGICS_TOOLSET_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_IMAGICS_TOOLSET_NO_IMPORT) || defined(BUILDING_IMAGICS_STATIC)

#endif  // IMAGICS_TOOLSET_DLL_DLL_H
