///	Copyright (c) 2010-2022
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	引擎游戏版本：0.8.0.11 (2022/07/13 17:04)

#ifndef THREADING_CORE_RENDER_ENGINE_GAME_NO_IMPORT_H
#define THREADING_CORE_RENDER_ENGINE_GAME_NO_IMPORT_H

#include "UserMacro.h"

#ifndef BUILDING_THREADING_CORE_RENDER_ENGINE_GAME_NO_IMPORT
    #define BUILDING_THREADING_CORE_RENDER_ENGINE_GAME_NO_IMPORT
#endif  // BUILDING_THREADING_CORE_RENDER_ENGINE_GAME_NO_IMPORT

#endif  // THREADING_CORE_RENDER_ENGINE_GAME_NO_IMPORT_H