///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	引擎辅助版本：0.9.0.12 (2023/06/15 18:15)

#ifndef EDITOR_TOOLSET_DLL_DLL_H
#define EDITOR_TOOLSET_DLL_DLL_H

#include "Helper/Helper.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_EDITOR_TOOLSET_NO_IMPORT) || defined(BUILDING_EDITOR_STATIC)

    #define EDITOR_TOOLSET_DEFAULT_DECLARE
    #define EDITOR_TOOLSET_VISIBLE

    #if defined(BUILDING_EDITOR_TOOLSET_EXPORT)

        #define EDITOR_TOOLSET_HIDDEN_DECLARE

    #else  // !defined(BUILDING_EDITOR_TOOLSET_EXPORT)

        #define EDITOR_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_EDITOR_TOOLSET_EXPORT

#else  // !defined(BUILDING_EDITOR_TOOLSET_NO_IMPORT) && !defined(BUILDING_EDITOR_STATIC)

    #if defined(BUILDING_EDITOR_TOOLSET_EXPORT)

        #define EDITOR_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define EDITOR_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_EDITOR_TOOLSET_EXPORT)

        #define EDITOR_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define EDITOR_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_EDITOR_TOOLSET_EXPORT

    #define EDITOR_TOOLSET_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_EDITOR_TOOLSET_NO_IMPORT) || defined(BUILDING_EDITOR_STATIC)

#endif  // EDITOR_TOOLSET_DLL_DLL_H
