///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.1 (2021/02/09 14:57)

#ifndef NUMERICAL_RECIPES_IN_CPP_DLL_H
#define NUMERICAL_RECIPES_IN_CPP_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_NUMERICAL_RECIPES_IN_CPP_NO_IMPORT) || defined(BUILDING_NUMERICAL_RECIPES_IN_CPP_STATIC)

    #define NUMERICAL_RECIPES_IN_CPP_DEFAULT_DECLARE
    #define NUMERICAL_RECIPES_IN_CPP_HIDDEN_DECLARE
    #define NUMERICAL_RECIPES_IN_CPP_VISIBLE

#else  // !defined(BUILDING_NUMERICAL_RECIPES_IN_CPP_NO_IMPORT) && !defined(BUILDING_NUMERICAL_RECIPES_IN_CPP_STATIC)

    #if defined(BUILDING_NUMERICAL_RECIPES_IN_CPP_EXPORT)

        #define NUMERICAL_RECIPES_IN_CPP_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define NUMERICAL_RECIPES_IN_CPP_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_NUMERICAL_RECIPES_IN_CPP_EXPORT)

        #define NUMERICAL_RECIPES_IN_CPP_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define NUMERICAL_RECIPES_IN_CPP_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_NUMERICAL_RECIPES_IN_CPP_EXPORT

    #define NUMERICAL_RECIPES_IN_CPP_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_NUMERICAL_RECIPES_IN_CPP_NO_IMPORT) || defined(BUILDING_NUMERICAL_RECIPES_IN_CPP_STATIC)

#endif  // NUMERICAL_RECIPES_IN_CPP_DLL_H
