///	Copyright (c) 2010-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.0 (2020/12/26 21:32)

#ifndef PROBLEM_SOLVING_WITH_CPP_HELPER_USER_MACRO_H
#define PROBLEM_SOLVING_WITH_CPP_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define PROBLEM_SOLVING_WITH_CPP_ClOSE_BEGIN (0x01)

#define CLOSE_USE_PROBLEM_SOLVING_WITH_CPP (PROBLEM_SOLVING_WITH_CPP_ClOSE_BEGIN)

#define PROBLEM_SOLVING_WITH_CPP_ClOSE_END CLOSE_USE_PROBLEM_SOLVING_WITH_CPP

#define CLOSE_PROBLEM_SOLVING_WITH_CPP_MAX ((PROBLEM_SOLVING_WITH_CPP_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_PROBLEM_SOLVING_WITH_CPP_CLOSE 0x00

static_assert(0 <= COMPILE_PROBLEM_SOLVING_WITH_CPP_CLOSE, "COMPILE_PROBLEM_SOLVING_WITH_CPP_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_PROBLEM_SOLVING_WITH_CPP_CLOSE <= CLOSE_PROBLEM_SOLVING_WITH_CPP_MAX, "COMPILE_PROBLEM_SOLVING_WITH_CPP_CLOSE Must be less than or equal CLOSE_PROBLEM_SOLVING_WITH_CPP_MAX.");

#if !defined(COMPILE_PROBLEM_SOLVING_WITH_CPP_CLOSE) || (COMPILE_PROBLEM_SOLVING_WITH_CPP_CLOSE & CLOSE_USE_PROBLEM_SOLVING_WITH_CPP) != CLOSE_USE_PROBLEM_SOLVING_WITH_CPP

#endif  // !defined(COMPILE_PROBLEM_SOLVING_WITH_CPP_CLOSE) || (COMPILE_PROBLEM_SOLVING_WITH_CPP_CLOSE & CLOSE_USE_PROBLEM_SOLVING_WITH_CPP) != CLOSE_USE_PROBLEM_SOLVING_WITH_CPP

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_PROBLEM_SOLVING_WITH_CPP_STATIC
#endif  // BUILDING_STATIC

#endif  // PROBLEM_SOLVING_WITH_CPP_HELPER_USER_MACRO_H
