///	Copyright (c) 2010-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.0 (2020/12/27 19:47)

#ifndef SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_HELPER_USER_MACRO_H
#define SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_ClOSE_BEGIN (0x01)

#define CLOSE_USE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY (SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_ClOSE_BEGIN)

#define SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_ClOSE_END CLOSE_USE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY

#define CLOSE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_MAX ((SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_CLOSE 0x00

static_assert(0 <= COMPILE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_CLOSE, "COMPILE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_CLOSE <= CLOSE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_MAX, "COMPILE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_CLOSE Must be less than or equal CLOSE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_MAX.");

#if !defined(COMPILE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_CLOSE) || (COMPILE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_CLOSE & CLOSE_USE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY) != CLOSE_USE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY

#endif  // !defined(COMPILE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_CLOSE) || (COMPILE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_CLOSE & CLOSE_USE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY) != CLOSE_USE_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_STATIC
#endif  // BUILDING_STATIC

#endif  // SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_HELPER_USER_MACRO_H
