// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 最后的霸王版本：0.0.0.1 (2019/10/11 11:49)

#ifndef GATEWAY_SERVER_MIDDLE_LAYER_NO_IMPORT_H
#define GATEWAY_SERVER_MIDDLE_LAYER_NO_IMPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_GATEWAY_SERVER_MIDDLE_LAYER_NO_IMPORT
  #define BUILDING_GATEWAY_SERVER_MIDDLE_LAYER_NO_IMPORT
#endif // BUILDING_GATEWAY_SERVER_MIDDLE_LAYER_NO_IMPORT

#endif // GATEWAY_SERVER_MIDDLE_LAYER_NO_IMPORT_H
