///	Copyright (c) 2010-2022
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	最后的霸王版本：0.8.0.12 (2022/07/23 13:44)

#ifndef GATEWAY_SERVER_MIDDLE_LAYER_NO_IMPORT_H
#define GATEWAY_SERVER_MIDDLE_LAYER_NO_IMPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_GATEWAY_SERVER_MIDDLE_LAYER_NO_IMPORT
    #define BUILDING_GATEWAY_SERVER_MIDDLE_LAYER_NO_IMPORT
#endif  // BUILDING_GATEWAY_SERVER_MIDDLE_LAYER_NO_IMPORT

#endif  // GATEWAY_SERVER_MIDDLE_LAYER_NO_IMPORT_H
