///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.1 (2021/03/06 16:30)

#ifndef USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_HELPER_USER_MACRO_H
#define USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_ClOSE_BEGIN (0x01)

#define CLOSE_USE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES (USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_ClOSE_BEGIN)

#define USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_ClOSE_END CLOSE_USE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES

#define CLOSE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_MAX ((USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_CLOSE 0x00

static_assert(0 <= COMPILE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_CLOSE, "COMPILE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_CLOSE <= CLOSE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_MAX, "COMPILE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_CLOSE Must be less than or equal CLOSE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_MAX.");

#if !defined(COMPILE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_CLOSE) || (COMPILE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_CLOSE & CLOSE_USE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES) != CLOSE_USE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES

#endif  // !defined(COMPILE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_CLOSE) || (COMPILE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_CLOSE & CLOSE_USE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES) != CLOSE_USE_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_STATIC
#endif  // BUILDING_STATIC

#endif  // USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_HELPER_USER_MACRO_H
