///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.3 (2021/09/02 8:45)

#ifndef PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_DLL_H
#define PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_NO_IMPORT) || defined(BUILDING_PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_STATIC)

    #define PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_DEFAULT_DECLARE
    #define PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_VISIBLE

    #if defined(BUILDING_PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_EXPORT)

        #define PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_HIDDEN_DECLARE

    #else  // !defined(BUILDING_PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_EXPORT)

        #define PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_EXPORT

#else  // !defined(BUILDING_PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_NO_IMPORT) && !defined(BUILDING_PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_STATIC)

    #if defined(BUILDING_PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_EXPORT)

        #define PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_EXPORT)

        #define PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_EXPORT

    #define PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_NO_IMPORT) || defined(BUILDING_PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_STATIC)

#endif  // PRINCIPLES_PROTOCOLS_AND_ARCHITECTURES_DLL_H
