///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.3 (2021/05/19 23:08)

#ifndef IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_HELPER_USER_MACRO_H
#define IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_ClOSE_BEGIN (0x01)

#define CLOSE_USE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION (IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_ClOSE_BEGIN)

#define IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_ClOSE_END CLOSE_USE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION

#define CLOSE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_MAX ((IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_CLOSE 0x00

static_assert(0 <= COMPILE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_CLOSE, "COMPILE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_CLOSE <= CLOSE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_MAX, "COMPILE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_CLOSE Must be less than or equal CLOSE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_MAX.");

#if !defined(COMPILE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_CLOSE) || (COMPILE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_CLOSE & CLOSE_USE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION) != CLOSE_USE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION

#endif  // !defined(COMPILE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_CLOSE) || (COMPILE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_CLOSE & CLOSE_USE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION) != CLOSE_USE_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION

#ifdef BUILDING_STATIC
    #define BUILDING_IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_STATIC
#endif  // BUILDING_STATIC

#endif  // IVOR_HORTONS_BEGINNING_VISUAL_CPP_FIFTH_EDITION_HELPER_USER_MACRO_H
