///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.3 (2021/09/22 21:07)

#ifndef TCP_IP_PROTOCOL_SUITE_DLL_H
#define TCP_IP_PROTOCOL_SUITE_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_TCP_IP_PROTOCOL_SUITE_NO_IMPORT) || defined(BUILDING_TCP_IP_PROTOCOL_SUITE_STATIC)

    #define TCP_IP_PROTOCOL_SUITE_DEFAULT_DECLARE
    #define TCP_IP_PROTOCOL_SUITE_VISIBLE

    #if defined(BUILDING_TCP_IP_PROTOCOL_SUITE_EXPORT)

        #define TCP_IP_PROTOCOL_SUITE_HIDDEN_DECLARE

    #else  // !defined(BUILDING_TCP_IP_PROTOCOL_SUITE_EXPORT)

        #define TCP_IP_PROTOCOL_SUITE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_TCP_IP_PROTOCOL_SUITE_EXPORT

#else  // !defined(BUILDING_TCP_IP_PROTOCOL_SUITE_NO_IMPORT) && !defined(BUILDING_TCP_IP_PROTOCOL_SUITE_STATIC)

    #if defined(BUILDING_TCP_IP_PROTOCOL_SUITE_EXPORT)

        #define TCP_IP_PROTOCOL_SUITE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define TCP_IP_PROTOCOL_SUITE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_TCP_IP_PROTOCOL_SUITE_EXPORT)

        #define TCP_IP_PROTOCOL_SUITE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define TCP_IP_PROTOCOL_SUITE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_TCP_IP_PROTOCOL_SUITE_EXPORT

    #define TCP_IP_PROTOCOL_SUITE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_TCP_IP_PROTOCOL_SUITE_NO_IMPORT) || defined(BUILDING_TCP_IP_PROTOCOL_SUITE_STATIC)

#endif  // TCP_IP_PROTOCOL_SUITE_DLL_H
