// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.1.0.1 (2020/04/07 21:10)

#ifndef THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_DLL_H
#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Helper/UserMacro.h"

#if defined(BUILDING_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_NO_IMPORT) || defined(BUILDING_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_STATIC)

  #define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_DEFAULT_DECLARE
  #define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_HIDDEN_DECLARE 
  #define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_VISIBLE

#else // !defined(BUILDING_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_NO_IMPORT) && !defined(BUILDING_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_STATIC)
 
   #if defined(BUILDING_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_EXPORT)
 
        #define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_EXPORT)

		#define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_EXPORT

   #define THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_NO_IMPORT) || defined(BUILDING_3D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_STATIC)
 
#endif // THREE_D_MATH_PRIMER_FOR_GRAPHICS_AND_GAME_DEVELOPMENT_DLL_H
