///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.0 (2021/01/24 15:21)

#ifndef CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_HELPER_USER_MACRO_H
#define CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_ClOSE_BEGIN (0x01)

#define CLOSE_USE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION (CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_ClOSE_BEGIN)

#define CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_ClOSE_END CLOSE_USE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION

#define CLOSE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_MAX ((CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_CLOSE 0x00

static_assert(0 <= COMPILE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_CLOSE, "COMPILE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_CLOSE <= CLOSE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_MAX, "COMPILE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_CLOSE Must be less than or equal CLOSE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_MAX.");

#if !defined(COMPILE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_CLOSE) || (COMPILE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_CLOSE & CLOSE_USE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION) != CLOSE_USE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION

#endif  // !defined(COMPILE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_CLOSE) || (COMPILE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_CLOSE & CLOSE_USE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION) != CLOSE_USE_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_STATIC
#endif  // BUILDING_STATIC

#endif  // CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_HELPER_USER_MACRO_H
