// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
// 
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.0.3 (2019/09/30 16:14)

#ifndef STLSOFT_LIB_EXAMPLE_DLL_H
#define STLSOFT_LIB_EXAMPLE_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(STLSOFT_LIB_EXAMPLE_NO_IMPORT) || defined(BUILDING_STLSOFT_LIB_EXAMPLE_STATIC)

  #define STLSOFT_LIB_EXAMPLE_DEFAULT_DECLARE
  #define STLSOFT_LIB_EXAMPLE_HIDDEN_DECLARE
  #define STLSOFT_LIB_EXAMPLE_VISIBLE

#else // !defined(STLSOFT_LIB_EXAMPLE_NO_IMPORT) && !defined(BUILDING_STLSOFT_LIB_EXAMPLE_STATIC)

   #if defined(STLSOFT_LIB_EXAMPLE_EXPORT)
 
        #define STLSOFT_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define STLSOFT_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(STLSOFT_LIB_EXAMPLE_EXPORT)

		#define STLSOFT_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define STLSOFT_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // STLSOFT_LIB_EXAMPLE_EXPORT

   #define STLSOFT_LIB_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(STLSOFT_LIB_EXAMPLE_NO_IMPORT) || defined(BUILDING_STLSOFT_LIB_EXAMPLE_STATIC)

#endif // STLSOFT_LIB_EXAMPLE_DLL_H
