// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
//
// 最后的霸王版本：0.0.0.1 (2019/10/12 23:03)

#ifndef LOG_SERVER_MIDDLE_LAYER_NO_IMPORT_H
#define LOG_SERVER_MIDDLE_LAYER_NO_IMPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_LOG_SERVER_MIDDLE_LAYER_NO_IMPORT
  #define BUILDING_LOG_SERVER_MIDDLE_LAYER_NO_IMPORT
#endif // BUILDING_LOG_SERVER_MIDDLE_LAYER_NO_IMPORT

#endif // LOG_SERVER_MIDDLE_LAYER_NO_IMPORT_H
