///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.1 (2021/03/06 16:29)

#ifndef USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_DLL_H
#define USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_NO_IMPORT) || defined(BUILDING_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_STATIC)

    #define USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_DEFAULT_DECLARE
    #define USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_HIDDEN_DECLARE
    #define USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_VISIBLE

#else  // !defined(BUILDING_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_NO_IMPORT) && !defined(BUILDING_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_STATIC)

    #if defined(BUILDING_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_EXPORT)

        #define USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_EXPORT)

        #define USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_EXPORT

    #define USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_NO_IMPORT) || defined(BUILDING_USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_STATIC)

#endif  // USING_THE_CPP_STANDARD_TEMPLATE_LIBRARIES_DLL_H
