// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 最后的霸王版本：0.0.0.1 (2019/10/12 18:22)

#ifndef RECHARGE_SERVER_MIDDLE_LAYER_EXPORT_H
#define RECHARGE_SERVER_MIDDLE_LAYER_EXPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_RECHARGE_SERVER_MIDDLE_LAYER_EXPORT
  #define BUILDING_RECHARGE_SERVER_MIDDLE_LAYER_EXPORT
#endif // BUILDING_RECHARGE_SERVER_MIDDLE_LAYER_EXPORT

#endif // RECHARGE_SERVER_MIDDLE_LAYER_EXPORT_H
