// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.0 (2020/01/05 11:48)

#ifndef DATABASE_TOOLSET_DLL_DLL_H
#define DATABASE_TOOLSET_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Database/Helper/UserMacro.h"

#if defined(BUILDING_DATABASE_TOOLSET_NO_IMPORT) || defined(BUILDING_DATABASE_STATIC)

  #define DATABASE_TOOLSET_DEFAULT_DECLARE
  #define DATABASE_TOOLSET_HIDDEN_DECLARE
  #define DATABASE_TOOLSET_VISIBLE

#else // !defined(BUILDING_DATABASE_TOOLSET_NO_IMPORT) && !defined(BUILDING_DATABASE_STATIC)

   #if defined(BUILDING_DATABASE_TOOLSET_EXPORT)
 
        #define DATABASE_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define DATABASE_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_DATABASE_TOOLSET_EXPORT)

		#define DATABASE_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define DATABASE_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_DATABASE_TOOLSET_EXPORT

   #define DATABASE_TOOLSET_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_DATABASE_TOOLSET_NO_IMPORT) || defined(BUILDING_DATABASE_STATIC)

#endif // DATABASE_TOOLSET_DLL_DLL_H
