///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.1 (2021/03/11 17:53)

#ifndef THE_CPP_STANDARD_LIBRARY_EXTENSIONS_HELPER_USER_MACRO_H
#define THE_CPP_STANDARD_LIBRARY_EXTENSIONS_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define THE_CPP_STANDARD_LIBRARY_EXTENSIONS_ClOSE_BEGIN (0x01)

#define CLOSE_USE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS (THE_CPP_STANDARD_LIBRARY_EXTENSIONS_ClOSE_BEGIN)

#define THE_CPP_STANDARD_LIBRARY_EXTENSIONS_ClOSE_END CLOSE_USE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS

#define CLOSE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS_MAX ((THE_CPP_STANDARD_LIBRARY_EXTENSIONS_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS_CLOSE 0x00

static_assert(0 <= COMPILE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS_CLOSE, "COMPILE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS_CLOSE <= CLOSE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS_MAX, "COMPILE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS_CLOSE Must be less than or equal CLOSE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS_MAX.");

#if !defined(COMPILE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS_CLOSE) || (COMPILE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS_CLOSE & CLOSE_USE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS) != CLOSE_USE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS

#endif  // !defined(COMPILE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS_CLOSE) || (COMPILE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS_CLOSE & CLOSE_USE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS) != CLOSE_USE_THE_CPP_STANDARD_LIBRARY_EXTENSIONS

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_THE_CPP_STANDARD_LIBRARY_EXTENSIONS_STATIC
#endif  // BUILDING_STATIC

#endif  // THE_CPP_STANDARD_LIBRARY_EXTENSIONS_HELPER_USER_MACRO_H
