///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.1 (2021/08/01 21:08)

#ifndef NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_DLL_H
#define NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_NO_IMPORT) || defined(BUILDING_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_STATIC)

    #define NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_DEFAULT_DECLARE
    #define NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_VISIBLE

    #if defined(BUILDING_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_EXPORT)

        #define NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_HIDDEN_DECLARE

    #else  // !defined(BUILDING_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_EXPORT)

        #define NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_EXPORT

#else  // !defined(BUILDING_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_NO_IMPORT) && !defined(BUILDING_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_STATIC)

    #if defined(BUILDING_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_EXPORT)

        #define NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_EXPORT)

        #define NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_EXPORT

    #define NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_NO_IMPORT) || defined(BUILDING_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_STATIC)

#endif  // NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_DLL_H
