///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.1 (2021/01/08 21:29)

#ifndef THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_DLL_H
#define THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_NO_IMPORT) || defined(BUILDING_THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_STATIC)

    #define THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_DEFAULT_DECLARE
    #define THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_HIDDEN_DECLARE
    #define THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_VISIBLE

#else  // !defined(BUILDING_THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_NO_IMPORT) && !defined(BUILDING_THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_STATIC)

    #if defined(BUILDING_THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_EXPORT)

        #define THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_EXPORT)

        #define THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_EXPORT

    #define THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_NO_IMPORT) || defined(BUILDING_THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_STATIC)

#endif  // THE_CPP_PROGRAMMING_LANGUAGE_SPECIAL_EDITION_EXERCISE_DLL_H
