// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.2 (2020/01/24 0:14)

#ifndef DATABASE_EXAMPLE_DLL_DLL_H
#define DATABASE_EXAMPLE_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(BUILDING_DATABASE_EXAMPLE_NO_IMPORT) || defined(BUILDING_DATABASE_EXAMPLE_STATIC)

  #define DATABASE_EXAMPLE_DEFAULT_DECLARE
  #define DATABASE_EXAMPLE_HIDDEN_DECLARE
  #define DATABASE_EXAMPLE_VISIBLE

#else // !defined(BUILDING_DATABASE_EXAMPLE_NO_IMPORT) && !defined(BUILDING_DATABASE_EXAMPLE_STATIC)

   #if defined(BUILDING_DATABASE_EXAMPLE_EXPORT)
 
        #define DATABASE_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define DATABASE_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_DATABASE_EXAMPLE_EXPORT)

		#define DATABASE_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define DATABASE_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_DATABASE_EXAMPLE_EXPORT

   #define DATABASE_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_DATABASE_EXAMPLE_NO_IMPORT) || defined(BUILDING_DATABASE_EXAMPLE_STATIC)

#endif // DATABASE_EXAMPLE_DLL_DLL_H
