///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	引擎辅助版本：0.9.0.9 (2023/05/25 11:29)

#ifndef DATABASE_EXAMPLE_DLL_DLL_H
#define DATABASE_EXAMPLE_DLL_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_DATABASE_EXAMPLE_NO_IMPORT) || defined(BUILDING_DATABASE_EXAMPLE_STATIC)

    #define DATABASE_EXAMPLE_DEFAULT_DECLARE
    #define DATABASE_EXAMPLE_HIDDEN_DECLARE

    #if defined(BUILDING_DATABASE_EXAMPLE_EXPORT)

        #define DATABASE_EXAMPLE_VISIBLE

    #else  // !defined(BUILDING_DATABASE_EXAMPLE_EXPORT)

        #define DATABASE_EXAMPLE_VISIBLE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_DATABASE_EXAMPLE_EXPORT

#else  // !defined(BUILDING_DATABASE_EXAMPLE_NO_IMPORT) && !defined(BUILDING_DATABASE_EXAMPLE_STATIC)

    #if defined(BUILDING_DATABASE_EXAMPLE_EXPORT)

        #define DATABASE_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define DATABASE_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_DATABASE_EXAMPLE_EXPORT)

        #define DATABASE_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define DATABASE_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_DATABASE_EXAMPLE_EXPORT

    #define DATABASE_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_DATABASE_EXAMPLE_NO_IMPORT) || defined(BUILDING_DATABASE_EXAMPLE_STATIC)

#endif  // DATABASE_EXAMPLE_DLL_DLL_H
