///	Copyright (c) 2010-2022
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	引擎辅助版本：0.8.0.10 (2022/07/04 18:57)

#ifndef FRAMEWORK_TOOLSET_DLL_DLL_H
#define FRAMEWORK_TOOLSET_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Framework/Helper/UserMacro.h"

#if defined(BUILDING_FRAMEWORK_TOOLSET_NO_IMPORT) || defined(BUILDING_FRAMEWORK_STATIC)

    #define FRAMEWORK_TOOLSET_DEFAULT_DECLARE
    #define FRAMEWORK_TOOLSET_HIDDEN_DECLARE
    #define FRAMEWORK_TOOLSET_VISIBLE

#else  // !defined(BUILDING_FRAMEWORK_TOOLSET_NO_IMPORT) && !defined(BUILDING_FRAMEWORK_STATIC)

    #if defined(BUILDING_FRAMEWORK_TOOLSET_EXPORT)

        #define FRAMEWORK_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define FRAMEWORK_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_FRAMEWORK_TOOLSET_EXPORT)

        #define FRAMEWORK_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define FRAMEWORK_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_FRAMEWORK_TOOLSET_EXPORT

    #define FRAMEWORK_TOOLSET_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_FRAMEWORK_TOOLSET_NO_IMPORT) || defined(BUILDING_FRAMEWORK_STATIC)

#endif  // FRAMEWORK_TOOLSET_DLL_DLL_H
