///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	引擎测试版本：0.9.0.4 (2023/03/03 17:15)

#ifndef CORE_TOOLS_TEXT_PARSING_SUITE_H
#define CORE_TOOLS_TEXT_PARSING_SUITE_H

#include "BatchConversionCSVTesting.h"
#include "CSVConfigureTesting.h"
#include "CSVContentTesting.h"
#include "CSVDataTesting.h"
#include "CSVGenerateTesting.h"
#include "CSVHeadTesting.h"
#include "CSVRowTesting.h"
#include "CSVTotalGenerateTesting.h"
#include "CSVTypeConversionTesting.h"
#include "DataTypeDescribeTesting.h"
#include "ExcelConversionCSVTesting.h"
#include "JsonConfigureTesting.h"
#include "JsonGenerateTesting.h"
#include "JsonHeadTesting.h"
#include "JsonNodeContainerTesting.h"
#include "JsonNodeTesting.h"
#include "JsonRowTesting.h"
#include "JsonTotalGenerateTesting.h"
#include "SimpleCSV/AppPropertiesTesting.h"
#include "SimpleCSV/CellIteratorTesting.h"
#include "SimpleCSV/CellRangeTesting.h"
#include "SimpleCSV/CellReferenceTesting.h"
#include "SimpleCSV/CellTesting.h"
#include "SimpleCSV/CellValueProxyTesting.h"
#include "SimpleCSV/CellValueTesting.h"
#include "SimpleCSV/ColorTesting.h"
#include "SimpleCSV/ColumnTesting.h"
#include "SimpleCSV/Command/CommandAddChartSheetTesting.h"
#include "SimpleCSV/Command/CommandAddSharedStringsTesting.h"
#include "SimpleCSV/Command/CommandAddWorksheetTesting.h"
#include "SimpleCSV/Command/CommandCloneSheetTesting.h"
#include "SimpleCSV/Command/CommandDeleteSheetTesting.h"
#include "SimpleCSV/Command/CommandResetCalcChainTesting.h"
#include "SimpleCSV/Command/CommandSetSheetColorTesting.h"
#include "SimpleCSV/Command/CommandSetSheetIndexTesting.h"
#include "SimpleCSV/Command/CommandSetSheetNameTesting.h"
#include "SimpleCSV/Command/CommandSetSheetVisibilityTesting.h"
#include "SimpleCSV/ContentItemTesting.h"
#include "SimpleCSV/ContentTypesTesting.h"
#include "SimpleCSV/DocumentTesting.h"
#include "SimpleCSV/PropertiesTesting.h"
#include "SimpleCSV/Query/QuerySharedStringsTesting.h"
#include "SimpleCSV/Query/QuerySheetIdTesting.h"
#include "SimpleCSV/Query/QuerySheetIndexTesting.h"
#include "SimpleCSV/Query/QuerySheetNameTesting.h"
#include "SimpleCSV/Query/QuerySheetRelsIdTesting.h"
#include "SimpleCSV/Query/QuerySheetRelsTargetTesting.h"
#include "SimpleCSV/Query/QuerySheetTypeTesting.h"
#include "SimpleCSV/Query/QuerySheetVisibilityTesting.h"
#include "SimpleCSV/Query/QueryXmlDataTesting.h"
#include "SimpleCSV/RelationshipItemTesting.h"
#include "SimpleCSV/RelationshipsTesting.h"
#include "SimpleCSV/RowDataIteratorTesting.h"
#include "SimpleCSV/RowDataProxyTesting.h"
#include "SimpleCSV/RowDataRangeTesting.h"
#include "SimpleCSV/RowRangeTesting.h"
#include "SimpleCSV/RowTesting.h"
#include "SimpleCSV/SharedStringsTesting.h"
#include "SimpleCSV/SheetBaseTesting.h"
#include "SimpleCSV/SimpleCSVExceptionTesting.h"
#include "SimpleCSV/WorkbookTesting.h"
#include "SimpleCSV/WorksheetTesting.h"
#include "SimpleCSV/XmlDataTesting.h"
#include "SimpleCSV/XmlFileTesting.h"
#include "SimpleZip/ZipArchiveTesting.h"
#include "SimpleZip/ZipEntryTesting.h"

#endif  // CORE_TOOLS_TEXT_PARSING_SUITE_H