/// Copyright (c) 2010-2024
/// Threading Core Render Engine
///
/// 作者：彭武阳，彭晔恩，彭晔泽
/// 联系作者：94458936@qq.com
///
/// 标准：std:c++20
/// 版本：1.0.0.8 (2024/04/17 09:37)

#ifndef CORE_TOOLS_TEXT_PARSING_SUITE_H
#define CORE_TOOLS_TEXT_PARSING_SUITE_H

#include "CSV/CSVConfigureLoadingTesting.h"
#include "CSV/CSVConfigureTesting.h"
#include "CSV/CSVContentTesting.h"
#include "CSV/CSVDataTesting.h"
#include "CSV/CSVGenerateTesting.h"
#include "CSV/CSVHeadTesting.h"
#include "CSV/CSVRowTesting.h"
#include "CSV/CSVTotalGenerateTesting.h"
#include "CSV/CSVTypeConversionTesting.h"
#include "CSV/DataTypeDescribeTesting.h"
#include "Excel/BatchConversionCSVTesting.h"
#include "Excel/BatchConversionCodeTesting.h"
#include "Excel/ExcelConversionCSVTesting.h"
#include "SimpleCSV/AppPropertiesTesting.h"
#include "SimpleCSV/CellIteratorTesting.h"
#include "SimpleCSV/CellRangeTesting.h"
#include "SimpleCSV/CellReferenceTesting.h"
#include "SimpleCSV/CellTesting.h"
#include "SimpleCSV/CellValueProxyTesting.h"
#include "SimpleCSV/CellValueTesting.h"
#include "SimpleCSV/ColorTesting.h"
#include "SimpleCSV/ColumnTesting.h"
#include "SimpleCSV/Command/CommandAddChartSheetTesting.h"
#include "SimpleCSV/Command/CommandAddSharedStringsTesting.h"
#include "SimpleCSV/Command/CommandAddWorksheetTesting.h"
#include "SimpleCSV/Command/CommandCloneSheetTesting.h"
#include "SimpleCSV/Command/CommandDeleteSheetTesting.h"
#include "SimpleCSV/Command/CommandResetCalcChainTesting.h"
#include "SimpleCSV/Command/CommandSetSheetColorTesting.h"
#include "SimpleCSV/Command/CommandSetSheetIndexTesting.h"
#include "SimpleCSV/Command/CommandSetSheetNameTesting.h"
#include "SimpleCSV/Command/CommandSetSheetVisibilityTesting.h"
#include "SimpleCSV/ContentItemTesting.h"
#include "SimpleCSV/ContentTypesTesting.h"
#include "SimpleCSV/DocumentTesting.h"
#include "SimpleCSV/PropertiesTesting.h"
#include "SimpleCSV/Query/QuerySharedStringsTesting.h"
#include "SimpleCSV/Query/QuerySheetIdTesting.h"
#include "SimpleCSV/Query/QuerySheetIndexTesting.h"
#include "SimpleCSV/Query/QuerySheetNameTesting.h"
#include "SimpleCSV/Query/QuerySheetRelsIdTesting.h"
#include "SimpleCSV/Query/QuerySheetRelsTargetTesting.h"
#include "SimpleCSV/Query/QuerySheetTypeTesting.h"
#include "SimpleCSV/Query/QuerySheetVisibilityTesting.h"
#include "SimpleCSV/Query/QueryXmlDataTesting.h"
#include "SimpleCSV/RelationshipItemTesting.h"
#include "SimpleCSV/RelationshipsTesting.h"
#include "SimpleCSV/RowDataIteratorTesting.h"
#include "SimpleCSV/RowDataProxyTesting.h"
#include "SimpleCSV/RowDataRangeTesting.h"
#include "SimpleCSV/RowRangeTesting.h"
#include "SimpleCSV/RowTesting.h"
#include "SimpleCSV/SharedStringsTesting.h"
#include "SimpleCSV/SheetBaseTesting.h"
#include "SimpleCSV/SimpleCSVExceptionTesting.h"
#include "SimpleCSV/WorkbookTesting.h"
#include "SimpleCSV/WorksheetTesting.h"
#include "SimpleCSV/XmlDataTesting.h"
#include "SimpleCSV/XmlFileTesting.h"
#include "SimpleZip/ZipArchiveTesting.h"
#include "SimpleZip/ZipEntryTesting.h"

#endif  // CORE_TOOLS_TEXT_PARSING_SUITE_H