///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.1 (2021/03/11 17:53)

#ifndef LARGE_SCALE_CPP_SOFTWARE_DESIGN_HELPER_USER_MACRO_H
#define LARGE_SCALE_CPP_SOFTWARE_DESIGN_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define LARGE_SCALE_CPP_SOFTWARE_DESIGN_ClOSE_BEGIN (0x01)

#define CLOSE_USE_LARGE_SCALE_CPP_SOFTWARE_DESIGN (LARGE_SCALE_CPP_SOFTWARE_DESIGN_ClOSE_BEGIN)

#define LARGE_SCALE_CPP_SOFTWARE_DESIGN_ClOSE_END CLOSE_USE_LARGE_SCALE_CPP_SOFTWARE_DESIGN

#define CLOSE_LARGE_SCALE_CPP_SOFTWARE_DESIGN_MAX ((LARGE_SCALE_CPP_SOFTWARE_DESIGN_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_LARGE_SCALE_CPP_SOFTWARE_DESIGN_CLOSE 0x00

static_assert(0 <= COMPILE_LARGE_SCALE_CPP_SOFTWARE_DESIGN_CLOSE, "COMPILE_LARGE_SCALE_CPP_SOFTWARE_DESIGN_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_LARGE_SCALE_CPP_SOFTWARE_DESIGN_CLOSE <= CLOSE_LARGE_SCALE_CPP_SOFTWARE_DESIGN_MAX, "COMPILE_LARGE_SCALE_CPP_SOFTWARE_DESIGN_CLOSE Must be less than or equal CLOSE_LARGE_SCALE_CPP_SOFTWARE_DESIGN_MAX.");

#if !defined(COMPILE_LARGE_SCALE_CPP_SOFTWARE_DESIGN_CLOSE) || (COMPILE_LARGE_SCALE_CPP_SOFTWARE_DESIGN_CLOSE & CLOSE_USE_LARGE_SCALE_CPP_SOFTWARE_DESIGN) != CLOSE_USE_LARGE_SCALE_CPP_SOFTWARE_DESIGN

#endif  // !defined(COMPILE_LARGE_SCALE_CPP_SOFTWARE_DESIGN_CLOSE) || (COMPILE_LARGE_SCALE_CPP_SOFTWARE_DESIGN_CLOSE & CLOSE_USE_LARGE_SCALE_CPP_SOFTWARE_DESIGN) != CLOSE_USE_LARGE_SCALE_CPP_SOFTWARE_DESIGN

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_LARGE_SCALE_CPP_SOFTWARE_DESIGN_STATIC
#endif  // BUILDING_STATIC

#endif  // LARGE_SCALE_CPP_SOFTWARE_DESIGN_HELPER_USER_MACRO_H
