///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.1 (2021/03/11 17:52)

#ifndef ADVANCED_QT_PROGRAMMING_DLL_H
#define ADVANCED_QT_PROGRAMMING_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_ADVANCED_QT_PROGRAMMING_NO_IMPORT) || defined(BUILDING_ADVANCED_QT_PROGRAMMING_STATIC)

    #define ADVANCED_QT_PROGRAMMING_DEFAULT_DECLARE
    #define ADVANCED_QT_PROGRAMMING_VISIBLE

    #if defined(BUILDING_ADVANCED_QT_PROGRAMMING_EXPORT)

        #define ADVANCED_QT_PROGRAMMING_HIDDEN_DECLARE

    #else  // !defined(BUILDING_ADVANCED_QT_PROGRAMMING_EXPORT)

        #define ADVANCED_QT_PROGRAMMING_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_ADVANCED_QT_PROGRAMMING_EXPORT

#else  // !defined(BUILDING_ADVANCED_QT_PROGRAMMING_NO_IMPORT) && !defined(BUILDING_ADVANCED_QT_PROGRAMMING_STATIC)

    #if defined(BUILDING_ADVANCED_QT_PROGRAMMING_EXPORT)

        #define ADVANCED_QT_PROGRAMMING_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define ADVANCED_QT_PROGRAMMING_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_ADVANCED_QT_PROGRAMMING_EXPORT)

        #define ADVANCED_QT_PROGRAMMING_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define ADVANCED_QT_PROGRAMMING_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_ADVANCED_QT_PROGRAMMING_EXPORT

    #define ADVANCED_QT_PROGRAMMING_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_ADVANCED_QT_PROGRAMMING_NO_IMPORT) || defined(BUILDING_ADVANCED_QT_PROGRAMMING_STATIC)

#endif  // ADVANCED_QT_PROGRAMMING_DLL_H
