// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê”Œœ∑∞Ê±æ£∫0.0.0.1 (2019/10/04 23:43)

#ifndef ITEM_MANAGER_DLL_H
#define ITEM_MANAGER_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Helper/UserMacro.h"

#if defined(BUILDING_ITEM_MANAGER_NO_IMPORT) || defined(BUILDING_ITEM_MANAGER_STATIC)

  #define ITEM_MANAGER_DEFAULT_DECLARE
  #define ITEM_MANAGER_HIDDEN_DECLARE 
  #define ITEM_MANAGER_VISIBLE

#else // !defined(BUILDING_ITEM_MANAGER_NO_IMPORT) && !defined(BUILDING_ITEM_MANAGER_STATIC)
 
   #if defined(BUILDING_ITEM_MANAGER_EXPORT)
 
        #define ITEM_MANAGER_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define ITEM_MANAGER_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_ITEM_MANAGER_EXPORT)

		#define ITEM_MANAGER_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define ITEM_MANAGER_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_ITEM_MANAGER_EXPORT

   #define ITEM_MANAGER_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_ITEM_MANAGER_NO_IMPORT) || defined(BUILDING_ITEM_MANAGER_STATIC)
 
#endif // ITEM_MANAGER_DLL_H
