///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.2 (2021/03/28 12:58)

#ifndef APPLIED_CRYPTOGRAPHY_HELPER_USER_MACRO_H
#define APPLIED_CRYPTOGRAPHY_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define APPLIED_CRYPTOGRAPHY_ClOSE_BEGIN (0x01)

#define CLOSE_USE_APPLIED_CRYPTOGRAPHY (APPLIED_CRYPTOGRAPHY_ClOSE_BEGIN)

#define APPLIED_CRYPTOGRAPHY_ClOSE_END CLOSE_USE_APPLIED_CRYPTOGRAPHY

#define CLOSE_APPLIED_CRYPTOGRAPHY_MAX ((APPLIED_CRYPTOGRAPHY_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_APPLIED_CRYPTOGRAPHY_CLOSE 0x00

static_assert(0 <= COMPILE_APPLIED_CRYPTOGRAPHY_CLOSE, "COMPILE_APPLIED_CRYPTOGRAPHY_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_APPLIED_CRYPTOGRAPHY_CLOSE <= CLOSE_APPLIED_CRYPTOGRAPHY_MAX, "COMPILE_APPLIED_CRYPTOGRAPHY_CLOSE Must be less than or equal CLOSE_APPLIED_CRYPTOGRAPHY_MAX.");

#if !defined(COMPILE_APPLIED_CRYPTOGRAPHY_CLOSE) || (COMPILE_APPLIED_CRYPTOGRAPHY_CLOSE & CLOSE_USE_APPLIED_CRYPTOGRAPHY) != CLOSE_USE_APPLIED_CRYPTOGRAPHY

#endif  // !defined(COMPILE_APPLIED_CRYPTOGRAPHY_CLOSE) || (COMPILE_APPLIED_CRYPTOGRAPHY_CLOSE & CLOSE_USE_APPLIED_CRYPTOGRAPHY) != CLOSE_USE_APPLIED_CRYPTOGRAPHY

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_APPLIED_CRYPTOGRAPHY_STATIC
#endif  // BUILDING_STATIC

#endif  // APPLIED_CRYPTOGRAPHY_HELPER_USER_MACRO_H
