///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.1 (2021/02/16 17:45)

#ifndef EFFECTIVE_STL_DLL_H
#define EFFECTIVE_STL_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_EFFECTIVE_STL_NO_IMPORT) || defined(BUILDING_EFFECTIVE_STL_STATIC)

    #define EFFECTIVE_STL_DEFAULT_DECLARE
    #define EFFECTIVE_STL_HIDDEN_DECLARE
    #define EFFECTIVE_STL_VISIBLE

#else  // !defined(BUILDING_EFFECTIVE_STL_NO_IMPORT) && !defined(BUILDING_EFFECTIVE_STL_STATIC)

    #if defined(BUILDING_EFFECTIVE_STL_EXPORT)

        #define EFFECTIVE_STL_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define EFFECTIVE_STL_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_EFFECTIVE_STL_EXPORT)

        #define EFFECTIVE_STL_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define EFFECTIVE_STL_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_EFFECTIVE_STL_EXPORT

    #define EFFECTIVE_STL_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_EFFECTIVE_STL_NO_IMPORT) || defined(BUILDING_EFFECTIVE_STL_STATIC)

#endif  // EFFECTIVE_STL_DLL_H
