@echo on
 
call RunAllGameClientTesting.bat
call RunAllRobotClientTesting.bat
call RunAllMessageClientTesting.bat
call RunAllBackgroundClientTesting.bat
call RunAllGatewayServerTesting.bat
call RunAllLoginServerTesting.bat
call RunAllPlayerServerTesting.bat
call RunAllGameServerTesting.bat
call RunAllFightingServerTesting.bat
call RunAllWorldServerTesting.bat
call RunAllCrossServerTesting.bat
call RunAllOfflineServerTesting.bat
call RunAllLeaderboardServerTesting.bat
call RunAllMailServerTesting.bat
call RunAllChatServerTesting.bat
call RunAllRechargeServerTesting.bat
call RunAllLogServerTesting.bat
call RunAllGameMasterServerTesting.bat
call RunAllUpdateServerTesting.bat
call RunAllBackgroundServerTesting.bat
call RunAllDatabaseServerTesting.bat
call RunAllServerManagerTesting.bat

call RunTheLastOverlordTesting.bat

pause