@echo on
 
start /d %TheLastOverlordTestingWin32DebugLib% BackgroundServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingWin32ReleaseLib% BackgroundServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingX64DebugLib% BackgroundServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingX64ReleaseLib% BackgroundServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingStaticWin32DebugLib% BackgroundServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticWin32ReleaseLib% BackgroundServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingStaticX64DebugLib% BackgroundServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticX64ReleaseLib% BackgroundServerMiddleLayerTestingStatic.exe

start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32DebugLib% BackgroundServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32ReleaseLib% BackgroundServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64DebugLib% BackgroundServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64ReleaseLib% BackgroundServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32DebugLib% BackgroundServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32ReleaseLib% BackgroundServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64DebugLib% BackgroundServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64ReleaseLib% BackgroundServerMiddleLayerTesting.exe

pause