@echo on
 
start /d %TheLastOverlordTestingWin32DebugLib% BackgroundClientMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingWin32ReleaseLib% BackgroundClientMiddleLayerTesting.exe
start /d %TheLastOverlordTestingX64DebugLib% BackgroundClientMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingX64ReleaseLib% BackgroundClientMiddleLayerTesting.exe
start /d %TheLastOverlordTestingStaticWin32DebugLib% BackgroundClientMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticWin32ReleaseLib% BackgroundClientMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingStaticX64DebugLib% BackgroundClientMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticX64ReleaseLib% BackgroundClientMiddleLayerTestingStatic.exe

start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32DebugLib% BackgroundClientMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32ReleaseLib% BackgroundClientMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64DebugLib% BackgroundClientMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64ReleaseLib% BackgroundClientMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32DebugLib% BackgroundClientMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32ReleaseLib% BackgroundClientMiddleLayerTesting.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64DebugLib% BackgroundClientMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64ReleaseLib% BackgroundClientMiddleLayerTesting.exe

pause