@echo on
 
start /d %TheLastOverlordTestingWin32DebugLib% ChatServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingWin32ReleaseLib% ChatServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingX64DebugLib% ChatServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingX64ReleaseLib% ChatServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingStaticWin32DebugLib% ChatServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticWin32ReleaseLib% ChatServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingStaticX64DebugLib% ChatServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticX64ReleaseLib% ChatServerMiddleLayerTestingStatic.exe

start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32DebugLib% ChatServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32ReleaseLib% ChatServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64DebugLib% ChatServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64ReleaseLib% ChatServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32DebugLib% ChatServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32ReleaseLib% ChatServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64DebugLib% ChatServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64ReleaseLib% ChatServerMiddleLayerTesting.exe

pause