@echo on
 
start /d %TheLastOverlordTestingWin32DebugLib% CrossServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingWin32ReleaseLib% CrossServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingX64DebugLib% CrossServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingX64ReleaseLib% CrossServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingStaticWin32DebugLib% CrossServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticWin32ReleaseLib% CrossServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingStaticX64DebugLib% CrossServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticX64ReleaseLib% CrossServerMiddleLayerTestingStatic.exe

start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32DebugLib% CrossServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32ReleaseLib% CrossServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64DebugLib% CrossServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64ReleaseLib% CrossServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32DebugLib% CrossServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32ReleaseLib% CrossServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64DebugLib% CrossServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64ReleaseLib% CrossServerMiddleLayerTesting.exe

pause