@echo on
 
start /d %TheLastOverlordTestingWin32DebugLib% GameServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingWin32ReleaseLib% GameServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingX64DebugLib% GameServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingX64ReleaseLib% GameServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingStaticWin32DebugLib% GameServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticWin32ReleaseLib% GameServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingStaticX64DebugLib% GameServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticX64ReleaseLib% GameServerMiddleLayerTestingStatic.exe

start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32DebugLib% GameServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32ReleaseLib% GameServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64DebugLib% GameServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64ReleaseLib% GameServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32DebugLib% GameServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32ReleaseLib% GameServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64DebugLib% GameServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64ReleaseLib% GameServerMiddleLayerTesting.exe

pause