@echo on
 
start /d %TheLastOverlordTestingWin32DebugLib% GameServerTestingD.exe
start /d %TheLastOverlordTestingWin32ReleaseLib% GameServerTesting.exe
start /d %TheLastOverlordTestingX64DebugLib% GameServerTestingD.exe
start /d %TheLastOverlordTestingX64ReleaseLib% GameServerTesting.exe
start /d %TheLastOverlordTestingStaticWin32DebugLib% GameServerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticWin32ReleaseLib% GameServerTestingStatic.exe
start /d %TheLastOverlordTestingStaticX64DebugLib% GameServerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticX64ReleaseLib% GameServerTestingStatic.exe

start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32DebugLib% GameServerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32ReleaseLib% GameServerTestingStatic.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64DebugLib% GameServerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64ReleaseLib% GameServerTestingStatic.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32DebugLib% GameServerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32ReleaseLib% GameServerTesting.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64DebugLib% GameServerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64ReleaseLib% GameServerTesting.exe

pause