@echo on
 
start /d %TheLastOverlordTestingWin32DebugLib% GatewayServerCoreTestingD.exe
start /d %TheLastOverlordTestingWin32ReleaseLib% GatewayServerCoreTesting.exe
start /d %TheLastOverlordTestingX64DebugLib% GatewayServerCoreTestingD.exe
start /d %TheLastOverlordTestingX64ReleaseLib% GatewayServerCoreTesting.exe
start /d %TheLastOverlordTestingStaticWin32DebugLib% GatewayServerCoreTestingStaticD.exe
start /d %TheLastOverlordTestingStaticWin32ReleaseLib% GatewayServerCoreTestingStatic.exe
start /d %TheLastOverlordTestingStaticX64DebugLib% GatewayServerCoreTestingStaticD.exe
start /d %TheLastOverlordTestingStaticX64ReleaseLib% GatewayServerCoreTestingStatic.exe

start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32DebugLib% GatewayServerCoreTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32ReleaseLib% GatewayServerCoreTestingStatic.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64DebugLib% GatewayServerCoreTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64ReleaseLib% GatewayServerCoreTestingStatic.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32DebugLib% GatewayServerCoreTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32ReleaseLib% GatewayServerCoreTesting.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64DebugLib% GatewayServerCoreTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64ReleaseLib% GatewayServerCoreTesting.exe

pause