@echo on
 
start /d %TheLastOverlordTestingWin32DebugLib% GatewayServerTestingD.exe
start /d %TheLastOverlordTestingWin32ReleaseLib% GatewayServerTesting.exe
start /d %TheLastOverlordTestingX64DebugLib% GatewayServerTestingD.exe
start /d %TheLastOverlordTestingX64ReleaseLib% GatewayServerTesting.exe
start /d %TheLastOverlordTestingStaticWin32DebugLib% GatewayServerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticWin32ReleaseLib% GatewayServerTestingStatic.exe
start /d %TheLastOverlordTestingStaticX64DebugLib% GatewayServerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticX64ReleaseLib% GatewayServerTestingStatic.exe

start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32DebugLib% GatewayServerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32ReleaseLib% GatewayServerTestingStatic.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64DebugLib% GatewayServerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64ReleaseLib% GatewayServerTestingStatic.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32DebugLib% GatewayServerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32ReleaseLib% GatewayServerTesting.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64DebugLib% GatewayServerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64ReleaseLib% GatewayServerTesting.exe

pause