@echo on
 
start /d %TheLastOverlordTestingWin32DebugLib% GameMasterServerCoreTestingD.exe
start /d %TheLastOverlordTestingWin32ReleaseLib% GameMasterServerCoreTesting.exe
start /d %TheLastOverlordTestingX64DebugLib% GameMasterServerCoreTestingD.exe
start /d %TheLastOverlordTestingX64ReleaseLib% GameMasterServerCoreTesting.exe
start /d %TheLastOverlordTestingStaticWin32DebugLib% GameMasterServerCoreTestingStaticD.exe
start /d %TheLastOverlordTestingStaticWin32ReleaseLib% GameMasterServerCoreTestingStatic.exe
start /d %TheLastOverlordTestingStaticX64DebugLib% GameMasterServerCoreTestingStaticD.exe
start /d %TheLastOverlordTestingStaticX64ReleaseLib% GameMasterServerCoreTestingStatic.exe

start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32DebugLib% GameMasterServerCoreTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32ReleaseLib% GameMasterServerCoreTestingStatic.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64DebugLib% GameMasterServerCoreTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64ReleaseLib% GameMasterServerCoreTestingStatic.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32DebugLib% GameMasterServerCoreTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32ReleaseLib% GameMasterServerCoreTesting.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64DebugLib% GameMasterServerCoreTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64ReleaseLib% GameMasterServerCoreTesting.exe

pause