@echo on
 
start /d %TheLastOverlordTestingWin32DebugLib% GameMasterServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingWin32ReleaseLib% GameMasterServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingX64DebugLib% GameMasterServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingX64ReleaseLib% GameMasterServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingStaticWin32DebugLib% GameMasterServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticWin32ReleaseLib% GameMasterServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingStaticX64DebugLib% GameMasterServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticX64ReleaseLib% GameMasterServerMiddleLayerTestingStatic.exe

start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32DebugLib% GameMasterServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32ReleaseLib% GameMasterServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64DebugLib% GameMasterServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64ReleaseLib% GameMasterServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32DebugLib% GameMasterServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32ReleaseLib% GameMasterServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64DebugLib% GameMasterServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64ReleaseLib% GameMasterServerMiddleLayerTesting.exe

pause