@echo on
 
start /d %TheLastOverlordTestingWin32DebugLib% LeaderboardServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingWin32ReleaseLib% LeaderboardServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingX64DebugLib% LeaderboardServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingX64ReleaseLib% LeaderboardServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingStaticWin32DebugLib% LeaderboardServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticWin32ReleaseLib% LeaderboardServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingStaticX64DebugLib% LeaderboardServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticX64ReleaseLib% LeaderboardServerMiddleLayerTestingStatic.exe

start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32DebugLib% LeaderboardServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32ReleaseLib% LeaderboardServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64DebugLib% LeaderboardServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64ReleaseLib% LeaderboardServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32DebugLib% LeaderboardServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32ReleaseLib% LeaderboardServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64DebugLib% LeaderboardServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64ReleaseLib% LeaderboardServerMiddleLayerTesting.exe

pause