@echo on
 
start /d %TheLastOverlordTestingWin32DebugLib% MailServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingWin32ReleaseLib% MailServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingX64DebugLib% MailServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingX64ReleaseLib% MailServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingStaticWin32DebugLib% MailServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticWin32ReleaseLib% MailServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingStaticX64DebugLib% MailServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticX64ReleaseLib% MailServerMiddleLayerTestingStatic.exe

start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32DebugLib% MailServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32ReleaseLib% MailServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64DebugLib% MailServerMiddleLayerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64ReleaseLib% MailServerMiddleLayerTestingStatic.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32DebugLib% MailServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32ReleaseLib% MailServerMiddleLayerTesting.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64DebugLib% MailServerMiddleLayerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64ReleaseLib% MailServerMiddleLayerTesting.exe

pause