@echo on
 
start /d %TheLastOverlordTestingWin32DebugLib% RechargeServerTestingD.exe
start /d %TheLastOverlordTestingWin32ReleaseLib% RechargeServerTesting.exe
start /d %TheLastOverlordTestingX64DebugLib% RechargeServerTestingD.exe
start /d %TheLastOverlordTestingX64ReleaseLib% RechargeServerTesting.exe
start /d %TheLastOverlordTestingStaticWin32DebugLib% RechargeServerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticWin32ReleaseLib% RechargeServerTestingStatic.exe
start /d %TheLastOverlordTestingStaticX64DebugLib% RechargeServerTestingStaticD.exe
start /d %TheLastOverlordTestingStaticX64ReleaseLib% RechargeServerTestingStatic.exe

start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32DebugLib% RechargeServerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicWin32ReleaseLib% RechargeServerTestingStatic.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64DebugLib% RechargeServerTestingStaticD.exe
start /d %TheLastOverlordTestingEngineStaticGameDynamicX64ReleaseLib% RechargeServerTestingStatic.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32DebugLib% RechargeServerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticWin32ReleaseLib% RechargeServerTesting.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64DebugLib% RechargeServerTestingD.exe
start /d %TheLastOverlordTestingEngineDynamicGameStaticX64ReleaseLib% RechargeServerTesting.exe

pause