///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.6 (2021/11/21 20:58)

#ifndef BEGINNING_LINUX_PROGRAMMING_HELPER_USER_MACRO_H
#define BEGINNING_LINUX_PROGRAMMING_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define BEGINNING_LINUX_PROGRAMMING_ClOSE_BEGIN (0x01)

#define CLOSE_USE_BEGINNING_LINUX_PROGRAMMING (BEGINNING_LINUX_PROGRAMMING_ClOSE_BEGIN)

#define BEGINNING_LINUX_PROGRAMMING_ClOSE_END CLOSE_USE_BEGINNING_LINUX_PROGRAMMING

#define CLOSE_BEGINNING_LINUX_PROGRAMMING_MAX ((BEGINNING_LINUX_PROGRAMMING_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_BEGINNING_LINUX_PROGRAMMING_CLOSE 0x00

static_assert(0 <= COMPILE_BEGINNING_LINUX_PROGRAMMING_CLOSE, "COMPILE_BEGINNING_LINUX_PROGRAMMING_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_BEGINNING_LINUX_PROGRAMMING_CLOSE <= CLOSE_BEGINNING_LINUX_PROGRAMMING_MAX, "COMPILE_BEGINNING_LINUX_PROGRAMMING_CLOSE Must be less than or equal CLOSE_BEGINNING_LINUX_PROGRAMMING_MAX.");

#if !defined(COMPILE_BEGINNING_LINUX_PROGRAMMING_CLOSE) || (COMPILE_BEGINNING_LINUX_PROGRAMMING_CLOSE & CLOSE_USE_BEGINNING_LINUX_PROGRAMMING) != CLOSE_USE_BEGINNING_LINUX_PROGRAMMING

#endif  // !defined(COMPILE_BEGINNING_LINUX_PROGRAMMING_CLOSE) || (COMPILE_BEGINNING_LINUX_PROGRAMMING_CLOSE & CLOSE_USE_BEGINNING_LINUX_PROGRAMMING) != CLOSE_USE_BEGINNING_LINUX_PROGRAMMING

#ifdef BUILDING_STATIC
    #define BUILDING_BEGINNING_LINUX_PROGRAMMING_STATIC
#endif  // BUILDING_STATIC

#endif  // BEGINNING_LINUX_PROGRAMMING_HELPER_USER_MACRO_H
