///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.2 (2021/03/28 12:58)

#ifndef ALGORITHMIC_PUZZLES_HELPER_USER_MACRO_H
#define ALGORITHMIC_PUZZLES_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define ALGORITHMIC_PUZZLES_ClOSE_BEGIN (0x01)

#define CLOSE_USE_ALGORITHMIC_PUZZLES (ALGORITHMIC_PUZZLES_ClOSE_BEGIN)

#define ALGORITHMIC_PUZZLES_ClOSE_END CLOSE_USE_ALGORITHMIC_PUZZLES

#define CLOSE_ALGORITHMIC_PUZZLES_MAX ((ALGORITHMIC_PUZZLES_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_ALGORITHMIC_PUZZLES_CLOSE 0x00

static_assert(0 <= COMPILE_ALGORITHMIC_PUZZLES_CLOSE, "COMPILE_ALGORITHMIC_PUZZLES_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_ALGORITHMIC_PUZZLES_CLOSE <= CLOSE_ALGORITHMIC_PUZZLES_MAX, "COMPILE_ALGORITHMIC_PUZZLES_CLOSE Must be less than or equal CLOSE_ALGORITHMIC_PUZZLES_MAX.");

#if !defined(COMPILE_ALGORITHMIC_PUZZLES_CLOSE) || (COMPILE_ALGORITHMIC_PUZZLES_CLOSE & CLOSE_USE_ALGORITHMIC_PUZZLES) != CLOSE_USE_ALGORITHMIC_PUZZLES

#endif  // !defined(COMPILE_ALGORITHMIC_PUZZLES_CLOSE) || (COMPILE_ALGORITHMIC_PUZZLES_CLOSE & CLOSE_USE_ALGORITHMIC_PUZZLES) != CLOSE_USE_ALGORITHMIC_PUZZLES

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_ALGORITHMIC_PUZZLES_STATIC
#endif  // BUILDING_STATIC

#endif  // ALGORITHMIC_PUZZLES_HELPER_USER_MACRO_H
