///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.1 (2021/03/11 17:53)

#ifndef DESIGNING_AND_CODING_REUSABLE_CPP_HELPER_USER_MACRO_H
#define DESIGNING_AND_CODING_REUSABLE_CPP_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define DESIGNING_AND_CODING_REUSABLE_CPP_ClOSE_BEGIN (0x01)

#define CLOSE_USE_DESIGNING_AND_CODING_REUSABLE_CPP (DESIGNING_AND_CODING_REUSABLE_CPP_ClOSE_BEGIN)

#define DESIGNING_AND_CODING_REUSABLE_CPP_ClOSE_END CLOSE_USE_DESIGNING_AND_CODING_REUSABLE_CPP

#define CLOSE_DESIGNING_AND_CODING_REUSABLE_CPP_MAX ((DESIGNING_AND_CODING_REUSABLE_CPP_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_DESIGNING_AND_CODING_REUSABLE_CPP_CLOSE 0x00

static_assert(0 <= COMPILE_DESIGNING_AND_CODING_REUSABLE_CPP_CLOSE, "COMPILE_DESIGNING_AND_CODING_REUSABLE_CPP_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_DESIGNING_AND_CODING_REUSABLE_CPP_CLOSE <= CLOSE_DESIGNING_AND_CODING_REUSABLE_CPP_MAX, "COMPILE_DESIGNING_AND_CODING_REUSABLE_CPP_CLOSE Must be less than or equal CLOSE_DESIGNING_AND_CODING_REUSABLE_CPP_MAX.");

#if !defined(COMPILE_DESIGNING_AND_CODING_REUSABLE_CPP_CLOSE) || (COMPILE_DESIGNING_AND_CODING_REUSABLE_CPP_CLOSE & CLOSE_USE_DESIGNING_AND_CODING_REUSABLE_CPP) != CLOSE_USE_DESIGNING_AND_CODING_REUSABLE_CPP

#endif  // !defined(COMPILE_DESIGNING_AND_CODING_REUSABLE_CPP_CLOSE) || (COMPILE_DESIGNING_AND_CODING_REUSABLE_CPP_CLOSE & CLOSE_USE_DESIGNING_AND_CODING_REUSABLE_CPP) != CLOSE_USE_DESIGNING_AND_CODING_REUSABLE_CPP

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_DESIGNING_AND_CODING_REUSABLE_CPP_STATIC
#endif  // BUILDING_STATIC

#endif  // DESIGNING_AND_CODING_REUSABLE_CPP_HELPER_USER_MACRO_H
