// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
// 
// “˝«Ê∞Ê±æ£∫0.0.0.2 (2019/07/03 14:57)

#ifndef MATHEMATICS_DLL_H
#define MATHEMATICS_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Mathematics/Macro/UserMacro.h"

#if defined(BUILDING_MATHEMATICS_NO_IMPORT) || defined(BUILDING_MATHEMATICS_STATIC)

  #define MATHEMATICS_DEFAULT_DECLARE
  #define MATHEMATICS_HIDDEN_DECLARE
  #define MATHEMATICS_VISIBLE

#else // !defined(BUILDING_MATHEMATICS_NO_IMPORT) && !defined(BUILDING_MATHEMATICS_STATIC)
 
   #if defined(BUILDING_MATHEMATICS_EXPORT)
 
        #define MATHEMATICS_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define MATHEMATICS_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_MATHEMATICS_EXPORT)

		#define MATHEMATICS_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define MATHEMATICS_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_MATHEMATICS_EXPORT

   #define MATHEMATICS_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_MATHEMATICS_NO_IMPORT) || defined(BUILDING_MATHEMATICS_STATIC)

#endif // MATHEMATICS_DLL_H