// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
//
// 最后的霸王版本：0.0.0.1 (2019/10/13 16:54)

#ifndef SERVER_MANAGER_MIDDLE_LAYER_DLL_H
#define SERVER_MANAGER_MIDDLE_LAYER_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(BUILDING_SERVER_MANAGER_MIDDLE_LAYER_NO_IMPORT)  || defined(BUILDING_SERVER_MANAGER_MIDDLE_LAYER_STATIC)

  #define SERVER_MANAGER_MIDDLE_LAYER_DEFAULT_DECLARE
  #define SERVER_MANAGER_MIDDLE_LAYER_HIDDEN_DECLARE 
  #define SERVER_MANAGER_MIDDLE_LAYER_VISIBLE

#else // !defined(BUILDING_SERVER_MANAGER_MIDDLE_LAYER_NO_IMPORT) && !defined(BUILDING_SERVER_MANAGER_MIDDLE_LAYER_STATIC)
 
   #if defined(BUILDING_SERVER_MANAGER_MIDDLE_LAYER_EXPORT)
 
        #define SERVER_MANAGER_MIDDLE_LAYER_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define SERVER_MANAGER_MIDDLE_LAYER_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_SERVER_MANAGER_MIDDLE_LAYER_EXPORT)

		#define SERVER_MANAGER_MIDDLE_LAYER_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define SERVER_MANAGER_MIDDLE_LAYER_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_SERVER_MANAGER_MIDDLE_LAYER_EXPORT

   #define SERVER_MANAGER_MIDDLE_LAYER_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_SERVER_MANAGER_MIDDLE_LAYER_NO_IMPORT) || defined(BUILDING_SERVER_MANAGER_MIDDLE_LAYER_STATIC)
 
#endif // SERVER_MANAGER_MIDDLE_LAYER_DLL_H
