// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
//
// 最后的霸王版本：0.0.0.1 (2019/10/13 16:54)

#ifndef SERVER_MANAGER_MIDDLE_LAYER_IMPORT_H
#define SERVER_MANAGER_MIDDLE_LAYER_IMPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_SERVER_MANAGER_MIDDLE_LAYER_IMPORT
  #define BUILDING_SERVER_MANAGER_MIDDLE_LAYER_IMPORT
#endif // BUILDING_SERVER_MANAGER_MIDDLE_LAYER_IMPORT

#endif // SERVER_MANAGER_MIDDLE_LAYER_IMPORT_H
