///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.1 (2021/02/28 19:37)

#ifndef EXTENDED_STL_HELPER_USER_MACRO_H
#define EXTENDED_STL_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define EXTENDED_STL_ClOSE_BEGIN (0x01)

#define CLOSE_USE_EXTENDED_STL (EXTENDED_STL_ClOSE_BEGIN)

#define EXTENDED_STL_ClOSE_END CLOSE_USE_EXTENDED_STL

#define CLOSE_EXTENDED_STL_MAX ((EXTENDED_STL_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_EXTENDED_STL_CLOSE 0x00

static_assert(0 <= COMPILE_EXTENDED_STL_CLOSE, "COMPILE_EXTENDED_STL_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_EXTENDED_STL_CLOSE <= CLOSE_EXTENDED_STL_MAX, "COMPILE_EXTENDED_STL_CLOSE Must be less than or equal CLOSE_EXTENDED_STL_MAX.");

#if !defined(COMPILE_EXTENDED_STL_CLOSE) || (COMPILE_EXTENDED_STL_CLOSE & CLOSE_USE_EXTENDED_STL) != CLOSE_USE_EXTENDED_STL

#endif  // !defined(COMPILE_EXTENDED_STL_CLOSE) || (COMPILE_EXTENDED_STL_CLOSE & CLOSE_USE_EXTENDED_STL) != CLOSE_USE_EXTENDED_STL

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_EXTENDED_STL_STATIC
#endif  // BUILDING_STATIC

#endif  // EXTENDED_STL_HELPER_USER_MACRO_H
