///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.1 (2021/01/08 21:29)

#ifndef CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_DLL_H
#define CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_NO_IMPORT) || defined(BUILDING_CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_STATIC)

    #define CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_DEFAULT_DECLARE
    #define CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_HIDDEN_DECLARE
    #define CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_VISIBLE

#else  // !defined(BUILDING_CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_NO_IMPORT) && !defined(BUILDING_CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_STATIC)

    #if defined(BUILDING_CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_EXPORT)

        #define CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_EXPORT)

        #define CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_EXPORT

    #define CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_NO_IMPORT) || defined(BUILDING_CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_STATIC)

#endif  // CPP_IN_ACTION_INDUSTRIAL_STRENGTH_PROGRAMMING_TECHNIQUES_DLL_H
