///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.4 (2021/06/06 21:47)

#ifndef THE_ACE_PROGRAMMERS_GUIDE_HELPER_USER_MACRO_H
#define THE_ACE_PROGRAMMERS_GUIDE_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define THE_ACE_PROGRAMMERS_GUIDE_ClOSE_BEGIN (0x01)

#define CLOSE_USE_THE_ACE_PROGRAMMERS_GUIDE (THE_ACE_PROGRAMMERS_GUIDE_ClOSE_BEGIN)

#define THE_ACE_PROGRAMMERS_GUIDE_ClOSE_END CLOSE_USE_THE_ACE_PROGRAMMERS_GUIDE

#define CLOSE_THE_ACE_PROGRAMMERS_GUIDE_MAX ((THE_ACE_PROGRAMMERS_GUIDE_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_THE_ACE_PROGRAMMERS_GUIDE_CLOSE 0x00

static_assert(0 <= COMPILE_THE_ACE_PROGRAMMERS_GUIDE_CLOSE, "COMPILE_THE_ACE_PROGRAMMERS_GUIDE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_THE_ACE_PROGRAMMERS_GUIDE_CLOSE <= CLOSE_THE_ACE_PROGRAMMERS_GUIDE_MAX, "COMPILE_THE_ACE_PROGRAMMERS_GUIDE_CLOSE Must be less than or equal CLOSE_THE_ACE_PROGRAMMERS_GUIDE_MAX.");

#if !defined(COMPILE_THE_ACE_PROGRAMMERS_GUIDE_CLOSE) || (COMPILE_THE_ACE_PROGRAMMERS_GUIDE_CLOSE & CLOSE_USE_THE_ACE_PROGRAMMERS_GUIDE) != CLOSE_USE_THE_ACE_PROGRAMMERS_GUIDE

#endif  // !defined(COMPILE_THE_ACE_PROGRAMMERS_GUIDE_CLOSE) || (COMPILE_THE_ACE_PROGRAMMERS_GUIDE_CLOSE & CLOSE_USE_THE_ACE_PROGRAMMERS_GUIDE) != CLOSE_USE_THE_ACE_PROGRAMMERS_GUIDE

#ifdef BUILDING_STATIC
    #define BUILDING_THE_ACE_PROGRAMMERS_GUIDE_STATIC
#endif  // BUILDING_STATIC

#endif  // THE_ACE_PROGRAMMERS_GUIDE_HELPER_USER_MACRO_H
