///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.1 (2021/03/11 17:53)

#ifndef CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_HELPER_USER_MACRO_H
#define CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_ClOSE_BEGIN (0x01)

#define CLOSE_USE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT (CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_ClOSE_BEGIN)

#define CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_ClOSE_END CLOSE_USE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT

#define CLOSE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_MAX ((CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_CLOSE 0x00

static_assert(0 <= COMPILE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_CLOSE, "COMPILE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_CLOSE <= CLOSE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_MAX, "COMPILE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_CLOSE Must be less than or equal CLOSE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_MAX.");

#if !defined(COMPILE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_CLOSE) || (COMPILE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_CLOSE & CLOSE_USE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT) != CLOSE_USE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT

#endif  // !defined(COMPILE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_CLOSE) || (COMPILE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_CLOSE & CLOSE_USE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT) != CLOSE_USE_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_STATIC
#endif  // BUILDING_STATIC

#endif  // CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_HELPER_USER_MACRO_H
