/// Copyright (c) 2010-2024
/// Threading Core Render Engine
///
/// 作者：彭武阳，彭晔恩，彭晔泽
/// 联系作者：94458936@qq.com
///
/// 标准：std:c++20
/// 版本：1.0.0.8 (2024/04/12 15:44)

#ifndef CORE_TOOLS_EXAMPLE_DLL_DLL_H
#define CORE_TOOLS_EXAMPLE_DLL_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_CORE_TOOLS_EXAMPLE_NO_IMPORT) || defined(BUILDING_CORE_TOOLS_EXAMPLE_STATIC)

    #define CORE_TOOLS_EXAMPLE_DEFAULT_DECLARE
    #define CORE_TOOLS_EXAMPLE_VISIBLE

    #if defined(BUILDING_CORE_TOOLS_EXAMPLE_EXPORT)

        #define CORE_TOOLS_EXAMPLE_HIDDEN_DECLARE

    #else  // !defined(BUILDING_CORE_TOOLS_EXAMPLE_EXPORT)

        #define CORE_TOOLS_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_CORE_TOOLS_EXAMPLE_EXPORT

#else  // !defined(BUILDING_CORE_TOOLS_EXAMPLE_NO_IMPORT) && !defined(BUILDING_CORE_TOOLS_EXAMPLE_STATIC)

    #if defined(BUILDING_CORE_TOOLS_EXAMPLE_EXPORT)

        #define CORE_TOOLS_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define CORE_TOOLS_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_CORE_TOOLS_EXAMPLE_EXPORT)

        #define CORE_TOOLS_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define CORE_TOOLS_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_CORE_TOOLS_EXAMPLE_EXPORT

    #define CORE_TOOLS_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_CORE_TOOLS_EXAMPLE_NO_IMPORT) || defined(BUILDING_CORE_TOOLS_EXAMPLE_STATIC)

#endif  // CORE_TOOLS_EXAMPLE_DLL_DLL_H
