///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.3 (2021/05/19 23:07)

#ifndef THE_OLD_NEW_THING_DLL_H
#define THE_OLD_NEW_THING_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_THE_OLD_NEW_THING_NO_IMPORT) || defined(BUILDING_THE_OLD_NEW_THING_STATIC)

    #define THE_OLD_NEW_THING_DEFAULT_DECLARE
    #define THE_OLD_NEW_THING_VISIBLE

    #if defined(BUILDING_THE_OLD_NEW_THING_EXPORT)

        #define THE_OLD_NEW_THING_HIDDEN_DECLARE

    #else  // !defined(BUILDING_THE_OLD_NEW_THING_EXPORT)

        #define THE_OLD_NEW_THING_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_THE_OLD_NEW_THING_EXPORT

#else  // !defined(BUILDING_THE_OLD_NEW_THING_NO_IMPORT) && !defined(BUILDING_THE_OLD_NEW_THING_STATIC)

    #if defined(BUILDING_THE_OLD_NEW_THING_EXPORT)

        #define THE_OLD_NEW_THING_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define THE_OLD_NEW_THING_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_THE_OLD_NEW_THING_EXPORT)

        #define THE_OLD_NEW_THING_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define THE_OLD_NEW_THING_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_THE_OLD_NEW_THING_EXPORT

    #define THE_OLD_NEW_THING_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_THE_OLD_NEW_THING_NO_IMPORT) || defined(BUILDING_THE_OLD_NEW_THING_STATIC)

#endif  // THE_OLD_NEW_THING_DLL_H
