///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.1 (2021/01/01 14:25)

#ifndef COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_IMPORT_H
#define COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_IMPORT
    #define BUILDING_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_IMPORT
#endif  // BUILDING_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_IMPORT

#endif  // COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_IMPORT_H
