///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.1 (2021/01/01 14:25)

#ifndef COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_DLL_H
#define COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_NO_IMPORT) || defined(BUILDING_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_STATIC)

    #define COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_DEFAULT_DECLARE
    #define COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_HIDDEN_DECLARE
    #define COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_VISIBLE

#else  // !defined(BUILDING_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_NO_IMPORT) && !defined(BUILDING_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_STATIC)

    #if defined(BUILDING_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_EXPORT)

        #define COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_EXPORT)

        #define COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_EXPORT

    #define COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_NO_IMPORT) || defined(BUILDING_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_STATIC)

#endif  // COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_DLL_H
