/// Copyright (c) 2010-2024
/// Threading Core Render Engine
///
/// 作者：彭武阳，彭晔恩，彭晔泽
/// 联系作者：94458936@qq.com
///
/// 标准：std:c++20
/// 版本：1.0.0.8 (2024/04/12 15:44)

#ifndef CORE_TOOLS_EXAMPLE_HELPER_USER_MACRO_H
#define CORE_TOOLS_EXAMPLE_HELPER_USER_MACRO_H

#include "System/Helper/UserMacro.h"

#define CORE_TOOLS_EXAMPLE_ClOSE_BEGIN (0x01)

#define CLOSE_USE_CORE_TOOLS_EXAMPLE (CORE_TOOLS_EXAMPLE_ClOSE_BEGIN)

#define CORE_TOOLS_EXAMPLE_ClOSE_END CLOSE_USE_CORE_TOOLS_EXAMPLE

#define CLOSE_CORE_TOOLS_EXAMPLE_MAX ((CORE_TOOLS_EXAMPLE_ClOSE_END << 1) - 1)

/// 编译测试（默认为0B0000，最大值为0B0001）
#define COMPILE_CORE_TOOLS_EXAMPLE_CLOSE 0B0000

static_assert(0 <= COMPILE_CORE_TOOLS_EXAMPLE_CLOSE, "COMPILE_CORE_TOOLS_EXAMPLE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_CORE_TOOLS_EXAMPLE_CLOSE <= CLOSE_CORE_TOOLS_EXAMPLE_MAX, "COMPILE_CORE_TOOLS_EXAMPLE_CLOSE Must be less than or equal CLOSE_CORE_TOOLS_EXAMPLE_MAX.");

#if !defined(COMPILE_CORE_TOOLS_EXAMPLE_CLOSE) || (COMPILE_CORE_TOOLS_EXAMPLE_CLOSE & CLOSE_USE_CORE_TOOLS_EXAMPLE) != CLOSE_USE_CORE_TOOLS_EXAMPLE

#endif  // !defined(COMPILE_CORE_TOOLS_EXAMPLE_CLOSE) || (COMPILE_CORE_TOOLS_EXAMPLE_CLOSE & CLOSE_USE_CORE_TOOLS_EXAMPLE) != CLOSE_USE_CORE_TOOLS_EXAMPLE

#ifdef BUILDING_STATIC

    #define BUILDING_CORE_TOOLS_EXAMPLE_STATIC

#endif  // BUILDING_STATIC

#endif  // CORE_TOOLS_EXAMPLE_HELPER_USER_MACRO_H
