// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.1 (2020/01/13 23:42)

#ifndef SHADER_EDITOR_DLL_DLL_H
#define SHADER_EDITOR_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(BUILDING_SHADER_EDITOR_NO_IMPORT) || defined(BUILDING_SHADER_EDITOR_STATIC)

  #define SHADER_EDITOR_DEFAULT_DECLARE
  #define SHADER_EDITOR_HIDDEN_DECLARE
  #define SHADER_EDITOR_VISIBLE

#else // !defined(BUILDING_SHADER_EDITOR_NO_IMPORT) && !defined(BUILDING_SHADER_EDITOR_STATIC)

   #if defined(BUILDING_SHADER_EDITOR_EXPORT)
 
        #define SHADER_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define SHADER_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_SHADER_EDITOR_EXPORT)

		#define SHADER_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define SHADER_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_SHADER_EDITOR_EXPORT

   #define SHADER_EDITOR_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_SHADER_EDITORNO_IMPORT) || defined(BUILDING_SHADER_EDITOR_STATIC)

#endif // SHADER_EDITOR_DLL_DLL_H
