// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.1 (2020/01/14 23:32)

#ifndef SHADOW_EDITOR_DLL_DLL_H
#define SHADOW_EDITOR_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(BUILDING_SHADOW_EDITOR_NO_IMPORT) || defined(BUILDING_SHADOW_EDITOR_STATIC)

  #define SHADOW_EDITOR_DEFAULT_DECLARE
  #define SHADOW_EDITOR_HIDDEN_DECLARE
  #define SHADOW_EDITOR_VISIBLE

#else // !defined(BUILDING_SHADOW_EDITOR_NO_IMPORT) && !defined(BUILDING_SHADOW_EDITOR_STATIC)

   #if defined(BUILDING_SHADOW_EDITOR_EXPORT)
 
        #define SHADOW_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define SHADOW_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_SHADOW_EDITOR_EXPORT)

		#define SHADOW_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define SHADOW_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_SHADOW_EDITOR_EXPORT

   #define SHADOW_EDITOR_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_SHADOW_EDITORNO_IMPORT) || defined(BUILDING_SHADOW_EDITOR_STATIC)

#endif // SHADOW_EDITOR_DLL_DLL_H
