/// Copyright (c) 2010-2024
/// Threading Core Render Engine
///
/// 作者：彭武阳，彭晔恩，彭晔泽
/// 联系作者：94458936@qq.com
///
/// 标准：std:c++20
/// 版本：1.0.0.4 (2024/01/10 19:49)

#ifndef ARTIFICIAL_INTELLIGENCE_MACRO_USER_MACRO_H
#define ARTIFICIAL_INTELLIGENCE_MACRO_USER_MACRO_H

#include "System/Helper/ConfigMacro.h"
#include "CoreTools/Helper/UserMacro.h"

#define ARTIFICIAL_INTELLIGENCE_ClOSE_BEGIN (0x01)

#define CLOSE_USE_ARTIFICIAL_INTELLIGENCE (ARTIFICIAL_INTELLIGENCE_ClOSE_BEGIN)

#define ARTIFICIAL_INTELLIGENCE_ClOSE_END CLOSE_USE_ARTIFICIAL_INTELLIGENCE

#define CLOSE_ARTIFICIAL_INTELLIGENCE_MAX (((ARTIFICIAL_INTELLIGENCE_ClOSE_END) << 1) - 1)

// 编译测试（默认为0B0000，最大值为0B0001）
#define COMPILE_ARTIFICIAL_INTELLIGENCE_CLOSE 0B0000

static_assert(0 <= COMPILE_ARTIFICIAL_INTELLIGENCE_CLOSE, "COMPILE_ARTIFICIAL_INTELLIGENCE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_ARTIFICIAL_INTELLIGENCE_CLOSE <= CLOSE_ARTIFICIAL_INTELLIGENCE_MAX, "COMPILE_ARTIFICIAL_INTELLIGENCE_CLOSE Must be less than or equal CLOSE_ARTIFICIAL_INTELLIGENCE_MAX.");

#if !defined(COMPILE_ARTIFICIAL_INTELLIGENCE_CLOSE) || (COMPILE_ARTIFICIAL_INTELLIGENCE_CLOSE & CLOSE_USE_ARTIFICIAL_INTELLIGENCE) != CLOSE_USE_ARTIFICIAL_INTELLIGENCE

#endif  // !defined(COMPILE_ARTIFICIAL_INTELLIGENCE_CLOSE) || (COMPILE_ARTIFICIAL_INTELLIGENCE_CLOSE & CLOSE_USE_ARTIFICIAL_INTELLIGENCE) != CLOSE_USE_ARTIFICIAL_INTELLIGENCE

#ifdef BUILDING_STATIC

    #define BUILDING_ARTIFICIAL_INTELLIGENCE_STATIC

#endif  // BUILDING_STATIC

#endif  // ARTIFICIAL_INTELLIGENCE_MACRO_USER_MACRO_H
