///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.3 (2021/05/01 19:03)

#ifndef MICROSOFT_WINDOWS_INTERNALS_FOURTH_EDITION_EXPORT_H
#define MICROSOFT_WINDOWS_INTERNALS_FOURTH_EDITION_EXPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_MICROSOFT_WINDOWS_INTERNALS_FOURTH_EDITION_EXPORT
    #define BUILDING_MICROSOFT_WINDOWS_INTERNALS_FOURTH_EDITION_EXPORT
#endif  // BUILDING_MICROSOFT_WINDOWS_INTERNALS_FOURTH_EDITION_EXPORT

#endif  // MICROSOFT_WINDOWS_INTERNALS_FOURTH_EDITION_EXPORT_H
