///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.5 (2021/11/02 22:35)

#ifndef BOOK_CONCURRENT_PROGRAMMING_TOOLSET_IMPORT_H
#define BOOK_CONCURRENT_PROGRAMMING_TOOLSET_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_BOOK_CONCURRENT_PROGRAMMING_TOOLSET_IMPORT
    #define BUILDING_BOOK_CONCURRENT_PROGRAMMING_TOOLSET_IMPORT
#endif  // BUILDING_BOOK_CONCURRENT_PROGRAMMING_TOOLSET_IMPORT

#endif  // BOOK_CONCURRENT_PROGRAMMING_TOOLSET_IMPORT_H
