// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 引擎辅助版本：0.0.1.0 (2019/11/06 09:48)

#ifndef BOOK_GAME_PROGRAMMING_MACRO_USER_MACRO_H
#define BOOK_GAME_PROGRAMMING_MACRO_USER_MACRO_H

#include "System/Helper/ConfigMacro.h"
#include "CoreTools/Helper/UserMacro.h" 

#define CLOSE_USE_XXX (0x01) 
#define CLOSE_BOOK_GAME_PROGRAMMING_MAX (((CLOSE_USE_XXX) << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_BOOK_GAME_PROGRAMMING_CLOSE 0x00

static_assert(0 <= COMPILE_BOOK_GAME_PROGRAMMING_CLOSE, "COMPILE_BOOK_GAME_PROGRAMMING_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_BOOK_GAME_PROGRAMMING_CLOSE <= CLOSE_BOOK_GAME_PROGRAMMING_MAX, "COMPILE_BOOK_GAME_PROGRAMMING_CLOSE Must be less than or equal CLOSE_BOOK_GAME_PROGRAMMING_MAX.");

// 是否编译为静态库
#ifdef BUILDING_STATIC
	#define  BUILDING_BOOK_GAME_PROGRAMMING_STATIC
#endif // BUILDING_STATIC

#if !defined(COMPILE_BOOK_GAME_PROGRAMMING_CLOSE) || (COMPILE_BOOK_GAME_PROGRAMMING_CLOSE & CLOSE_USE_XXX) != CLOSE_USE_XXX

#endif // !defined(COMPILE_BOOK_GAME_PROGRAMMING_CLOSE) || (COMPILE_BOOK_GAME_PROGRAMMING_CLOSE & CLOSE_USE_XXX) != CLOSE_USE_XXX 
 
#endif // BOOK_GAME_PROGRAMMING_MACRO_USER_MACRO_H
