///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.1 (2021/02/09 14:57)

#ifndef PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_HELPER_USER_MACRO_H
#define PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_ClOSE_BEGIN (0x01)

#define CLOSE_USE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS (PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_ClOSE_BEGIN)

#define PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_ClOSE_END CLOSE_USE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS

#define CLOSE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_MAX ((PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_CLOSE 0x00

static_assert(0 <= COMPILE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_CLOSE, "COMPILE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_CLOSE <= CLOSE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_MAX, "COMPILE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_CLOSE Must be less than or equal CLOSE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_MAX.");

#if !defined(COMPILE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_CLOSE) || (COMPILE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_CLOSE & CLOSE_USE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS) != CLOSE_USE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS

#endif  // !defined(COMPILE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_CLOSE) || (COMPILE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_CLOSE & CLOSE_USE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS) != CLOSE_USE_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_STATIC
#endif  // BUILDING_STATIC

#endif  // PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_HELPER_USER_MACRO_H
