// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.2 (2020/01/26 20:19)

#ifndef ANIMATION_EXAMPLE_DLL_DLL_H
#define ANIMATION_EXAMPLE_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(BUILDING_ANIMATION_EXAMPLE_NO_IMPORT) || defined(BUILDING_ANIMATION_EXAMPLE_STATIC)

  #define ANIMATION_EXAMPLE_DEFAULT_DECLARE
  #define ANIMATION_EXAMPLE_HIDDEN_DECLARE
  #define ANIMATION_EXAMPLE_VISIBLE

#else // !defined(BUILDING_ANIMATION_EXAMPLE_NO_IMPORT) && !defined(BUILDING_ANIMATION_EXAMPLE_STATIC)

   #if defined(BUILDING_ANIMATION_EXAMPLE_EXPORT)
 
        #define ANIMATION_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define ANIMATION_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_ANIMATION_EXAMPLE_EXPORT)

		#define ANIMATION_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define ANIMATION_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_ANIMATION_EXAMPLE_EXPORT

   #define ANIMATION_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_ANIMATION_EXAMPLE_NO_IMPORT) || defined(BUILDING_ANIMATION_EXAMPLE_STATIC)

#endif // ANIMATION_EXAMPLE_DLL_DLL_H
