///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	版本：0.9.1.2 (2023/07/31 14:02)

#ifndef ARTIFICIAL_INTELLIGENCE_EXAMPLE_EXPORT_H
#define ARTIFICIAL_INTELLIGENCE_EXAMPLE_EXPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_ARTIFICIAL_INTELLIGENCE_EXAMPLE_EXPORT

    #define BUILDING_ARTIFICIAL_INTELLIGENCE_EXAMPLE_EXPORT

#endif  // BUILDING_ARTIFICIAL_INTELLIGENCE_EXAMPLE_EXPORT

#endif  // ARTIFICIAL_INTELLIGENCE_EXAMPLE_EXPORT_H
