///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.2 (2021/08/27 22:50)

#ifndef EFFECTIVE_MODERN_CPP_HELPER_USER_MACRO_H
#define EFFECTIVE_MODERN_CPP_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define EFFECTIVE_MODERN_CPP_ClOSE_BEGIN (0x01)

#define CLOSE_USE_EFFECTIVE_MODERN_CPP (EFFECTIVE_MODERN_CPP_ClOSE_BEGIN)

#define EFFECTIVE_MODERN_CPP_ClOSE_END CLOSE_USE_EFFECTIVE_MODERN_CPP

#define CLOSE_EFFECTIVE_MODERN_CPP_MAX ((EFFECTIVE_MODERN_CPP_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_EFFECTIVE_MODERN_CPP_CLOSE 0x00

static_assert(0 <= COMPILE_EFFECTIVE_MODERN_CPP_CLOSE, "COMPILE_EFFECTIVE_MODERN_CPP_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_EFFECTIVE_MODERN_CPP_CLOSE <= CLOSE_EFFECTIVE_MODERN_CPP_MAX, "COMPILE_EFFECTIVE_MODERN_CPP_CLOSE Must be less than or equal CLOSE_EFFECTIVE_MODERN_CPP_MAX.");

#if !defined(COMPILE_EFFECTIVE_MODERN_CPP_CLOSE) || (COMPILE_EFFECTIVE_MODERN_CPP_CLOSE & CLOSE_USE_EFFECTIVE_MODERN_CPP) != CLOSE_USE_EFFECTIVE_MODERN_CPP

#endif  // !defined(COMPILE_EFFECTIVE_MODERN_CPP_CLOSE) || (COMPILE_EFFECTIVE_MODERN_CPP_CLOSE & CLOSE_USE_EFFECTIVE_MODERN_CPP) != CLOSE_USE_EFFECTIVE_MODERN_CPP

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_EFFECTIVE_MODERN_CPP_STATIC
#endif  // BUILDING_STATIC

#endif  // EFFECTIVE_MODERN_CPP_HELPER_USER_MACRO_H
