///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.0 (2021/02/16 17:46)

#ifndef CPP_COMMON_KNOWLEDGE_HELPER_USER_MACRO_H
#define CPP_COMMON_KNOWLEDGE_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define CPP_COMMON_KNOWLEDGE_ClOSE_BEGIN (0x01)

#define CLOSE_USE_CPP_COMMON_KNOWLEDGE (CPP_COMMON_KNOWLEDGE_ClOSE_BEGIN)

#define CPP_COMMON_KNOWLEDGE_ClOSE_END CLOSE_USE_CPP_COMMON_KNOWLEDGE

#define CLOSE_CPP_COMMON_KNOWLEDGE_MAX ((CPP_COMMON_KNOWLEDGE_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_CPP_COMMON_KNOWLEDGE_CLOSE 0x00

static_assert(0 <= COMPILE_CPP_COMMON_KNOWLEDGE_CLOSE, "COMPILE_CPP_COMMON_KNOWLEDGE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_CPP_COMMON_KNOWLEDGE_CLOSE <= CLOSE_CPP_COMMON_KNOWLEDGE_MAX, "COMPILE_CPP_COMMON_KNOWLEDGE_CLOSE Must be less than or equal CLOSE_CPP_COMMON_KNOWLEDGE_MAX.");

#if !defined(COMPILE_CPP_COMMON_KNOWLEDGE_CLOSE) || (COMPILE_CPP_COMMON_KNOWLEDGE_CLOSE & CLOSE_USE_CPP_COMMON_KNOWLEDGE) != CLOSE_USE_CPP_COMMON_KNOWLEDGE

#endif  // !defined(COMPILE_CPP_COMMON_KNOWLEDGE_CLOSE) || (COMPILE_CPP_COMMON_KNOWLEDGE_CLOSE & CLOSE_USE_CPP_COMMON_KNOWLEDGE) != CLOSE_USE_CPP_COMMON_KNOWLEDGE

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_CPP_COMMON_KNOWLEDGE_STATIC
#endif  // BUILDING_STATIC

#endif  // CPP_COMMON_KNOWLEDGE_HELPER_USER_MACRO_H
