/// Copyright (c) 2010-2023
/// Threading Core Render Engine
///
/// 作者：彭武阳，彭晔恩，彭晔泽
/// 联系作者：94458936@qq.com
///
/// 标准：std:c++20
/// 版本：0.9.1.3 (2023/08/21 10:42)

#ifndef THE_LAST_OVERLORD_USER_MACRO_H
#define THE_LAST_OVERLORD_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define THE_LAST_OVERLORD_ClOSE_BEGIN (0x01)

#define CLOSE_USE_THE_LAST_OVERLORD (THE_LAST_OVERLORD_ClOSE_BEGIN)

#define THE_LAST_OVERLORD_ClOSE_END CLOSE_USE_THE_LAST_OVERLORD

#define CLOSE_THE_LAST_OVERLORD_MAX ((THE_LAST_OVERLORD_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_THE_LAST_OVERLORD_CLOSE 0x00

static_assert(0 <= COMPILE_THE_LAST_OVERLORD_CLOSE, "COMPILE_THE_LAST_OVERLORD_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_THE_LAST_OVERLORD_CLOSE <= CLOSE_THE_LAST_OVERLORD_MAX, "COMPILE_THE_LAST_OVERLORD_CLOSE Must be less than or equal CLOSE_THE_LAST_OVERLORD_MAX.");

#if !defined(COMPILE_THE_LAST_OVERLORD_CLOSE) || (COMPILE_THE_LAST_OVERLORD_CLOSE & CLOSE_USE_THE_LAST_OVERLORD) != CLOSE_USE_THE_LAST_OVERLORD

#endif  // !defined(COMPILE_THE_LAST_OVERLORD_CLOSE) || (COMPILE_THE_LAST_OVERLORD_CLOSE & CLOSE_USE_THE_LAST_OVERLORD) != CLOSE_USE_THE_LAST_OVERLORD

#ifdef BUILDING_STATIC

    #define BUILDING_THE_LAST_OVERLORD_STATIC (static_cast<void>(0))

#endif  // BUILDING_STATIC

#endif  // THE_LAST_OVERLORD_USER_MACRO_H
