///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.0 (2021/01/30 11:03)

#ifndef ALGORITHMS_UNLOCKED_HELPER_USER_MACRO_H
#define ALGORITHMS_UNLOCKED_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define ALGORITHMS_UNLOCKED_ClOSE_BEGIN (0x01)

#define CLOSE_USE_ALGORITHMS_UNLOCKED (ALGORITHMS_UNLOCKED_ClOSE_BEGIN)

#define ALGORITHMS_UNLOCKED_ClOSE_END CLOSE_USE_ALGORITHMS_UNLOCKED

#define CLOSE_ALGORITHMS_UNLOCKED_MAX ((ALGORITHMS_UNLOCKED_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_ALGORITHMS_UNLOCKED_CLOSE 0x00

static_assert(0 <= COMPILE_ALGORITHMS_UNLOCKED_CLOSE, "COMPILE_ALGORITHMS_UNLOCKED_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_ALGORITHMS_UNLOCKED_CLOSE <= CLOSE_ALGORITHMS_UNLOCKED_MAX, "COMPILE_ALGORITHMS_UNLOCKED_CLOSE Must be less than or equal CLOSE_ALGORITHMS_UNLOCKED_MAX.");

#if !defined(COMPILE_ALGORITHMS_UNLOCKED_CLOSE) || (COMPILE_ALGORITHMS_UNLOCKED_CLOSE & CLOSE_USE_ALGORITHMS_UNLOCKED) != CLOSE_USE_ALGORITHMS_UNLOCKED

#endif  // !defined(COMPILE_ALGORITHMS_UNLOCKED_CLOSE) || (COMPILE_ALGORITHMS_UNLOCKED_CLOSE & CLOSE_USE_ALGORITHMS_UNLOCKED) != CLOSE_USE_ALGORITHMS_UNLOCKED

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_ALGORITHMS_UNLOCKED_STATIC
#endif  // BUILDING_STATIC

#endif  // ALGORITHMS_UNLOCKED_HELPER_USER_MACRO_H
