// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
// 
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.1.0 (2019/11/06 09:41)

#ifndef BOOK_GAME_PROGRAMMING_DLL_H
#define BOOK_GAME_PROGRAMMING_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(BUILDING_BOOK_GAME_PROGRAMMING_NO_IMPORT) || defined(BUILDING_BOOK_GAME_PROGRAMMING_STATIC)

  #define BOOK_GAME_PROGRAMMING_DEFAULT_DECLARE
  #define BOOK_GAME_PROGRAMMING_HIDDEN_DECLARE 
  #define BOOK_GAME_PROGRAMMING_VISIBLE

#else // !defined(BUILDING_BOOK_GAME_PROGRAMMING_NO_IMPORT) && !defined(BUILDING_BOOK_GAME_PROGRAMMING_STATIC)
 
   #if defined(BUILDING_BOOK_GAME_PROGRAMMING_EXPORT)
 
        #define BOOK_GAME_PROGRAMMING_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define BOOK_GAME_PROGRAMMING_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_BOOK_GAME_PROGRAMMING_EXPORT)

		#define BOOK_GAME_PROGRAMMING_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define BOOK_GAME_PROGRAMMING_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_BOOK_GAME_PROGRAMMING_EXPORT

   #define BOOK_GAME_PROGRAMMING_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_BOOK_GAME_PROGRAMMING_NO_IMPORT) || defined(BUILDING_BOOK_GAME_PROGRAMMING_STATIC)
 
#endif // BOOK_GAME_PROGRAMMING_DLL_H
