///	Copyright (c) 2010-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.0 (2020/12/21 20:52)

#ifndef BOOK_PRIMARY_HELPER_USER_MACRO_H
#define BOOK_PRIMARY_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define BOOK_PRIMARY_ClOSE_BEGIN (0x01)

#define CLOSE_USE_BOOK_PRIMARY (BOOK_PRIMARY_ClOSE_BEGIN)

#define BOOK_PRIMARY_ClOSE_END CLOSE_USE_BOOK_PRIMARY

#define CLOSE_BOOK_PRIMARY_MAX ((BOOK_PRIMARY_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_BOOK_PRIMARY_CLOSE 0x00

static_assert(0 <= COMPILE_BOOK_PRIMARY_CLOSE, "COMPILE_BOOK_PRIMARY_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_BOOK_PRIMARY_CLOSE <= CLOSE_BOOK_PRIMARY_MAX, "COMPILE_BOOK_PRIMARY_CLOSE Must be less than or equal CLOSE_BOOK_PRIMARY_MAX.");

#if !defined(COMPILE_BOOK_PRIMARY_CLOSE) || (COMPILE_BOOK_PRIMARY_CLOSE & CLOSE_USE_BOOK_PRIMARY) != CLOSE_USE_BOOK_PRIMARY

#endif  // !defined(COMPILE_BOOK_PRIMARY_CLOSE) || (COMPILE_BOOK_PRIMARY_CLOSE & CLOSE_USE_BOOK_PRIMARY) != CLOSE_USE_BOOK_PRIMARY

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_BOOK_PRIMARY_STATIC
#endif  // BUILDING_STATIC

#endif  // BOOK_PRIMARY_HELPER_USER_MACRO_H
