// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.1 (2020/01/18 23:43)

#ifndef TEXTURE_EDITOR_DLL_DLL_H
#define TEXTURE_EDITOR_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(BUILDING_TEXTURE_EDITOR_NO_IMPORT) || defined(BUILDING_TEXTURE_EDITOR_STATIC)

  #define TEXTURE_EDITOR_DEFAULT_DECLARE
  #define TEXTURE_EDITOR_HIDDEN_DECLARE
  #define TEXTURE_EDITOR_VISIBLE

#else // !defined(BUILDING_TEXTURE_EDITOR_NO_IMPORT) && !defined(BUILDING_TEXTURE_EDITOR_STATIC)

   #if defined(BUILDING_TEXTURE_EDITOR_EXPORT)
 
        #define TEXTURE_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define TEXTURE_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_TEXTURE_EDITOR_EXPORT)

		#define TEXTURE_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define TEXTURE_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_TEXTURE_EDITOR_EXPORT

   #define TEXTURE_EDITOR_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_TEXTURE_EDITORNO_IMPORT) || defined(BUILDING_TEXTURE_EDITOR_STATIC)

#endif // TEXTURE_EDITOR_DLL_DLL_H
