///	Copyright (c) 2010-2022
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	引擎辅助版本：0.8.0.10 (2022/07/11 13:48)

#ifndef TEXTURE_EDITOR_DLL_DLL_H
#define TEXTURE_EDITOR_DLL_DLL_H

#include "Macro/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_TEXTURE_EDITOR_NO_IMPORT) || defined(BUILDING_TEXTURE_EDITOR_STATIC)

    #define TEXTURE_EDITOR_DEFAULT_DECLARE
    #define TEXTURE_EDITOR_HIDDEN_DECLARE
    #define TEXTURE_EDITOR_VISIBLE

#else  // !defined(BUILDING_TEXTURE_EDITOR_NO_IMPORT) && !defined(BUILDING_TEXTURE_EDITOR_STATIC)

    #if defined(BUILDING_TEXTURE_EDITOR_EXPORT)

        #define TEXTURE_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define TEXTURE_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_TEXTURE_EDITOR_EXPORT)

        #define TEXTURE_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define TEXTURE_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_TEXTURE_EDITOR_EXPORT

    #define TEXTURE_EDITOR_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_TEXTURE_EDITORNO_IMPORT) || defined(BUILDING_TEXTURE_EDITOR_STATIC)

#endif  // TEXTURE_EDITOR_DLL_DLL_H
