///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.6 (2021/11/21 20:58)

#ifndef LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_DLL_H
#define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_NO_IMPORT) || defined(BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_STATIC)

    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_DEFAULT_DECLARE
    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_VISIBLE

    #if defined(BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_EXPORT)

        #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_HIDDEN_DECLARE

    #else  // !defined(BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_EXPORT)

        #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_EXPORT

#else  // !defined(BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_NO_IMPORT) && !defined(BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_STATIC)

    #if defined(BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_EXPORT)

        #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_EXPORT)

        #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_EXPORT

    #define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_NO_IMPORT) || defined(BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_STATIC)

#endif  // LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_DLL_H
