///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.6 (2021/11/21 20:53)

#ifndef LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_NO_IMPORT_H
#define LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_NO_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_NO_IMPORT
    #define BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_NO_IMPORT
#endif  // BUILDING_LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_NO_IMPORT

#endif  // LINUX_COMMAND_LINE_AND_SHELL_SCRIPTING_BIBLE_NO_IMPORT_H
