///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.3 (2021/09/08 21:15)

#ifndef CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_HELPER_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_CUSTOM_ASSERT_MACRO_H
#define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_HELPER_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_CUSTOM_ASSERT_MACRO_H

#include "UserMacro.h"
#include "CoreTools/Helper/Assertion/UserCustomAssertMacro.h"

#if defined(OPEN_IMPORTANT_EXCPTION_ASSERT)
    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL 0
#endif  // OPEN_IMPORTANT_EXCPTION_ASSERT

#if !defined(CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL)
    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL 4
#endif  // CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL

constexpr auto g_ConfiguringWindowsServer2008NetworkInfrastructureAssert = CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL;

static_assert(CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL <= USER_ASSERT_LEVEL, "Assert level definition error.");

#if 0 <= CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL

    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_0(condition, format, ...) \
        USER_ASSERTION_0((condition), (format), __VA_ARGS__)
    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_USE_FUNCTION_DESCRIBED_0(condition, functionDescribed, format, ...) \
        USER_ASSERTION_USE_FUNCTION_DESCRIBED_0((condition), (functionDescribed), (format), __VA_ARGS__)

    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_DEBUG(condition, format, ...) \
        USER_ASSERTION_DEBUG((condition), (format), __VA_ARGS__)
    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_DEBUG_USE_FUNCTION_DESCRIBED(condition, functionDescribed, format, ...) \
        USER_ASSERTION_DEBUG_USE_FUNCTION_DESCRIBED((condition), (functionDescribed), (format), __VA_ARGS__)

#else  // CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL < 0

    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_0(condition, format, ...) (static_cast<void>(0))
    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_USE_FUNCTION_DESCRIBED_0(condition, functionDescribed, format, ...) (static_cast<void>(0))

    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_DEBUG(condition, format, ...) (static_cast<void>(0))
    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_DEBUG_USE_FUNCTION_DESCRIBED(condition, functionDescribed, format, ...) (static_cast<void>(0))

#endif  // 0 <= CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL

#if 1 <= CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL

    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_1(condition, format, ...) \
        USER_ASSERTION_1((condition), (format), __VA_ARGS__)
    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_USE_FUNCTION_DESCRIBED_1(condition, functionDescribed, format, ...) \
        USER_ASSERTION_USE_FUNCTION_DESCRIBED_1((condition), (functionDescribed), (format), __VA_ARGS__)

#else  // CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL < 1

    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_1(condition, format, ...) (static_cast<void>(0))
    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_USE_FUNCTION_DESCRIBED_1(condition, functionDescribed, format, ...) (static_cast<void>(0))

#endif  // 1 <= CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL

#if 2 <= CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL

    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_2(condition, format, ...) \
        USER_ASSERTION_2((condition), (format), __VA_ARGS__)
    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_USE_FUNCTION_DESCRIBED_2(condition, functionDescribed, format, ...) \
        USER_ASSERTION_USE_FUNCTION_DESCRIBED_2((condition), (functionDescribed), (format), __VA_ARGS__)

#else  // CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL < 2

    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_2(condition, format, ...) (static_cast<void>(0))
    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_USE_FUNCTION_DESCRIBED_2(condition, functionDescribed, format, ...) (static_cast<void>(0))

#endif  // 2 <= CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL

#if 3 <= CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL

    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_3(condition, format, ...) \
        USER_ASSERTION_3((condition), (format), __VA_ARGS__)
    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_USE_FUNCTION_DESCRIBED_3(condition, functionDescribed, format, ...) \
        USER_ASSERTION_USE_FUNCTION_DESCRIBED_3((condition), (functionDescribed), (format), __VA_ARGS__)

#else  // CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL < 3

    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_3(condition, format, ...) (static_cast<void>(0))
    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_USE_FUNCTION_DESCRIBED_3(condition, functionDescribed, format, ...) (static_cast<void>(0))

#endif  // 3 <= CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL

#if 4 <= CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL

    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_4(condition, format, ...) \
        USER_ASSERTION_4((condition), (format), __VA_ARGS__)
    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_USE_FUNCTION_DESCRIBED_4(condition, functionDescribed, format, ...) \
        USER_ASSERTION_USE_FUNCTION_DESCRIBED_4((condition), (functionDescribed), (format), __VA_ARGS__)

#else  // CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL < 4

    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_4(condition, format, ...) (static_cast<void>(0))
    #define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERTION_USE_FUNCTION_DESCRIBED_4(condition, functionDescribed, format, ...) (static_cast<void>(0))

#endif  // 4 <= CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ASSERT_LEVEL

#endif  // CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_HELPER_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_CUSTOM_ASSERT_MACRO_H
