///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.3 (2021/09/08 21:15)

#ifndef CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_HELPER_USER_MACRO_H
#define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ClOSE_BEGIN (0x01)

#define CLOSE_USE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE (CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ClOSE_BEGIN)

#define CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ClOSE_END CLOSE_USE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE

#define CLOSE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_MAX ((CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_CLOSE 0x00

static_assert(0 <= COMPILE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_CLOSE, "COMPILE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_CLOSE <= CLOSE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_MAX, "COMPILE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_CLOSE Must be less than or equal CLOSE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_MAX.");

#if !defined(COMPILE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_CLOSE) || (COMPILE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_CLOSE & CLOSE_USE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE) != CLOSE_USE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE

#endif  // !defined(COMPILE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_CLOSE) || (COMPILE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_CLOSE & CLOSE_USE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE) != CLOSE_USE_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE

#ifdef BUILDING_STATIC
    #define BUILDING_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_STATIC
#endif  // BUILDING_STATIC

#endif  // CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_HELPER_USER_MACRO_H
