///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.0 (2021/01/24 15:20)

#ifndef CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_NO_IMPORT_H
#define CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_NO_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_NO_IMPORT
    #define BUILDING_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_NO_IMPORT
#endif  // BUILDING_CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_NO_IMPORT

#endif  // CPP_EFFECTIVE_OBJECT_ORIENTED_SOFTWARE_CONSTRUCTION_NO_IMPORT_H
