// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.0.3 (2019/10/01 11:28)

#ifndef FREEALUT_LIB_EXAMPLE_DLL_H
#define FREEALUT_LIB_EXAMPLE_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(FREEALUT_LIB_EXAMPLE_NO_IMPORT) || defined(BUILDING_FREEALUT_LIB_EXAMPLE_STATIC)

  #define FREEALUT_LIB_EXAMPLE_DEFAULT_DECLARE
  #define FREEALUT_LIB_EXAMPLE_HIDDEN_DECLARE
  #define FREEALUT_LIB_EXAMPLE_VISIBLE

#else // !defined(FREEALUT_LIB_EXAMPLE_NO_IMPORT) && !defined(FREEALUT_LIB_EXAMPLE_STATIC)

   #if defined(FREEALUT_LIB_EXAMPLE_EXPORT)
 
        #define FREEALUT_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define FREEALUT_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(FREEALUT_LIB_EXAMPLE_EXPORT)

		#define FREEALUT_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define FREEALUT_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // FREEALUT_LIB_EXAMPLE_EXPORT

   #define FREEALUT_LIB_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(FREEALUT_LIB_EXAMPLE_NO_IMPORT) || defined(FREEALUT_LIB_EXAMPLE_STATIC)

#endif // FREEALUT_LIB_EXAMPLE_DLL_H
