///	Copyright (c) 2011-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎版本：0.5.2.5 (2020/12/08 15:13)

#ifndef MATHEMATICS_DISTANCE_DISTANCE_POINT2_HYPERBOLA2_DETAIL_H
#define MATHEMATICS_DISTANCE_DISTANCE_POINT2_HYPERBOLA2_DETAIL_H

#include "DistancePoint2Hyperbola2.h"

#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_DISTANCE_POINT2_HYPERBOLA2_ACHIEVE)

    #include "DistancePoint2Hyperbola2Achieve.h"

#endif  // !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_DISTANCE_POINT2_HYPERBOLA2_ACHIEVE)

#endif  // MATHEMATICS_DISTANCE_DISTANCE_POINT2_HYPERBOLA2_DETAIL_H
