///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.7 (2021/11/30 21:54)

#ifndef THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_DLL_H
#define THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_NO_IMPORT) || defined(BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_STATIC)

    #define THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_DEFAULT_DECLARE
    #define THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_VISIBLE

    #if defined(BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_EXPORT)

        #define THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_HIDDEN_DECLARE

    #else  // !defined(BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_EXPORT)

        #define THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_EXPORT

#else  // !defined(BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_NO_IMPORT) && !defined(BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_STATIC)

    #if defined(BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_EXPORT)

        #define THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_EXPORT)

        #define THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_EXPORT

    #define THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_NO_IMPORT) || defined(BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_STATIC)

#endif  // THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_DLL_H
