///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.7 (2021/11/30 21:53)

#ifndef THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_NO_IMPORT_H
#define THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_NO_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_NO_IMPORT
    #define BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_NO_IMPORT
#endif  // BUILDING_THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_NO_IMPORT

#endif  // THRIVING_IN_A_CROWDED_AND_CHANGING_WORLD_NO_IMPORT_H
