// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.0 (2020/01/07 23:00)

#ifndef ANIMATION_TOOLSET_DLL_DLL_H
#define ANIMATION_TOOLSET_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Animation/Helper/UserMacro.h"

#if defined(BUILDING_ANIMATION_TOOLSET_NO_IMPORT) || defined(BUILDING_ANIMATION_STATIC)

  #define ANIMATION_TOOLSET_DEFAULT_DECLARE
  #define ANIMATION_TOOLSET_HIDDEN_DECLARE
  #define ANIMATION_TOOLSET_VISIBLE

#else // !defined(BUILDING_ANIMATION_TOOLSET_NO_IMPORT) && !defined(BUILDING_ANIMATION_STATIC)

   #if defined(BUILDING_ANIMATION_TOOLSET_EXPORT)
 
        #define ANIMATION_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define ANIMATION_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_ANIMATION_TOOLSET_EXPORT)

		#define ANIMATION_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define ANIMATION_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_ANIMATION_TOOLSET_EXPORT

   #define ANIMATION_TOOLSET_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_ANIMATION_TOOLSET_NO_IMPORT) || defined(BUILDING_ANIMATION_STATIC)

#endif // ANIMATION_TOOLSET_DLL_DLL_H