///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.5 (2021/10/28 22:20)

#ifndef DISTRIBUTED_SYSTEMS_HELPER_USER_MACRO_H
#define DISTRIBUTED_SYSTEMS_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define DISTRIBUTED_SYSTEMS_ClOSE_BEGIN (0x01)

#define CLOSE_USE_DISTRIBUTED_SYSTEMS (DISTRIBUTED_SYSTEMS_ClOSE_BEGIN)

#define DISTRIBUTED_SYSTEMS_ClOSE_END CLOSE_USE_DISTRIBUTED_SYSTEMS

#define CLOSE_DISTRIBUTED_SYSTEMS_MAX ((DISTRIBUTED_SYSTEMS_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_DISTRIBUTED_SYSTEMS_CLOSE 0x00

static_assert(0 <= COMPILE_DISTRIBUTED_SYSTEMS_CLOSE, "COMPILE_DISTRIBUTED_SYSTEMS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_DISTRIBUTED_SYSTEMS_CLOSE <= CLOSE_DISTRIBUTED_SYSTEMS_MAX, "COMPILE_DISTRIBUTED_SYSTEMS_CLOSE Must be less than or equal CLOSE_DISTRIBUTED_SYSTEMS_MAX.");

#if !defined(COMPILE_DISTRIBUTED_SYSTEMS_CLOSE) || (COMPILE_DISTRIBUTED_SYSTEMS_CLOSE & CLOSE_USE_DISTRIBUTED_SYSTEMS) != CLOSE_USE_DISTRIBUTED_SYSTEMS

#endif  // !defined(COMPILE_DISTRIBUTED_SYSTEMS_CLOSE) || (COMPILE_DISTRIBUTED_SYSTEMS_CLOSE & CLOSE_USE_DISTRIBUTED_SYSTEMS) != CLOSE_USE_DISTRIBUTED_SYSTEMS

#ifdef BUILDING_STATIC
    #define BUILDING_DISTRIBUTED_SYSTEMS_STATIC
#endif  // BUILDING_STATIC

#endif  // DISTRIBUTED_SYSTEMS_HELPER_USER_MACRO_H
