///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.4 (2021/10/07 23:22)

#ifndef THE_DEVELOPERS_GUIDE_TO_DEBUGGING_DLL_H
#define THE_DEVELOPERS_GUIDE_TO_DEBUGGING_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_NO_IMPORT) || defined(BUILDING_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_STATIC)

    #define THE_DEVELOPERS_GUIDE_TO_DEBUGGING_DEFAULT_DECLARE
    #define THE_DEVELOPERS_GUIDE_TO_DEBUGGING_VISIBLE

    #if defined(BUILDING_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_EXPORT)

        #define THE_DEVELOPERS_GUIDE_TO_DEBUGGING_HIDDEN_DECLARE

    #else  // !defined(BUILDING_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_EXPORT)

        #define THE_DEVELOPERS_GUIDE_TO_DEBUGGING_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_EXPORT

#else  // !defined(BUILDING_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_NO_IMPORT) && !defined(BUILDING_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_STATIC)

    #if defined(BUILDING_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_EXPORT)

        #define THE_DEVELOPERS_GUIDE_TO_DEBUGGING_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define THE_DEVELOPERS_GUIDE_TO_DEBUGGING_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_EXPORT)

        #define THE_DEVELOPERS_GUIDE_TO_DEBUGGING_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define THE_DEVELOPERS_GUIDE_TO_DEBUGGING_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_EXPORT

    #define THE_DEVELOPERS_GUIDE_TO_DEBUGGING_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_NO_IMPORT) || defined(BUILDING_THE_DEVELOPERS_GUIDE_TO_DEBUGGING_STATIC)

#endif  // THE_DEVELOPERS_GUIDE_TO_DEBUGGING_DLL_H
