///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.0 (2021/01/24 13:06)

#ifndef CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_HELPER_USER_MACRO_H
#define CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_ClOSE_BEGIN (0x01)

#define CLOSE_USE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH (CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_ClOSE_BEGIN)

#define CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_ClOSE_END CLOSE_USE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH

#define CLOSE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_MAX ((CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_CLOSE 0x00

static_assert(0 <= COMPILE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_CLOSE, "COMPILE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_CLOSE <= CLOSE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_MAX, "COMPILE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_CLOSE Must be less than or equal CLOSE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_MAX.");

#if !defined(COMPILE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_CLOSE) || (COMPILE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_CLOSE & CLOSE_USE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH) != CLOSE_USE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH

#endif  // !defined(COMPILE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_CLOSE) || (COMPILE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_CLOSE & CLOSE_USE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH) != CLOSE_USE_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_STATIC
#endif  // BUILDING_STATIC

#endif  // CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_HELPER_USER_MACRO_H
