//	Copyright (c) 2011-2020
//	Threading Core Render Engine
//
//	作者：彭武阳，彭晔恩，彭晔泽
//	联系作者：94458936@qq.com
//
//	标准：std:c++17
//	引擎版本：0.5.0.0 (2020/08/16 1:46)

#ifndef THREADING_CORE_RENDER_ENGINE_DLL_H
#define THREADING_CORE_RENDER_ENGINE_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Framework/Helper/UserMacro.h"

#if defined(BUILDING_THREADING_CORE_RENDER_ENGINE_NO_IMPORT) || defined(BUILDING_STATIC)

    #define THREADING_CORE_RENDER_ENGINE_DEFAULT_DECLARE
    #define THREADING_CORE_RENDER_ENGINE_HIDDEN_DECLARE
    #define THREADING_CORE_RENDER_ENGINE_VISIBLE

#else  // !defined(BUILDING_THREADING_CORE_RENDER_ENGINE_NO_IMPORT) && !defined(BUILDING_STATIC)

    #if defined(BUILDING_THREADING_CORE_RENDER_ENGINE_EXPORT)

        #define THREADING_CORE_RENDER_ENGINE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define THREADING_CORE_RENDER_ENGINE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_THREADING_CORE_RENDER_ENGINE_EXPORT)

        #define THREADING_CORE_RENDER_ENGINE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define THREADING_CORE_RENDER_ENGINE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_THREADING_CORE_RENDER_ENGINE_EXPORT

    #define THREADING_CORE_RENDER_ENGINE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_THREADING_CORE_RENDER_ENGINE_NO_IMPORT) || defined(BUILDING_STATIC)

#endif  // THREADING_CORE_RENDER_ENGINE_DLL_H