//	Copyright (c) 2011-2020
//	Threading Core Render Engine
//
//	作者：彭武阳，彭晔恩，彭晔泽
//	联系作者：94458936@qq.com
//
//	标准：std:c++17
//	引擎版本：0.5.0.0 (2020/08/16 1:47)

#ifndef THREADING_CORE_RENDER_ENGINE_NO_IMPORT_H
#define THREADING_CORE_RENDER_ENGINE_NO_IMPORT_H

#include "Framework/Helper/UserMacro.h"

#ifndef BUILDING_THREADING_CORE_RENDER_ENGINE_NO_IMPORT
    #define BUILDING_THREADING_CORE_RENDER_ENGINE_NO_IMPORT
#endif  // BUILDING_THREADING_CORE_RENDER_ENGINE_NO_IMPORT

#endif  // THREADING_CORE_RENDER_ENGINE_NO_IMPORT_H