// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
// 
// “˝«Ê∞Ê±æ£∫0.3.0.0 (2020/05/11 21:28)

#ifndef THREADING_CORE_RENDER_ENGINE_NO_IMPORT_H
#define THREADING_CORE_RENDER_ENGINE_NO_IMPORT_H

#include "Framework/Helper/UserMacro.h"

#ifndef BUILDING_THREADING_CORE_RENDER_ENGINE_NO_IMPORT
	#define BUILDING_THREADING_CORE_RENDER_ENGINE_NO_IMPORT
#endif // BUILDING_THREADING_CORE_RENDER_ENGINE_NO_IMPORT

#endif // THREADING_CORE_RENDER_ENGINE_NO_IMPORT_H