// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
// 
// “˝«Ê∞Ê±æ£∫0.3.0.0 (2020/05/11 21:29)

#ifndef THREADING_CORE_RENDER_ENGINE_DLL_H
#define THREADING_CORE_RENDER_ENGINE_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Framework/Helper/UserMacro.h"

#if defined(BUILDING_THREADING_CORE_RENDER_ENGINE_NO_IMPORT) || defined(BUILDING_STATIC)

	#define THREADING_CORE_RENDER_ENGINE_DEFAULT_DECLARE
	#define THREADING_CORE_RENDER_ENGINE_HIDDEN_DECLARE 
	#define THREADING_CORE_RENDER_ENGINE_VISIBLE

#else // !defined(BUILDING_THREADING_CORE_RENDER_ENGINE_NO_IMPORT) && !defined(BUILDING_STATIC)

	#if defined(BUILDING_THREADING_CORE_RENDER_ENGINE_EXPORT)

		#define THREADING_CORE_RENDER_ENGINE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
		#define THREADING_CORE_RENDER_ENGINE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

	#else // !defined(BUILDING_THREADING_CORE_RENDER_ENGINE_EXPORT)

		#define THREADING_CORE_RENDER_ENGINE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
		#define THREADING_CORE_RENDER_ENGINE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

	#endif // BUILDING_THREADING_CORE_RENDER_ENGINE_EXPORT

	#define THREADING_CORE_RENDER_ENGINE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_THREADING_CORE_RENDER_ENGINE_NO_IMPORT) || defined(BUILDING_STATIC)

#endif // THREADING_CORE_RENDER_ENGINE_DLL_H