// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 引擎版本：0.0.2.0 (2019/12/30 10:15)

#ifndef THREADING_CORE_RENDER_ENGINE_IMPORT_H
#define THREADING_CORE_RENDER_ENGINE_IMPORT_H

#include "Framework/Macro/UserMacro.h"

#ifndef BUILDING_THREADING_CORE_RENDER_ENGINE_IMPORT
  #define BUILDING_THREADING_CORE_RENDER_ENGINE_IMPORT
#endif // BUILDING_THREADING_CORE_RENDER_ENGINE_IMPORT

#endif // THREADING_CORE_RENDER_ENGINE_IMPORT_H