///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.3 (2021/05/08 21:51)

#ifndef PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_MACRO_USER_MACRO_H
#define PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_MACRO_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_ClOSE_BEGIN (0x01)

#define CLOSE_USE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS (PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_ClOSE_BEGIN)

#define PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_ClOSE_END CLOSE_USE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS

#define CLOSE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_MAX ((PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_CLOSE 0x00

static_assert(0 <= COMPILE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_CLOSE, "COMPILE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_CLOSE <= CLOSE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_MAX, "COMPILE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_CLOSE Must be less than or equal CLOSE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_MAX.");

#if !defined(COMPILE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_CLOSE) || (COMPILE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_CLOSE & CLOSE_USE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS) != CLOSE_USE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS

#endif  // !defined(COMPILE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_CLOSE) || (COMPILE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_CLOSE & CLOSE_USE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS) != CLOSE_USE_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_STATIC
#endif  // BUILDING_STATIC

#endif  // PROGRAMMING_APPLICATIONS_FOR_MICROSOFT_WINDOWS_MACRO_USER_MACRO_H
