///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	版本：0.9.1.5 (2023/09/23 14:23)

#ifndef CORE_TOOLS_TEXT_PARSING_H
#define CORE_TOOLS_TEXT_PARSING_H

#include "CSV/BatchConversionCSV.h"
#include "CSV/BatchConversionCode.h"
#include "CSV/CSVContent.h"
#include "CSV/CSVGenerate.h"
#include "CSV/CSVHead.h"
#include "CSV/CSVRow.h"
#include "CSV/CSVTotalGenerate.h"
#include "CSV/CSVTypeConversion.h"
#include "CSV/DataTypeDescribe.h"
#include "CSV/ExcelConversionCSV.h" 
#include "SimpleCSV/AppProperties.h"
#include "SimpleCSV/Cell.h"
#include "SimpleCSV/CellIterator.h"
#include "SimpleCSV/CellRange.h"
#include "SimpleCSV/CellReference.h"
#include "SimpleCSV/CellValue.h"
#include "SimpleCSV/CellValueProxy.h"
#include "SimpleCSV/Color.h"
#include "SimpleCSV/Column.h"
#include "SimpleCSV/CommandQuery/CommandAddChartSheet.h"
#include "SimpleCSV/CommandQuery/CommandAddSharedStrings.h"
#include "SimpleCSV/CommandQuery/CommandAddWorksheet.h"
#include "SimpleCSV/CommandQuery/CommandCloneSheet.h"
#include "SimpleCSV/CommandQuery/CommandDeleteSheet.h"
#include "SimpleCSV/CommandQuery/CommandResetCalcChain.h"
#include "SimpleCSV/CommandQuery/CommandSetSheetColor.h"
#include "SimpleCSV/CommandQuery/CommandSetSheetIndex.h"
#include "SimpleCSV/CommandQuery/CommandSetSheetName.h"
#include "SimpleCSV/CommandQuery/CommandSetSheetVisibility.h"
#include "SimpleCSV/CommandQuery/QuerySharedStrings.h"
#include "SimpleCSV/CommandQuery/QuerySheetId.h"
#include "SimpleCSV/CommandQuery/QuerySheetIndex.h"
#include "SimpleCSV/CommandQuery/QuerySheetName.h"
#include "SimpleCSV/CommandQuery/QuerySheetRelsId.h"
#include "SimpleCSV/CommandQuery/QuerySheetRelsTarget.h"
#include "SimpleCSV/CommandQuery/QuerySheetType.h"
#include "SimpleCSV/CommandQuery/QuerySheetVisibility.h"
#include "SimpleCSV/CommandQuery/QueryXmlData.h"
#include "SimpleCSV/ContentItem.h"
#include "SimpleCSV/ContentTypes.h"
#include "SimpleCSV/Document.h"
#include "SimpleCSV/Properties.h"
#include "SimpleCSV/RelationshipItem.h"
#include "SimpleCSV/Relationships.h"
#include "SimpleCSV/Row.h"
#include "SimpleCSV/RowDataIterator.h"
#include "SimpleCSV/RowDataProxy.h"
#include "SimpleCSV/RowDataRange.h"
#include "SimpleCSV/RowRange.h"
#include "SimpleCSV/SharedStrings.h"
#include "SimpleCSV/SheetBase.h"
#include "SimpleCSV/SimpleCSVException.h"
#include "SimpleCSV/Workbook.h"
#include "SimpleCSV/Worksheet.h"
#include "SimpleCSV/XmlData.h"
#include "SimpleCSV/XmlFile.h"
#include "SimpleZip/ZipArchive.h"
#include "SimpleZip/ZipEntry.h"
#include "Data/IntVector2.h"
#include "Data/IntVector3.h"
#include "Data/IntVector4.h"
#include "Data/Vector2.h"
#include "Data/Vector3.h"
#include "Data/Vector4.h"

#endif  // CORE_TOOLS_TEXT_PARSING_H