// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.0.3 (2019/10/02 0:20)

#ifndef GLEW_LIB_EXAMPLE_DLL_H
#define GLEW_LIB_EXAMPLE_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(GLEW_LIB_EXAMPLE_NO_IMPORT) || defined(BUILDING_GLEW_LIB_EXAMPLE_STATIC)

  #define GLEW_LIB_EXAMPLE_DEFAULT_DECLARE
  #define GLEW_LIB_EXAMPLE_HIDDEN_DECLARE
  #define GLEW_LIB_EXAMPLE_VISIBLE

#else // !defined(GLEW_LIB_EXAMPLE_NO_IMPORT) && !defined(GLEW_LIB_EXAMPLE_STATIC)

   #if defined(GLEW_LIB_EXAMPLE_EXPORT)
 
        #define GLEW_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define GLEW_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(GLEW_LIB_EXAMPLE_EXPORT)

		#define GLEW_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define GLEW_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // GLEW_LIB_EXAMPLE_EXPORT

   #define GLEW_LIB_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(GLEW_LIB_EXAMPLE_NO_IMPORT) || defined(GLEW_LIB_EXAMPLE_STATIC)

#endif // GLEW_LIB_EXAMPLE_DLL_H
