///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.3 (2021/09/08 21:15)

#ifndef THE_SOCKETS_NETWORKING_API_DLL_H
#define THE_SOCKETS_NETWORKING_API_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_THE_SOCKETS_NETWORKING_API_NO_IMPORT) || defined(BUILDING_THE_SOCKETS_NETWORKING_API_STATIC)

    #define THE_SOCKETS_NETWORKING_API_DEFAULT_DECLARE
    #define THE_SOCKETS_NETWORKING_API_VISIBLE

    #if defined(BUILDING_THE_SOCKETS_NETWORKING_API_EXPORT)

        #define THE_SOCKETS_NETWORKING_API_HIDDEN_DECLARE

    #else  // !defined(BUILDING_THE_SOCKETS_NETWORKING_API_EXPORT)

        #define THE_SOCKETS_NETWORKING_API_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_THE_SOCKETS_NETWORKING_API_EXPORT

#else  // !defined(BUILDING_THE_SOCKETS_NETWORKING_API_NO_IMPORT) && !defined(BUILDING_THE_SOCKETS_NETWORKING_API_STATIC)

    #if defined(BUILDING_THE_SOCKETS_NETWORKING_API_EXPORT)

        #define THE_SOCKETS_NETWORKING_API_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define THE_SOCKETS_NETWORKING_API_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_THE_SOCKETS_NETWORKING_API_EXPORT)

        #define THE_SOCKETS_NETWORKING_API_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define THE_SOCKETS_NETWORKING_API_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_THE_SOCKETS_NETWORKING_API_EXPORT

    #define THE_SOCKETS_NETWORKING_API_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_THE_SOCKETS_NETWORKING_API_NO_IMPORT) || defined(BUILDING_THE_SOCKETS_NETWORKING_API_STATIC)

#endif  // THE_SOCKETS_NETWORKING_API_DLL_H
