// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 最后的霸王版本：0.0.0.0 (2019/10/10 18:01)

#ifndef BACKGROUND_CLIENT_MIDDLE_LAYER_EXPORT_H
#define BACKGROUND_CLIENT_MIDDLE_LAYER_EXPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_BACKGROUND_CLIENT_MIDDLE_LAYER_EXPORT
  #define BUILDING_BACKGROUND_CLIENT_MIDDLE_LAYER_EXPORT
#endif // BUILDING_BACKGROUND_CLIENT_MIDDLE_LAYER_EXPORT

#endif // BACKGROUND_CLIENT_MIDDLE_LAYER_EXPORT_H
