///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.4 (2021/06/06 21:47)

#ifndef MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_HELPER_USER_MACRO_H
#define MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_ClOSE_BEGIN (0x01)

#define CLOSE_USE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS (MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_ClOSE_BEGIN)

#define MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_ClOSE_END CLOSE_USE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS

#define CLOSE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_MAX ((MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_CLOSE 0x00

static_assert(0 <= COMPILE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_CLOSE, "COMPILE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_CLOSE <= CLOSE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_MAX, "COMPILE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_CLOSE Must be less than or equal CLOSE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_MAX.");

#if !defined(COMPILE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_CLOSE) || (COMPILE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_CLOSE & CLOSE_USE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS) != CLOSE_USE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS

#endif  // !defined(COMPILE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_CLOSE) || (COMPILE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_CLOSE & CLOSE_USE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS) != CLOSE_USE_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS

#ifdef BUILDING_STATIC
    #define BUILDING_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_STATIC
#endif  // BUILDING_STATIC

#endif  // MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_HELPER_USER_MACRO_H
