// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Resource/Protobuf/Proto/Player.proto

#include "Resource/Protobuf/Proto/Player.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Player {
PROTOBUF_CONSTEXPR PlayerRequest::PlayerRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.user_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerRequestDefaultTypeInternal() {}
  union {
    PlayerRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerRequestDefaultTypeInternal _PlayerRequest_default_instance_;
PROTOBUF_CONSTEXPR PlayerResponse::PlayerResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.user_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerResponseDefaultTypeInternal() {}
  union {
    PlayerResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerResponseDefaultTypeInternal _PlayerResponse_default_instance_;
}  // namespace Player
static ::_pb::Metadata file_level_metadata_Resource_2fProtobuf_2fProto_2fPlayer_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Resource_2fProtobuf_2fProto_2fPlayer_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Resource_2fProtobuf_2fProto_2fPlayer_2eproto = nullptr;

const uint32_t TableStruct_Resource_2fProtobuf_2fProto_2fPlayer_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Player::PlayerRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Player::PlayerRequest, _impl_.user_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Player::PlayerResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Player::PlayerResponse, _impl_.user_id_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Player::PlayerRequest)},
  { 7, -1, -1, sizeof(::Player::PlayerResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Player::_PlayerRequest_default_instance_._instance,
  &::Player::_PlayerResponse_default_instance_._instance,
};

const char descriptor_table_protodef_Resource_2fProtobuf_2fProto_2fPlayer_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n$Resource/Protobuf/Proto/Player.proto\022\006"
  "Player\" \n\rPlayerRequest\022\017\n\007user_id\030\001 \001(\005"
  "\"!\n\016PlayerResponse\022\017\n\007user_id\030\001 \001(\005b\006pro"
  "to3"
  ;
static ::_pbi::once_flag descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto = {
    false, false, 123, descriptor_table_protodef_Resource_2fProtobuf_2fProto_2fPlayer_2eproto,
    "Resource/Protobuf/Proto/Player.proto",
    &descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_Resource_2fProtobuf_2fProto_2fPlayer_2eproto::offsets,
    file_level_metadata_Resource_2fProtobuf_2fProto_2fPlayer_2eproto, file_level_enum_descriptors_Resource_2fProtobuf_2fProto_2fPlayer_2eproto,
    file_level_service_descriptors_Resource_2fProtobuf_2fProto_2fPlayer_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto_getter() {
  return &descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Resource_2fProtobuf_2fProto_2fPlayer_2eproto(&descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto);
namespace Player {

// ===================================================================

class PlayerRequest::_Internal {
 public:
};

PlayerRequest::PlayerRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Player.PlayerRequest)
}
PlayerRequest::PlayerRequest(const PlayerRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.user_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.user_id_ = from._impl_.user_id_;
  // @@protoc_insertion_point(copy_constructor:Player.PlayerRequest)
}

inline void PlayerRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.user_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PlayerRequest::~PlayerRequest() {
  // @@protoc_insertion_point(destructor:Player.PlayerRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PlayerRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Player.PlayerRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 user_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Player.PlayerRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 user_id = 1;
  if (this->_internal_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_user_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Player.PlayerRequest)
  return target;
}

size_t PlayerRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Player.PlayerRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 user_id = 1;
  if (this->_internal_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_user_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerRequest::GetClassData() const { return &_class_data_; }


void PlayerRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerRequest*>(&to_msg);
  auto& from = static_cast<const PlayerRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Player.PlayerRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_user_id() != 0) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerRequest::CopyFrom(const PlayerRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Player.PlayerRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerRequest::IsInitialized() const {
  return true;
}

void PlayerRequest::InternalSwap(PlayerRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.user_id_, other->_impl_.user_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto_getter, &descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto_once,
      file_level_metadata_Resource_2fProtobuf_2fProto_2fPlayer_2eproto[0]);
}

// ===================================================================

class PlayerResponse::_Internal {
 public:
};

PlayerResponse::PlayerResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Player.PlayerResponse)
}
PlayerResponse::PlayerResponse(const PlayerResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.user_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.user_id_ = from._impl_.user_id_;
  // @@protoc_insertion_point(copy_constructor:Player.PlayerResponse)
}

inline void PlayerResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.user_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PlayerResponse::~PlayerResponse() {
  // @@protoc_insertion_point(destructor:Player.PlayerResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PlayerResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Player.PlayerResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 user_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Player.PlayerResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 user_id = 1;
  if (this->_internal_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_user_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Player.PlayerResponse)
  return target;
}

size_t PlayerResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Player.PlayerResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 user_id = 1;
  if (this->_internal_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_user_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerResponse::GetClassData() const { return &_class_data_; }


void PlayerResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerResponse*>(&to_msg);
  auto& from = static_cast<const PlayerResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Player.PlayerResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_user_id() != 0) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerResponse::CopyFrom(const PlayerResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Player.PlayerResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerResponse::IsInitialized() const {
  return true;
}

void PlayerResponse::InternalSwap(PlayerResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.user_id_, other->_impl_.user_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto_getter, &descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto_once,
      file_level_metadata_Resource_2fProtobuf_2fProto_2fPlayer_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Player
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Player::PlayerRequest*
Arena::CreateMaybeMessage< ::Player::PlayerRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Player::PlayerRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::Player::PlayerResponse*
Arena::CreateMaybeMessage< ::Player::PlayerResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Player::PlayerResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
