// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Resource/Protobuf/Proto/Player.proto
// Protobuf C++ Version: 6.31.1

#include "Resource/Protobuf/Proto/Player.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Player {

inline constexpr PlayerResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        user_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PlayerResponse::PlayerResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PlayerResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlayerResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerResponseDefaultTypeInternal() {}
  union {
    PlayerResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerResponseDefaultTypeInternal _PlayerResponse_default_instance_;

inline constexpr PlayerRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        user_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PlayerRequest::PlayerRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PlayerRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlayerRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerRequestDefaultTypeInternal() {}
  union {
    PlayerRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerRequestDefaultTypeInternal _PlayerRequest_default_instance_;
}  // namespace Player
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_Resource_2fProtobuf_2fProto_2fPlayer_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_Resource_2fProtobuf_2fProto_2fPlayer_2eproto = nullptr;
const ::uint32_t
    TableStruct_Resource_2fProtobuf_2fProto_2fPlayer_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Player::PlayerRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Player::PlayerRequest, _impl_.user_id_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Player::PlayerResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Player::PlayerResponse, _impl_.user_id_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Player::PlayerRequest)},
        {5, sizeof(::Player::PlayerResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Player::_PlayerRequest_default_instance_._instance,
    &::Player::_PlayerResponse_default_instance_._instance,
};
const char descriptor_table_protodef_Resource_2fProtobuf_2fProto_2fPlayer_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n$Resource/Protobuf/Proto/Player.proto\022\006"
    "Player\" \n\rPlayerRequest\022\017\n\007user_id\030\001 \001(\005"
    "\"!\n\016PlayerResponse\022\017\n\007user_id\030\001 \001(\005b\006pro"
    "to3"
};
static ::absl::once_flag descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto = {
    false,
    false,
    123,
    descriptor_table_protodef_Resource_2fProtobuf_2fProto_2fPlayer_2eproto,
    "Resource/Protobuf/Proto/Player.proto",
    &descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_Resource_2fProtobuf_2fProto_2fPlayer_2eproto::offsets,
    file_level_enum_descriptors_Resource_2fProtobuf_2fProto_2fPlayer_2eproto,
    file_level_service_descriptors_Resource_2fProtobuf_2fProto_2fPlayer_2eproto,
};
namespace Player {
// ===================================================================

class PlayerRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PlayerRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PlayerRequest, _impl_._has_bits_);
};

PlayerRequest::PlayerRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlayerRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Player.PlayerRequest)
}
PlayerRequest::PlayerRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PlayerRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlayerRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PlayerRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PlayerRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.user_id_ = {};
}
PlayerRequest::~PlayerRequest() {
  // @@protoc_insertion_point(destructor:Player.PlayerRequest)
  SharedDtor(*this);
}
inline void PlayerRequest::SharedDtor(MessageLite& self) {
  PlayerRequest& this_ = static_cast<PlayerRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PlayerRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PlayerRequest(arena);
}
constexpr auto PlayerRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PlayerRequest),
                                            alignof(PlayerRequest));
}
constexpr auto PlayerRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PlayerRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PlayerRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PlayerRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PlayerRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PlayerRequest>(), &PlayerRequest::ByteSizeLong,
              &PlayerRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PlayerRequest, _impl_._cached_size_),
          false,
      },
      &PlayerRequest::kDescriptorMethods,
      &descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PlayerRequest_class_data_ =
        PlayerRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PlayerRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PlayerRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PlayerRequest_class_data_.tc_table);
  return PlayerRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
PlayerRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PlayerRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PlayerRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Player::PlayerRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 user_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PlayerRequest, _impl_.user_id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(PlayerRequest, _impl_.user_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 user_id = 1;
    {PROTOBUF_FIELD_OFFSET(PlayerRequest, _impl_.user_id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PlayerRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Player.PlayerRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PlayerRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PlayerRequest& this_ = static_cast<const PlayerRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PlayerRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PlayerRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:Player.PlayerRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 user_id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_user_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_user_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Player.PlayerRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PlayerRequest::ByteSizeLong(const MessageLite& base) {
  const PlayerRequest& this_ = static_cast<const PlayerRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PlayerRequest::ByteSizeLong() const {
  const PlayerRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Player.PlayerRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 user_id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_user_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_user_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PlayerRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PlayerRequest*>(&to_msg);
  auto& from = static_cast<const PlayerRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Player.PlayerRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_user_id() != 0) {
      _this->_impl_.user_id_ = from._impl_.user_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerRequest::CopyFrom(const PlayerRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Player.PlayerRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PlayerRequest::InternalSwap(PlayerRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.user_id_, other->_impl_.user_id_);
}

::google::protobuf::Metadata PlayerRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PlayerResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PlayerResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PlayerResponse, _impl_._has_bits_);
};

PlayerResponse::PlayerResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlayerResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Player.PlayerResponse)
}
PlayerResponse::PlayerResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PlayerResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlayerResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PlayerResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PlayerResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.user_id_ = {};
}
PlayerResponse::~PlayerResponse() {
  // @@protoc_insertion_point(destructor:Player.PlayerResponse)
  SharedDtor(*this);
}
inline void PlayerResponse::SharedDtor(MessageLite& self) {
  PlayerResponse& this_ = static_cast<PlayerResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PlayerResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PlayerResponse(arena);
}
constexpr auto PlayerResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PlayerResponse),
                                            alignof(PlayerResponse));
}
constexpr auto PlayerResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PlayerResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PlayerResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PlayerResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PlayerResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PlayerResponse>(), &PlayerResponse::ByteSizeLong,
              &PlayerResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PlayerResponse, _impl_._cached_size_),
          false,
      },
      &PlayerResponse::kDescriptorMethods,
      &descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PlayerResponse_class_data_ =
        PlayerResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PlayerResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PlayerResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PlayerResponse_class_data_.tc_table);
  return PlayerResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
PlayerResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PlayerResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PlayerResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Player::PlayerResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 user_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PlayerResponse, _impl_.user_id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(PlayerResponse, _impl_.user_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 user_id = 1;
    {PROTOBUF_FIELD_OFFSET(PlayerResponse, _impl_.user_id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PlayerResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Player.PlayerResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PlayerResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PlayerResponse& this_ = static_cast<const PlayerResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PlayerResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PlayerResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:Player.PlayerResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 user_id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_user_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_user_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Player.PlayerResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PlayerResponse::ByteSizeLong(const MessageLite& base) {
  const PlayerResponse& this_ = static_cast<const PlayerResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PlayerResponse::ByteSizeLong() const {
  const PlayerResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Player.PlayerResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 user_id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_user_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_user_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PlayerResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PlayerResponse*>(&to_msg);
  auto& from = static_cast<const PlayerResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Player.PlayerResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_user_id() != 0) {
      _this->_impl_.user_id_ = from._impl_.user_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerResponse::CopyFrom(const PlayerResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Player.PlayerResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PlayerResponse::InternalSwap(PlayerResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.user_id_, other->_impl_.user_id_);
}

::google::protobuf::Metadata PlayerResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Player
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_Resource_2fProtobuf_2fProto_2fPlayer_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
