///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.1 (2021/02/16 17:46)

#ifndef EFFECTIVE_STL_HELPER_USER_MACRO_H
#define EFFECTIVE_STL_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define EFFECTIVE_STL_ClOSE_BEGIN (0x01)

#define CLOSE_USE_EFFECTIVE_STL (EFFECTIVE_STL_ClOSE_BEGIN)

#define EFFECTIVE_STL_ClOSE_END CLOSE_USE_EFFECTIVE_STL

#define CLOSE_EFFECTIVE_STL_MAX ((EFFECTIVE_STL_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_EFFECTIVE_STL_CLOSE 0x00

static_assert(0 <= COMPILE_EFFECTIVE_STL_CLOSE, "COMPILE_EFFECTIVE_STL_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_EFFECTIVE_STL_CLOSE <= CLOSE_EFFECTIVE_STL_MAX, "COMPILE_EFFECTIVE_STL_CLOSE Must be less than or equal CLOSE_EFFECTIVE_STL_MAX.");

#if !defined(COMPILE_EFFECTIVE_STL_CLOSE) || (COMPILE_EFFECTIVE_STL_CLOSE & CLOSE_USE_EFFECTIVE_STL) != CLOSE_USE_EFFECTIVE_STL

#endif  // !defined(COMPILE_EFFECTIVE_STL_CLOSE) || (COMPILE_EFFECTIVE_STL_CLOSE & CLOSE_USE_EFFECTIVE_STL) != CLOSE_USE_EFFECTIVE_STL

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_EFFECTIVE_STL_STATIC
#endif  // BUILDING_STATIC

#endif  // EFFECTIVE_STL_HELPER_USER_MACRO_H
