// Copyright (c) 2011-2020
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
//
// 最后的霸王版本：0.0.2.0 (2020/01/09 22:36)

#ifndef GAME_CLIENT_MIDDLE_LAYER_EXPORT_H
#define GAME_CLIENT_MIDDLE_LAYER_EXPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_GAME_CLIENT_MIDDLE_LAYER_EXPORT
  #define BUILDING_GAME_CLIENT_MIDDLE_LAYER_EXPORT
#endif // BUILDING_GAME_CLIENT_MIDDLE_LAYER_EXPORT

#endif // GAME_CLIENT_MIDDLE_LAYER_EXPORT_H