// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 最后的霸王版本：0.0.0.1 (2019/10/12 13:13)

#ifndef WORLD_SERVER_MIDDLE_LAYER_IMPORT_H
#define WORLD_SERVER_MIDDLE_LAYER_IMPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_WORLD_SERVER_MIDDLE_LAYER_IMPORT
  #define BUILDING_WORLD_SERVER_MIDDLE_LAYER_IMPORT
#endif // BUILDING_WORLD_SERVER_MIDDLE_LAYER_IMPORT

#endif // WORLD_SERVER_MIDDLE_LAYER_IMPORT_H
