// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
// 
// “˝«Ê∞Ê±æ£∫0.0.0.3 (2019/07/17 10:19)

#ifndef RESOURCE_MANAGER_DLL_H
#define RESOURCE_MANAGER_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Helper/UserMacro.h"

#if defined(BUILDING_RESOURCE_MANAGER_NO_IMPORT) || defined(BUILDING_RESOURCE_MANAGER_STATIC)

  #define RESOURCE_MANAGER_DEFAULT_DECLARE
  #define RESOURCE_MANAGER_HIDDEN_DECLARE
  #define RESOURCE_MANAGER_VISIBLE

#else // !defined(BUILDING_RESOURCE_MANAGER_NO_IMPORT) && !defined(BUILDING_RESOURCE_MANAGER_STATIC)
 
   #if defined(BUILDING_RESOURCE_MANAGER_EXPORT)
 
        #define RESOURCE_MANAGER_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define RESOURCE_MANAGER_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_RESOURCE_MANAGER_EXPORT)

		#define RESOURCE_MANAGER_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define RESOURCE_MANAGER_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_RESOURCE_MANAGER_EXPORT

   #define RESOURCE_MANAGER_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_RESOURCE_MANAGER_NO_IMPORT) || defined(BUILDING_RESOURCE_MANAGER_STATIC)

#endif // RESOURCE_MANAGER_DLL_H