// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.1.0.3 (2020/05/01 14:10)

#ifndef FRAMEWORK_EXAMPLE_DLL_DLL_H
#define FRAMEWORK_EXAMPLE_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Helper/UserMacro.h"

#if defined(BUILDING_FRAMEWORK_EXAMPLE_NO_IMPORT) || defined(BUILDING_FRAMEWORK_EXAMPLE_STATIC)

  #define FRAMEWORK_EXAMPLE_DEFAULT_DECLARE
  #define FRAMEWORK_EXAMPLE_HIDDEN_DECLARE
  #define FRAMEWORK_EXAMPLE_VISIBLE

#else // !defined(BUILDING_FRAMEWORK_EXAMPLE_NO_IMPORT) && !defined(BUILDING_FRAMEWORK_EXAMPLE_STATIC)

   #if defined(BUILDING_FRAMEWORK_EXAMPLE_EXPORT)
 
        #define FRAMEWORK_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define FRAMEWORK_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_FRAMEWORK_EXAMPLE_EXPORT)

		#define FRAMEWORK_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define FRAMEWORK_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_FRAMEWORK_EXAMPLE_EXPORT

   #define FRAMEWORK_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_FRAMEWORK_EXAMPLE_NO_IMPORT) || defined(BUILDING_FRAMEWORK_EXAMPLE_STATIC)

#endif // FRAMEWORK_EXAMPLE_DLL_DLL_H
