///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.2 (2021/03/28 12:58)

#ifndef ALGORITHMIC_PUZZLES_DLL_H
#define ALGORITHMIC_PUZZLES_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_ALGORITHMIC_PUZZLES_NO_IMPORT) || defined(BUILDING_ALGORITHMIC_PUZZLES_STATIC)

    #define ALGORITHMIC_PUZZLES_DEFAULT_DECLARE
    #define ALGORITHMIC_PUZZLES_VISIBLE

    #if defined(BUILDING_ALGORITHMIC_PUZZLES_EXPORT)

        #define ALGORITHMIC_PUZZLES_HIDDEN_DECLARE

    #else  // !defined(BUILDING_ALGORITHMIC_PUZZLES_EXPORT)

        #define ALGORITHMIC_PUZZLES_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_ALGORITHMIC_PUZZLES_EXPORT

#else  // !defined(BUILDING_ALGORITHMIC_PUZZLES_NO_IMPORT) && !defined(BUILDING_ALGORITHMIC_PUZZLES_STATIC)

    #if defined(BUILDING_ALGORITHMIC_PUZZLES_EXPORT)

        #define ALGORITHMIC_PUZZLES_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define ALGORITHMIC_PUZZLES_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_ALGORITHMIC_PUZZLES_EXPORT)

        #define ALGORITHMIC_PUZZLES_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define ALGORITHMIC_PUZZLES_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_ALGORITHMIC_PUZZLES_EXPORT

    #define ALGORITHMIC_PUZZLES_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_ALGORITHMIC_PUZZLES_NO_IMPORT) || defined(BUILDING_ALGORITHMIC_PUZZLES_STATIC)

#endif  // ALGORITHMIC_PUZZLES_DLL_H
