//	Copyright (c) 2011-2020
//	Threading Core Render Engine
//
//	作者：彭武阳，彭晔恩，彭晔泽
//	联系作者：94458936@qq.com
//
//	标准：std:c++17
//	引擎版本：0.5.0.0 (2020/08/23 23:58)

#ifndef MATHEMATICS_RATIONAL_FLOATING_POINT_ANALYSIS_DETAIL_H
#define MATHEMATICS_RATIONAL_FLOATING_POINT_ANALYSIS_DETAIL_H

#include "FloatingPointAnalysis.h"

#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_FLOATING_POINT_ANALYSIS_ACHIEVE)

    #include "FloatingPointAnalysisAchieve.h"

#endif  //  !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_FLOATING_POINT_ANALYSIS_ACHIEVE)

#endif  // MATHEMATICS_RATIONAL_FLOATING_POINT_ANALYSIS_DETAIL_H
