/// Copyright (c) 2010-2024
/// Threading Core Render Engine
///
/// 作者：彭武阳，彭晔恩，彭晔泽
/// 联系作者：94458936@qq.com
///
/// 标准：std:c++20
/// 版本：1.0.0.7 (2024/03/05 19:36)

#ifndef MATHEMATICS_RATIONAL_RATIONAL_U_INTEGER_ARITHMETIC_LOGIC_UNIT_32_DETAIL_H
#define MATHEMATICS_RATIONAL_RATIONAL_U_INTEGER_ARITHMETIC_LOGIC_UNIT_32_DETAIL_H

#include "UIntegerArithmeticLogicUnit32.h"

#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_U_INTEGER_ARITHMETIC_LOGIC_UNIT_32_ACHIEVE)

    #include "UIntegerArithmeticLogicUnit32Achieve.h"

#endif  //  !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_U_INTEGER_ARITHMETIC_LOGIC_UNIT_32_ACHIEVE)

#endif  // MATHEMATICS_RATIONAL_RATIONAL_U_INTEGER_ARITHMETIC_LOGIC_UNIT_32_DETAIL_H
