///	Copyright (c) 2010-2022
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	引擎辅助版本：0.8.0.10 (2022/07/11 18:43)

#ifndef ARTIFICIAL_INTELLEGENCE_EXAMPLE_IMPORT_H
#define ARTIFICIAL_INTELLEGENCE_EXAMPLE_IMPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_IMPORT
    #define BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_IMPORT
#endif  // BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_IMPORT

#endif  // ARTIFICIAL_INTELLEGENCE_EXAMPLE_IMPORT_H
