// Copyright (c) 2011-2020
// Threading Core Render Engine
// „ч’я£Ї≈нќд—ф£ђ≈нк ґч£ђ≈нк ‘у
//
// “э«жЄ®÷ъ∞ж±Њ£Ї0.0.2.2 (2020/01/27 1:15)

#ifndef ARTIFICIAL_INTELLEGENCE_EXAMPLE_NO_IMPORT_H
#define ARTIFICIAL_INTELLEGENCE_EXAMPLE_NO_IMPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_NO_IMPORT
  #define BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_NO_IMPORT
#endif // BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_NO_IMPORT

#endif // ARTIFICIAL_INTELLEGENCE_EXAMPLE_NO_IMPORT_H
