///	Copyright (c) 2010-2022
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	引擎辅助版本：0.8.0.10 (2022/07/11 18:43)

#ifndef ARTIFICIAL_INTELLEGENCE_EXAMPLE_DLL_DLL_H
#define ARTIFICIAL_INTELLEGENCE_EXAMPLE_DLL_DLL_H

#include "Macro/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_NO_IMPORT) || defined(BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_STATIC)

    #define ARTIFICIAL_INTELLEGENCE_EXAMPLE_DEFAULT_DECLARE
    #define ARTIFICIAL_INTELLEGENCE_EXAMPLE_HIDDEN_DECLARE
    #define ARTIFICIAL_INTELLEGENCE_EXAMPLE_VISIBLE

#else  // !defined(BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_NO_IMPORT) && !defined(BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_STATIC)

    #if defined(BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_EXPORT)

        #define ARTIFICIAL_INTELLEGENCE_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define ARTIFICIAL_INTELLEGENCE_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_EXPORT)

        #define ARTIFICIAL_INTELLEGENCE_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define ARTIFICIAL_INTELLEGENCE_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_EXPORT

    #define ARTIFICIAL_INTELLEGENCE_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_NO_IMPORT) || defined(BUILDING_ARTIFICIAL_INTELLEGENCE_EXAMPLE_STATIC)

#endif  // ARTIFICIAL_INTELLEGENCE_EXAMPLE_DLL_DLL_H
