// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 最后的霸王版本：0.0.0.0 (2019/10/10 17:49)

#ifndef BACKGROUND_CLIENT_CORE_IMPORT_H
#define BACKGROUND_CLIENT_CORE_IMPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_BACKGROUND_CLIENT_CORE_IMPORT
  #define BUILDING_BACKGROUND_CLIENT_CORE_IMPORT
#endif // BUILDING_BACKGROUND_CLIENT_CORE_IMPORT

#endif // BACKGROUND_CLIENT_CORE_IMPORT_H
