// Copyright (c) 2011-2019
// Threading Core Render Engine
// „ч’я£Ї≈нќд—ф£ђ≈нк ґч£ђ≈нк ‘у
//
// “э«жЄ®÷ъ∞ж±Њ£Ї0.0.0.3 (2019/10/02 14:28)

#ifndef VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_IMPORT_H
#define VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_IMPORT_H

#include "Macro/UserMacro.h"

#ifndef VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_IMPORT
  #define VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_IMPORT
#endif // VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_IMPORT

#endif // VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_IMPORT_H
