// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.0.3 (2019/10/02 14:29)

#ifndef VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_DLL_H
#define VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_NO_IMPORT) || defined(BUILDING_VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_STATIC)

  #define VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_DEFAULT_DECLARE
  #define VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_HIDDEN_DECLARE
  #define VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_VISIBLE

#else // !defined(VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_NO_IMPORT) && !defined(VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_STATIC)

   #if defined(VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_EXPORT)
 
        #define VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_EXPORT)

		#define VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_EXPORT

   #define VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_NO_IMPORT) || defined(VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_STATIC)

#endif // VISUAL_LEAK_DETECTOR_LIB_EXAMPLE_DLL_H
