///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.2 (2021/03/28 12:58)

#ifndef APPLIED_CRYPTOGRAPHY_DLL_H
#define APPLIED_CRYPTOGRAPHY_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_APPLIED_CRYPTOGRAPHY_NO_IMPORT) || defined(BUILDING_APPLIED_CRYPTOGRAPHY_STATIC)

    #define APPLIED_CRYPTOGRAPHY_DEFAULT_DECLARE
    #define APPLIED_CRYPTOGRAPHY_VISIBLE

    #if defined(BUILDING_APPLIED_CRYPTOGRAPHY_EXPORT)

        #define APPLIED_CRYPTOGRAPHY_HIDDEN_DECLARE

    #else  // !defined(BUILDING_APPLIED_CRYPTOGRAPHY_EXPORT)

        #define APPLIED_CRYPTOGRAPHY_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_APPLIED_CRYPTOGRAPHY_EXPORT

#else  // !defined(BUILDING_APPLIED_CRYPTOGRAPHY_NO_IMPORT) && !defined(BUILDING_APPLIED_CRYPTOGRAPHY_STATIC)

    #if defined(BUILDING_APPLIED_CRYPTOGRAPHY_EXPORT)

        #define APPLIED_CRYPTOGRAPHY_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define APPLIED_CRYPTOGRAPHY_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_APPLIED_CRYPTOGRAPHY_EXPORT)

        #define APPLIED_CRYPTOGRAPHY_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define APPLIED_CRYPTOGRAPHY_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_APPLIED_CRYPTOGRAPHY_EXPORT

    #define APPLIED_CRYPTOGRAPHY_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_APPLIED_CRYPTOGRAPHY_NO_IMPORT) || defined(BUILDING_APPLIED_CRYPTOGRAPHY_STATIC)

#endif  // APPLIED_CRYPTOGRAPHY_DLL_H
