///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.1 (2021/03/11 17:52)

#ifndef MODERN_CPP_DESIGN_DLL_H
#define MODERN_CPP_DESIGN_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_MODERN_CPP_DESIGN_NO_IMPORT) || defined(BUILDING_MODERN_CPP_DESIGN_STATIC)

    #define MODERN_CPP_DESIGN_DEFAULT_DECLARE
    #define MODERN_CPP_DESIGN_VISIBLE

    #if defined(BUILDING_MODERN_CPP_DESIGN_EXPORT)

        #define MODERN_CPP_DESIGN_HIDDEN_DECLARE

    #else  // !defined(BUILDING_MODERN_CPP_DESIGN_EXPORT)

        #define MODERN_CPP_DESIGN_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_MODERN_CPP_DESIGN_EXPORT

#else  // !defined(BUILDING_MODERN_CPP_DESIGN_NO_IMPORT) && !defined(BUILDING_MODERN_CPP_DESIGN_STATIC)

    #if defined(BUILDING_MODERN_CPP_DESIGN_EXPORT)

        #define MODERN_CPP_DESIGN_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define MODERN_CPP_DESIGN_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_MODERN_CPP_DESIGN_EXPORT)

        #define MODERN_CPP_DESIGN_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define MODERN_CPP_DESIGN_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_MODERN_CPP_DESIGN_EXPORT

    #define MODERN_CPP_DESIGN_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_MODERN_CPP_DESIGN_NO_IMPORT) || defined(BUILDING_MODERN_CPP_DESIGN_STATIC)

#endif  // MODERN_CPP_DESIGN_DLL_H
