///	Copyright (c) 2010-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.0 (2020/12/26 21:32)

#ifndef BEGINNING_CPP_17_HELPER_USER_MACRO_H
#define BEGINNING_CPP_17_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define BEGINNING_CPP_17_ClOSE_BEGIN (0x01)

#define CLOSE_USE_BEGINNING_CPP_17 (BEGINNING_CPP_17_ClOSE_BEGIN)

#define BEGINNING_CPP_17_ClOSE_END CLOSE_USE_BEGINNING_CPP_17

#define CLOSE_BEGINNING_CPP_17_MAX ((BEGINNING_CPP_17_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_BEGINNING_CPP_17_CLOSE 0x00

static_assert(0 <= COMPILE_BEGINNING_CPP_17_CLOSE, "COMPILE_BEGINNING_CPP_17_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_BEGINNING_CPP_17_CLOSE <= CLOSE_BEGINNING_CPP_17_MAX, "COMPILE_BEGINNING_CPP_17_CLOSE Must be less than or equal CLOSE_BEGINNING_CPP_17_MAX.");

#if !defined(COMPILE_BEGINNING_CPP_17_CLOSE) || (COMPILE_BEGINNING_CPP_17_CLOSE & CLOSE_USE_BEGINNING_CPP_17) != CLOSE_USE_BEGINNING_CPP_17

#endif  // !defined(COMPILE_BEGINNING_CPP_17_CLOSE) || (COMPILE_BEGINNING_CPP_17_CLOSE & CLOSE_USE_BEGINNING_CPP_17) != CLOSE_USE_BEGINNING_CPP_17

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_BEGINNING_CPP_17_STATIC
#endif  // BUILDING_STATIC

#endif  // BEGINNING_CPP_17_HELPER_USER_MACRO_H
