// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.1 (2020/01/12 1:46)

#ifndef LIB_EXAMPLE_TOOLSET_DLL_DLL_H
#define LIB_EXAMPLE_TOOLSET_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/Macro.h" 

#if defined(BUILDING_LIB_EXAMPLE_TOOLSET_NO_IMPORT) || defined(BUILDING_LIB_EXAMPLE_STATIC)

  #define LIB_EXAMPLE_TOOLSET_DEFAULT_DECLARE
  #define LIB_EXAMPLE_TOOLSET_HIDDEN_DECLARE
  #define LIB_EXAMPLE_TOOLSET_VISIBLE

#else // !defined(BUILDING_LIB_EXAMPLE_TOOLSET_NO_IMPORT) && !defined(BUILDING_LIB_EXAMPLE_STATIC)

   #if defined(BUILDING_LIB_EXAMPLE_TOOLSET_EXPORT)
 
        #define LIB_EXAMPLE_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define LIB_EXAMPLE_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_LIB_EXAMPLE_TOOLSET_EXPORT)

		#define LIB_EXAMPLE_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define LIB_EXAMPLE_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_LIB_EXAMPLE_TOOLSET_EXPORT

   #define LIB_EXAMPLE_TOOLSET_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_LIB_EXAMPLE_TOOLSET_NO_IMPORT) || defined(BUILDING_LIB_EXAMPLE_STATIC)

#endif // LIB_EXAMPLE_TOOLSET_DLL_DLL_H
