///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.3 (2021/09/08 21:15)

#ifndef INTERPROCESS_COMMUNICATIONS_HELPER_USER_MACRO_H
#define INTERPROCESS_COMMUNICATIONS_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define INTERPROCESS_COMMUNICATIONS_ClOSE_BEGIN (0x01)

#define CLOSE_USE_INTERPROCESS_COMMUNICATIONS (INTERPROCESS_COMMUNICATIONS_ClOSE_BEGIN)

#define INTERPROCESS_COMMUNICATIONS_ClOSE_END CLOSE_USE_INTERPROCESS_COMMUNICATIONS

#define CLOSE_INTERPROCESS_COMMUNICATIONS_MAX ((INTERPROCESS_COMMUNICATIONS_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_INTERPROCESS_COMMUNICATIONS_CLOSE 0x00

static_assert(0 <= COMPILE_INTERPROCESS_COMMUNICATIONS_CLOSE, "COMPILE_INTERPROCESS_COMMUNICATIONS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_INTERPROCESS_COMMUNICATIONS_CLOSE <= CLOSE_INTERPROCESS_COMMUNICATIONS_MAX, "COMPILE_INTERPROCESS_COMMUNICATIONS_CLOSE Must be less than or equal CLOSE_INTERPROCESS_COMMUNICATIONS_MAX.");

#if !defined(COMPILE_INTERPROCESS_COMMUNICATIONS_CLOSE) || (COMPILE_INTERPROCESS_COMMUNICATIONS_CLOSE & CLOSE_USE_INTERPROCESS_COMMUNICATIONS) != CLOSE_USE_INTERPROCESS_COMMUNICATIONS

#endif  // !defined(COMPILE_INTERPROCESS_COMMUNICATIONS_CLOSE) || (COMPILE_INTERPROCESS_COMMUNICATIONS_CLOSE & CLOSE_USE_INTERPROCESS_COMMUNICATIONS) != CLOSE_USE_INTERPROCESS_COMMUNICATIONS

#ifdef BUILDING_STATIC
    #define BUILDING_INTERPROCESS_COMMUNICATIONS_STATIC
#endif  // BUILDING_STATIC

#endif  // INTERPROCESS_COMMUNICATIONS_HELPER_USER_MACRO_H
