///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.0 (2021/02/20 0:15)

#ifndef MORE_EXCEPTIONAL_CPP_HELPER_USER_MACRO_H
#define MORE_EXCEPTIONAL_CPP_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define MORE_EXCEPTIONAL_CPP_ClOSE_BEGIN (0x01)

#define CLOSE_USE_MORE_EXCEPTIONAL_CPP (MORE_EXCEPTIONAL_CPP_ClOSE_BEGIN)

#define MORE_EXCEPTIONAL_CPP_ClOSE_END CLOSE_USE_MORE_EXCEPTIONAL_CPP

#define CLOSE_MORE_EXCEPTIONAL_CPP_MAX ((MORE_EXCEPTIONAL_CPP_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_MORE_EXCEPTIONAL_CPP_CLOSE 0x00

static_assert(0 <= COMPILE_MORE_EXCEPTIONAL_CPP_CLOSE, "COMPILE_MORE_EXCEPTIONAL_CPP_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_MORE_EXCEPTIONAL_CPP_CLOSE <= CLOSE_MORE_EXCEPTIONAL_CPP_MAX, "COMPILE_MORE_EXCEPTIONAL_CPP_CLOSE Must be less than or equal CLOSE_MORE_EXCEPTIONAL_CPP_MAX.");

#if !defined(COMPILE_MORE_EXCEPTIONAL_CPP_CLOSE) || (COMPILE_MORE_EXCEPTIONAL_CPP_CLOSE & CLOSE_USE_MORE_EXCEPTIONAL_CPP) != CLOSE_USE_MORE_EXCEPTIONAL_CPP

#endif  // !defined(COMPILE_MORE_EXCEPTIONAL_CPP_CLOSE) || (COMPILE_MORE_EXCEPTIONAL_CPP_CLOSE & CLOSE_USE_MORE_EXCEPTIONAL_CPP) != CLOSE_USE_MORE_EXCEPTIONAL_CPP

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_MORE_EXCEPTIONAL_CPP_STATIC
#endif  // BUILDING_STATIC

#endif  // MORE_EXCEPTIONAL_CPP_HELPER_USER_MACRO_H
