///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.7 (2021/12/06 21:22)

#ifndef OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_DLL_H
#define OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_NO_IMPORT) || defined(BUILDING_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_STATIC)

    #define OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_DEFAULT_DECLARE
    #define OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_VISIBLE

    #if defined(BUILDING_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_EXPORT)

        #define OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_HIDDEN_DECLARE

    #else  // !defined(BUILDING_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_EXPORT)

        #define OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_EXPORT

#else  // !defined(BUILDING_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_NO_IMPORT) && !defined(BUILDING_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_STATIC)

    #if defined(BUILDING_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_EXPORT)

        #define OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_EXPORT)

        #define OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_EXPORT

    #define OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_NO_IMPORT) || defined(BUILDING_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_STATIC)

#endif  // OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_DLL_H
