///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.1 (2021/01/01 14:25)

#ifndef C_AND_CPP_CODE_CAPSULES_HELPER_USER_MACRO_H
#define C_AND_CPP_CODE_CAPSULES_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define C_AND_CPP_CODE_CAPSULES_ClOSE_BEGIN (0x01)

#define CLOSE_USE_C_AND_CPP_CODE_CAPSULES (C_AND_CPP_CODE_CAPSULES_ClOSE_BEGIN)

#define C_AND_CPP_CODE_CAPSULES_ClOSE_END CLOSE_USE_C_AND_CPP_CODE_CAPSULES

#define CLOSE_C_AND_CPP_CODE_CAPSULES_MAX ((C_AND_CPP_CODE_CAPSULES_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_C_AND_CPP_CODE_CAPSULES_CLOSE 0x00

static_assert(0 <= COMPILE_C_AND_CPP_CODE_CAPSULES_CLOSE, "COMPILE_C_AND_CPP_CODE_CAPSULES_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_C_AND_CPP_CODE_CAPSULES_CLOSE <= CLOSE_C_AND_CPP_CODE_CAPSULES_MAX, "COMPILE_C_AND_CPP_CODE_CAPSULES_CLOSE Must be less than or equal CLOSE_C_AND_CPP_CODE_CAPSULES_MAX.");

#if !defined(COMPILE_C_AND_CPP_CODE_CAPSULES_CLOSE) || (COMPILE_C_AND_CPP_CODE_CAPSULES_CLOSE & CLOSE_USE_C_AND_CPP_CODE_CAPSULES) != CLOSE_USE_C_AND_CPP_CODE_CAPSULES

#endif  // !defined(COMPILE_C_AND_CPP_CODE_CAPSULES_CLOSE) || (COMPILE_C_AND_CPP_CODE_CAPSULES_CLOSE & CLOSE_USE_C_AND_CPP_CODE_CAPSULES) != CLOSE_USE_C_AND_CPP_CODE_CAPSULES

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_C_AND_CPP_CODE_CAPSULES_STATIC
#endif  // BUILDING_STATIC

#endif  // C_AND_CPP_CODE_CAPSULES_HELPER_USER_MACRO_H
