///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.1 (2021/02/09 14:57)

#ifndef UNDERSTANDING_THE_MACHINE_DLL_H
#define UNDERSTANDING_THE_MACHINE_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_UNDERSTANDING_THE_MACHINE_NO_IMPORT) || defined(BUILDING_UNDERSTANDING_THE_MACHINE_STATIC)

    #define UNDERSTANDING_THE_MACHINE_DEFAULT_DECLARE
    #define UNDERSTANDING_THE_MACHINE_HIDDEN_DECLARE
    #define UNDERSTANDING_THE_MACHINE_VISIBLE

#else  // !defined(BUILDING_UNDERSTANDING_THE_MACHINE_NO_IMPORT) && !defined(BUILDING_UNDERSTANDING_THE_MACHINE_STATIC)

    #if defined(BUILDING_UNDERSTANDING_THE_MACHINE_EXPORT)

        #define UNDERSTANDING_THE_MACHINE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define UNDERSTANDING_THE_MACHINE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_UNDERSTANDING_THE_MACHINE_EXPORT)

        #define UNDERSTANDING_THE_MACHINE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define UNDERSTANDING_THE_MACHINE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_UNDERSTANDING_THE_MACHINE_EXPORT

    #define UNDERSTANDING_THE_MACHINE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_UNDERSTANDING_THE_MACHINE_NO_IMPORT) || defined(BUILDING_UNDERSTANDING_THE_MACHINE_STATIC)

#endif  // UNDERSTANDING_THE_MACHINE_DLL_H
