///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.1 (2021/02/09 14:56)

#ifndef UNDERSTANDING_THE_MACHINE_NO_IMPORT_H
#define UNDERSTANDING_THE_MACHINE_NO_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_UNDERSTANDING_THE_MACHINE_NO_IMPORT
    #define BUILDING_UNDERSTANDING_THE_MACHINE_NO_IMPORT
#endif  // BUILDING_UNDERSTANDING_THE_MACHINE_NO_IMPORT

#endif  // UNDERSTANDING_THE_MACHINE_NO_IMPORT_H
