///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.1 (2021/08/01 21:08)

#ifndef NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_HELPER_USER_MACRO_H
#define NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_ClOSE_BEGIN (0x01)

#define CLOSE_USE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS (NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_ClOSE_BEGIN)

#define NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_ClOSE_END CLOSE_USE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS

#define CLOSE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_MAX ((NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_CLOSE 0x00

static_assert(0 <= COMPILE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_CLOSE, "COMPILE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_CLOSE <= CLOSE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_MAX, "COMPILE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_CLOSE Must be less than or equal CLOSE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_MAX.");

#if !defined(COMPILE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_CLOSE) || (COMPILE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_CLOSE & CLOSE_USE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS) != CLOSE_USE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS

#endif  // !defined(COMPILE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_CLOSE) || (COMPILE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_CLOSE & CLOSE_USE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS) != CLOSE_USE_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS

#ifdef BUILDING_STATIC
    #define BUILDING_NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_STATIC
#endif  // BUILDING_STATIC

#endif  // NETWORK_PROGRAMMING_FOR_MICROSOFT_WINDOWS_HELPER_USER_MACRO_H
