// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.0 (2020/01/07 22:18)

#ifndef RENDERING_TOOLSET_DLL_DLL_H
#define RENDERING_TOOLSET_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Rendering/Helper/UserMacro.h"

#if defined(BUILDING_RENDERING_TOOLSET_NO_IMPORT) || defined(BUILDING_RENDERING_STATIC)

  #define RENDERING_TOOLSET_DEFAULT_DECLARE
  #define RENDERING_TOOLSET_HIDDEN_DECLARE
  #define RENDERING_TOOLSET_VISIBLE

#else // !defined(BUILDING_RENDERING_TOOLSET_NO_IMPORT) && !defined(BUILDING_RENDERING_STATIC)

   #if defined(BUILDING_RENDERING_TOOLSET_EXPORT)
 
        #define RENDERING_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define RENDERING_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_RENDERING_TOOLSET_EXPORT)

		#define RENDERING_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define RENDERING_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_RENDERING_TOOLSET_EXPORT

   #define RENDERING_TOOLSET_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_RENDERING_TOOLSET_NO_IMPORT) || defined(BUILDING_RENDERING_STATIC)

#endif // RENDERING_TOOLSET_DLL_DLL_H
