// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 最后的霸王版本：0.0.0.1 (2019/10/12 09:37)

#ifndef FIGHTING_SERVER_CORE_DLL_H
#define FIGHTING_SERVER_CORE_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(BUILDING_FIGHTING_SERVER_CORE_NO_IMPORT)  || defined(BUILDING_FIGHTING_SERVER_CORE_STATIC)

  #define FIGHTING_SERVER_CORE_DEFAULT_DECLARE
  #define FIGHTING_SERVER_CORE_HIDDEN_DECLARE 
  #define FIGHTING_SERVER_CORE_VISIBLE

#else // !defined(BUILDING_FIGHTING_SERVER_CORE_NO_IMPORT) && !defined(BUILDING_FIGHTING_SERVER_CORE_STATIC)
 
   #if defined(BUILDING_FIGHTING_SERVER_CORE_EXPORT)
 
        #define FIGHTING_SERVER_CORE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define FIGHTING_SERVER_CORE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_FIGHTING_SERVER_CORE_EXPORT)

		#define FIGHTING_SERVER_CORE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define FIGHTING_SERVER_CORE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_FIGHTING_SERVER_CORE_EXPORT

   #define FIGHTING_SERVER_CORE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_FIGHTING_SERVER_CORE_NO_IMPORT) || defined(BUILDING_FIGHTING_SERVER_CORE_STATIC)
 
#endif // FIGHTING_SERVER_CORE_DLL_H
