///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	版本：0.9.1.2 (2023/07/31 11:31)

#ifndef INPUT_OUTPUT_EXAMPLE_HELPER_USER_MACRO_H
#define INPUT_OUTPUT_EXAMPLE_HELPER_USER_MACRO_H

#include "System/Helper/ConfigMacro.h"
#include "CoreTools/Helper/UserMacro.h"

#define INPUT_OUTPUT_EXAMPLE_ClOSE_BEGIN (0x01)

#define CLOSE_USE_INPUT_OUTPUT_EXAMPLE (INPUT_OUTPUT_EXAMPLE_ClOSE_BEGIN)

#define INPUT_OUTPUT_EXAMPLE_ClOSE_END CLOSE_USE_INPUT_OUTPUT_EXAMPLE

#define CLOSE_INPUT_OUTPUT_EXAMPLE_MAX (((INPUT_OUTPUT_EXAMPLE_ClOSE_END) << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_INPUT_OUTPUT_EXAMPLE_CLOSE 0x00

static_assert(0 <= COMPILE_INPUT_OUTPUT_EXAMPLE_CLOSE, "COMPILE_INPUT_OUTPUT_EXAMPLE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_INPUT_OUTPUT_EXAMPLE_CLOSE <= CLOSE_INPUT_OUTPUT_EXAMPLE_MAX, "COMPILE_INPUT_OUTPUT_EXAMPLE_CLOSE Must be less than or equal CLOSE_INPUT_OUTPUT_EXAMPLE_MAX.");

#if !defined(COMPILE_INPUT_OUTPUT_EXAMPLE_CLOSE) || (COMPILE_INPUT_OUTPUT_EXAMPLE_CLOSE & CLOSE_USE_INPUT_OUTPUT_EXAMPLE) != CLOSE_USE_INPUT_OUTPUT_EXAMPLE

#endif  // !defined(COMPILE_INPUT_OUTPUT_EXAMPLE_CLOSE) || (COMPILE_INPUT_OUTPUT_EXAMPLE_CLOSE & CLOSE_USE_INPUT_OUTPUT_EXAMPLE) != CLOSE_USE_INPUT_OUTPUT_EXAMPLE

#ifdef BUILDING_STATIC

    #define BUILDING_INPUT_OUTPUT_EXAMPLE_STATIC

#endif  // BUILDING_STATIC

#endif  // INPUT_OUTPUT_EXAMPLE_HELPER_USER_MACRO_H
