// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.1 (2020/01/16 0:06)

#ifndef EFFECT_EDITOR_DLL_DLL_H
#define EFFECT_EDITOR_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(BUILDING_EFFECT_EDITOR_NO_IMPORT) || defined(BUILDING_EFFECT_EDITOR_STATIC)

  #define EFFECT_EDITOR_DEFAULT_DECLARE
  #define EFFECT_EDITOR_HIDDEN_DECLARE
  #define EFFECT_EDITOR_VISIBLE

#else // !defined(BUILDING_EFFECT_EDITOR_NO_IMPORT) && !defined(BUILDING_EFFECT_EDITOR_STATIC)

   #if defined(BUILDING_EFFECT_EDITOR_EXPORT)
 
        #define EFFECT_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define EFFECT_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_EFFECT_EDITOR_EXPORT)

		#define EFFECT_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define EFFECT_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_EFFECT_EDITOR_EXPORT

   #define EFFECT_EDITOR_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_EFFECT_EDITORNO_IMPORT) || defined(BUILDING_EFFECT_EDITOR_STATIC)

#endif // EFFECT_EDITOR_DLL_DLL_H
