///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.0 (2021/02/27 12:45)

#ifndef GENERIC_PROGRAMMING_AND_THE_STL_HELPER_USER_MACRO_H
#define GENERIC_PROGRAMMING_AND_THE_STL_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define GENERIC_PROGRAMMING_AND_THE_STL_ClOSE_BEGIN (0x01)

#define CLOSE_USE_GENERIC_PROGRAMMING_AND_THE_STL (GENERIC_PROGRAMMING_AND_THE_STL_ClOSE_BEGIN)

#define GENERIC_PROGRAMMING_AND_THE_STL_ClOSE_END CLOSE_USE_GENERIC_PROGRAMMING_AND_THE_STL

#define CLOSE_GENERIC_PROGRAMMING_AND_THE_STL_MAX ((GENERIC_PROGRAMMING_AND_THE_STL_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_GENERIC_PROGRAMMING_AND_THE_STL_CLOSE 0x00

static_assert(0 <= COMPILE_GENERIC_PROGRAMMING_AND_THE_STL_CLOSE, "COMPILE_GENERIC_PROGRAMMING_AND_THE_STL_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_GENERIC_PROGRAMMING_AND_THE_STL_CLOSE <= CLOSE_GENERIC_PROGRAMMING_AND_THE_STL_MAX, "COMPILE_GENERIC_PROGRAMMING_AND_THE_STL_CLOSE Must be less than or equal CLOSE_GENERIC_PROGRAMMING_AND_THE_STL_MAX.");

#if !defined(COMPILE_GENERIC_PROGRAMMING_AND_THE_STL_CLOSE) || (COMPILE_GENERIC_PROGRAMMING_AND_THE_STL_CLOSE & CLOSE_USE_GENERIC_PROGRAMMING_AND_THE_STL) != CLOSE_USE_GENERIC_PROGRAMMING_AND_THE_STL

#endif  // !defined(COMPILE_GENERIC_PROGRAMMING_AND_THE_STL_CLOSE) || (COMPILE_GENERIC_PROGRAMMING_AND_THE_STL_CLOSE & CLOSE_USE_GENERIC_PROGRAMMING_AND_THE_STL) != CLOSE_USE_GENERIC_PROGRAMMING_AND_THE_STL

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_GENERIC_PROGRAMMING_AND_THE_STL_STATIC
#endif  // BUILDING_STATIC

#endif  // GENERIC_PROGRAMMING_AND_THE_STL_HELPER_USER_MACRO_H
