///	Copyright (c) 2010-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.0 (2020/12/27 19:46)

#ifndef SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_DLL_H
#define SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_NO_IMPORT) || defined(BUILDING_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_STATIC)

    #define SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_DEFAULT_DECLARE
    #define SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_HIDDEN_DECLARE
    #define SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_VISIBLE

#else  // !defined(BUILDING_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_NO_IMPORT) && !defined(BUILDING_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_STATIC)

    #if defined(BUILDING_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_EXPORT)

        #define SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_EXPORT)

        #define SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_EXPORT

    #define SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_NO_IMPORT) || defined(BUILDING_SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_STATIC)

#endif  // SAMS_TEACH_YOURSELF_CPP_IN_ONE_HOUR_A_DAY_DLL_H
