///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.0 (2021/01/30 11:03)

#ifndef DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SIXTH_EDITION_IMPORT_H
#define DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SIXTH_EDITION_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SIXTH_EDITION_IMPORT
    #define BUILDING_DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SIXTH_EDITION_IMPORT
#endif  // BUILDING_DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SIXTH_EDITION_IMPORT

#endif  // DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SIXTH_EDITION_IMPORT_H
