///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	千年史策版本：0.9.0.5 (2023/04/03 09:43)

#ifndef DATABASE_GENERATE_SERVER_CORE_HELPER_USER_MACRO_H
#define DATABASE_GENERATE_SERVER_CORE_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define CLOSE_USE_DATABASE_GENERATE_SERVER_CORE (0x01)
#define CLOSE_DATABASE_GENERATE_SERVER_CORE_MAX (((CLOSE_USE_DATABASE_GENERATE_SERVER_CORE) << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_DATABASE_GENERATE_SERVER_CORE_CLOSE 0x00

static_assert(0 <= COMPILE_DATABASE_GENERATE_SERVER_CORE_CLOSE, "COMPILE_DATABASE_GENERATE_SERVER_CORE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_DATABASE_GENERATE_SERVER_CORE_CLOSE <= CLOSE_DATABASE_GENERATE_SERVER_CORE_MAX, "COMPILE_DATABASE_GENERATE_SERVER_CORE_CLOSE Must be less than or equal CLOSE_DATABASE_GENERATE_SERVER_CORE_MAX.");

#if !defined(COMPILE_DATABASE_GENERATE_SERVER_CORE_CLOSE) || (COMPILE_DATABASE_GENERATE_SERVER_CORE_CLOSE & CLOSE_USE_DATABASE_GENERATE_SERVER_CORE) != CLOSE_USE_DATABASE_GENERATE_SERVER_CORE

#endif  // !defined(COMPILE_DATABASE_GENERATE_SERVER_CORE_CLOSE) || (COMPILE_DATABASE_GENERATE_SERVER_CORE_CLOSE & CLOSE_USE_DATABASE_GENERATE_SERVER_CORE) != CLOSE_USE_DATABASE_GENERATE_SERVER_CORE

// 是否编译成静态库
#ifdef BUILDING_STATIC

    #define BUILDING_DATABASE_GENERATE_SERVER_CORE_STATIC

#endif  // BUILDING_STATIC

#endif  // DATABASE_GENERATE_SERVER_CORE_HELPER_USER_MACRO_H
