//	Copyright (c) 2011-2020
//	Threading Core Render Engine
//
//	作者：彭武阳，彭晔恩，彭晔泽
//	联系作者：94458936@qq.com
//
//	标准：std:c++17
//	引擎版本：0.5.1.0 (2020/09/21 17:47)

#ifndef SYSTEM_HELPER_GL_30_EXTENSIONS_MACRO_H
#define SYSTEM_HELPER_GL_30_EXTENSIONS_MACRO_H

#include "System/Helper/GLExtensionsMacro.h"

#define GL_COMPARE_REF_TO_TEXTURE 0x884E
#define GL_CLIP_DISTANCE0 0x3000
#define GL_CLIP_DISTANCE1 0x3001
#define GL_CLIP_DISTANCE2 0x3002
#define GL_CLIP_DISTANCE3 0x3003
#define GL_CLIP_DISTANCE4 0x3004
#define GL_CLIP_DISTANCE5 0x3005
#define GL_CLIP_DISTANCE6 0x3006
#define GL_CLIP_DISTANCE7 0x3007
#define GL_MAX_CLIP_DISTANCES 0x0D32
#define GL_MAJOR_VERSION 0x821B
#define GL_MINOR_VERSION 0x821C
#define GL_NUM_EXTENSIONS 0x821D
#define GL_CONTEXT_FLAGS 0x821E
#define GL_DEPTH_BUFFER 0x8223
#define GL_STENCIL_BUFFER 0x8224
#define GL_COMPRESSED_RED 0x8225
#define GL_COMPRESSED_RG 0x8226
#define GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT 0x0001
#define GL_RGBA32F 0x8814
#define GL_RGB32F 0x8815
#define GL_RGBA16F 0x881A
#define GL_RGB16F 0x881B
#define GL_VERTEX_ATTRIB_ARRAY_INTEGER 0x88FD
#define GL_MAX_ARRAY_TEXTURE_LAYERS 0x88FF
#define GL_MIN_PROGRAM_TEXEL_OFFSET 0x8904
#define GL_MAX_PROGRAM_TEXEL_OFFSET 0x8905
#define GL_CLAMP_VERTEX_COLOR 0x891A
#define GL_CLAMP_FRAGMENT_COLOR 0x891B
#define GL_CLAMP_READ_COLOR 0x891C
#define GL_FIXED_ONLY 0x891D
#define GL_MAX_VARYING_COMPONENTS 0x8B4B
#define GL_TEXTURE_RED_TYPE 0x8C10
#define GL_TEXTURE_GREEN_TYPE 0x8C11
#define GL_TEXTURE_BLUE_TYPE 0x8C12
#define GL_TEXTURE_ALPHA_TYPE 0x8C13
#define GL_TEXTURE_LUMINANCE_TYPE 0x8C14
#define GL_TEXTURE_INTENSITY_TYPE 0x8C15
#define GL_TEXTURE_DEPTH_TYPE 0x8C16
#define GL_TEXTURE_1D_ARRAY 0x8C18
#define GL_PROXY_TEXTURE_1D_ARRAY 0x8C19
#define GL_TEXTURE_2D_ARRAY 0x8C1A
#define GL_PROXY_TEXTURE_2D_ARRAY 0x8C1B
#define GL_TEXTURE_BINDING_1D_ARRAY 0x8C1C
#define GL_TEXTURE_BINDING_2D_ARRAY 0x8C1D
#define GL_R11F_G11F_B10F 0x8C3A
#define GL_UNSIGNED_INT_10F_11F_11F_REV 0x8C3B
#define GL_RGB9_E5 0x8C3D
#define GL_UNSIGNED_INT_5_9_9_9_REV 0x8C3E
#define GL_TEXTURE_SHARED_SIZE 0x8C3F
#define GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH 0x8C76
#define GL_TRANSFORM_FEEDBACK_BUFFER_MODE 0x8C7F
#define GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS 0x8C80
#define GL_TRANSFORM_FEEDBACK_VARYINGS 0x8C83
#define GL_TRANSFORM_FEEDBACK_BUFFER_START 0x8C84
#define GL_TRANSFORM_FEEDBACK_BUFFER_SIZE 0x8C85
#define GL_PRIMITIVES_GENERATED 0x8C87
#define GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN 0x8C88
#define GL_RASTERIZER_DISCARD 0x8C89
#define GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS 0x8C8A
#define GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS 0x8C8B
#define GL_INTERLEAVED_ATTRIBS 0x8C8C
#define GL_SEPARATE_ATTRIBS 0x8C8D
#define GL_TRANSFORM_FEEDBACK_BUFFER 0x8C8E
#define GL_TRANSFORM_FEEDBACK_BUFFER_BINDING 0x8C8F
#define GL_RGBA32UI 0x8D70
#define GL_RGB32UI 0x8D71
#define GL_RGBA16UI 0x8D76
#define GL_RGB16UI 0x8D77
#define GL_RGBA8UI 0x8D7C
#define GL_RGB8UI 0x8D7D
#define GL_RGBA32I 0x8D82
#define GL_RGB32I 0x8D83
#define GL_RGBA16I 0x8D88
#define GL_RGB16I 0x8D89
#define GL_RGBA8I 0x8D8E
#define GL_RGB8I 0x8D8F
#define GL_RED_INTEGER 0x8D94
#define GL_GREEN_INTEGER 0x8D95
#define GL_BLUE_INTEGER 0x8D96
#define GL_ALPHA_INTEGER 0x8D97
#define GL_RGB_INTEGER 0x8D98
#define GL_RGBA_INTEGER 0x8D99
#define GL_BGR_INTEGER 0x8D9A
#define GL_BGRA_INTEGER 0x8D9B
#define GL_SAMPLER_1D_ARRAY 0x8DC0
#define GL_SAMPLER_2D_ARRAY 0x8DC1
#define GL_SAMPLER_1D_ARRAY_SHADOW 0x8DC3
#define GL_SAMPLER_2D_ARRAY_SHADOW 0x8DC4
#define GL_SAMPLER_CUBE_SHADOW 0x8DC5
#define GL_UNSIGNED_INT_VEC2 0x8DC6
#define GL_UNSIGNED_INT_VEC3 0x8DC7
#define GL_UNSIGNED_INT_VEC4 0x8DC8
#define GL_INT_SAMPLER_1D 0x8DC9
#define GL_INT_SAMPLER_2D 0x8DCA
#define GL_INT_SAMPLER_3D 0x8DCB
#define GL_INT_SAMPLER_CUBE 0x8DCC
#define GL_INT_SAMPLER_1D_ARRAY 0x8DCE
#define GL_INT_SAMPLER_2D_ARRAY 0x8DCF
#define GL_UNSIGNED_INT_SAMPLER_1D 0x8DD1
#define GL_UNSIGNED_INT_SAMPLER_2D 0x8DD2
#define GL_UNSIGNED_INT_SAMPLER_3D 0x8DD3
#define GL_UNSIGNED_INT_SAMPLER_CUBE 0x8DD4
#define GL_UNSIGNED_INT_SAMPLER_1D_ARRAY 0x8DD6
#define GL_UNSIGNED_INT_SAMPLER_2D_ARRAY 0x8DD7
#define GL_QUERY_WAIT 0x8E13
#define GL_QUERY_NO_WAIT 0x8E14
#define GL_QUERY_BY_REGION_WAIT 0x8E15
#define GL_QUERY_BY_REGION_NO_WAIT 0x8E16
#define GL_BUFFER_ACCESS_FLAGS 0x911F
#define GL_BUFFER_MAP_LENGTH 0x9120
#define GL_BUFFER_MAP_OFFSET 0x9121

#define glColorMaski System::GlColorMaski
#define glGetBooleani_v System::GlGetBooleani_v
#define glGetIntegeri_v System::GlGetIntegeri_v
#define glEnablei System::GlEnablei
#define glDisablei System::GlDisablei
#define glIsEnabledi System::GlIsEnabledi
#define glBeginTransformFeedback System::GlBeginTransformFeedback
#define glEndTransformFeedback System::GlEndTransformFeedback
#define glBindBufferRange System::GlBindBufferRange
#define glBindBufferBase System::GlBindBufferBase
#define glTransformFeedbackVaryings System::GlTransformFeedbackVaryings
#define glGetTransformFeedbackVarying System::GlGetTransformFeedbackVarying
#define glClampColor System::GlClampColor
#define glBeginConditionalRender System::GlBeginConditionalRender
#define glEndConditionalRender System::GlEndConditionalRender
#define glVertexAttribIPointer System::GlVertexAttribIPointer
#define glGetVertexAttribIiv System::GlGetVertexAttribIiv
#define glGetVertexAttribIuiv System::GlGetVertexAttribIuiv
#define glVertexAttribI1i System::GlVertexAttribI1i
#define glVertexAttribI2i System::GlVertexAttribI2i
#define glVertexAttribI3i System::GlVertexAttribI3i
#define glVertexAttribI4i System::GlVertexAttribI4i
#define glVertexAttribI1ui System::GlVertexAttribI1ui
#define glVertexAttribI2ui System::GlVertexAttribI2ui
#define glVertexAttribI3ui System::GlVertexAttribI3ui
#define glVertexAttribI4ui System::GlVertexAttribI4ui
#define glVertexAttribI1iv System::GlVertexAttribI1iv
#define glVertexAttribI2iv System::GlVertexAttribI2iv
#define glVertexAttribI3iv System::GlVertexAttribI3iv
#define glVertexAttribI4iv System::GlVertexAttribI4iv
#define glVertexAttribI1uiv System::GlVertexAttribI1uiv
#define glVertexAttribI2uiv System::GlVertexAttribI2uiv
#define glVertexAttribI3uiv System::GlVertexAttribI3uiv
#define glVertexAttribI4uiv System::GlVertexAttribI4uiv
#define glVertexAttribI4bv System::GlVertexAttribI4bv
#define glVertexAttribI4sv System::GlVertexAttribI4sv
#define glVertexAttribI4ubv System::GlVertexAttribI4ubv
#define glVertexAttribI4usv System::GlVertexAttribI4usv
#define glGetUniformuiv System::GlGetUniformuiv
#define glBindFragDataLocation System::GlBindFragDataLocation
#define glGetFragDataLocation System::GlGetFragDataLocation
#define glUniform1ui System::GlUniform1ui
#define glUniform2ui System::GlUniform2ui
#define glUniform3ui System::GlUniform3ui
#define glUniform4ui System::GlUniform4ui
#define glUniform1uiv System::GlUniform1uiv
#define glUniform2uiv System::GlUniform2uiv
#define glUniform3uiv System::GlUniform3uiv
#define glUniform4uiv System::GlUniform4uiv
#define glTexParameterIiv System::GlTexParameterIiv
#define glTexParameterIuiv System::GlTexParameterIuiv
#define glGetTexParameterIiv System::GlGetTexParameterIiv
#define glGetTexParameterIuiv System::GlGetTexParameterIuiv
#define glClearBufferiv System::GlClearBufferiv
#define glClearBufferuiv System::GlClearBufferuiv
#define glClearBufferfv System::GlClearBufferfv
#define glClearBufferfi System::GlClearBufferfi
#define glGetStringi System::GlGetStringi

#endif  // SYSTEM_HELPER_GL_30_EXTENSIONS_MACRO_H
