// Copyright (c) 2011-2020
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 引擎版本：0.2.0.0 (2020/05/07 23:39)

#ifndef SYSTEM_HELPER_GL_44_EXTENSIONS_MACRO_H
#define SYSTEM_HELPER_GL_44_EXTENSIONS_MACRO_H

#include "System/Helper/GLExtensionsMacro.h"

#define GL_PRIMITIVE_RESTART_FOR_PATCHES_SUPPORTED 0x8221
#define GL_MAX_VERTEX_ATTRIB_STRIDE 0x82E5
#define GL_TEXTURE_BUFFER_BINDING 0x8C2A 

#endif // SYSTEM_HELPER_GL_44_EXTENSIONS_MACRO_H
