//	Copyright (c) 2011-2020
//	Threading Core Render Engine
//
//	作者：彭武阳，彭晔恩，彭晔泽
//	联系作者：94458936@qq.com
//
//	标准：std:c++17
//	引擎版本：0.5.1.0 (2020/09/21 17:51)

#ifndef SYSTEM_HELPER_WGL_EXTENSIONS_MACRO_H
#define SYSTEM_HELPER_WGL_EXTENSIONS_MACRO_H

#include "System/Helper/GLExtensionsMacro.h"

// ARB 扩展

// (ARB 04) WGL_ARB_buffer_region

#define WGL_FRONT_COLOR_BUFFER_BIT_ARB 0x00000001
#define WGL_BACK_COLOR_BUFFER_BIT_ARB 0x00000002
#define WGL_DEPTH_BUFFER_BIT_ARB 0x00000004
#define WGL_STENCIL_BUFFER_BIT_ARB 0x00000008

#define wglCreateBufferRegionARB System::WglCreateBufferRegionARB
#define wglDeleteBufferRegionARB System::WglDeleteBufferRegionARB
#define wglSaveBufferRegionARB System::WglSaveBufferRegionARB
#define wglRestoreBufferRegionARB System::WglRestoreBufferRegionARB

// (ARB 05) WGL_ARB_multisample

#define WGL_SAMPLE_BUFFERS_ARB 0x2041
#define WGL_SAMPLES_ARB 0x2042

// (ARB 08) WGL_ARB_extensions_string

#define wglGetExtensionsStringARB System::WglGetExtensionsStringARB

// (ARB 09) WGL_ARB_pixel_format

#define WGL_NUMBER_PIXEL_FORMATS_ARB 0x2000
#define WGL_DRAW_TO_WINDOW_ARB 0x2001
#define WGL_DRAW_TO_BITMAP_ARB 0x2002
#define WGL_ACCELERATION_ARB 0x2003
#define WGL_NEED_PALETTE_ARB 0x2004
#define WGL_NEED_SYSTEM_PALETTE_ARB 0x2005
#define WGL_SWAP_LAYER_BUFFERS_ARB 0x2006
#define WGL_SWAP_METHOD_ARB 0x2007
#define WGL_NUMBER_OVERLAYS_ARB 0x2008
#define WGL_NUMBER_UNDERLAYS_ARB 0x2009
#define WGL_TRANSPARENT_ARB 0x200A
#define WGL_TRANSPARENT_RED_VALUE_ARB 0x2037
#define WGL_TRANSPARENT_GREEN_VALUE_ARB 0x2038
#define WGL_TRANSPARENT_BLUE_VALUE_ARB 0x2039
#define WGL_TRANSPARENT_ALPHA_VALUE_ARB 0x203A
#define WGL_TRANSPARENT_INDEX_VALUE_ARB 0x203B
#define WGL_SHARE_DEPTH_ARB 0x200C
#define WGL_SHARE_STENCIL_ARB 0x200D
#define WGL_SHARE_ACCUM_ARB 0x200E
#define WGL_SUPPORT_GDI_ARB 0x200F
#define WGL_SUPPORT_OPENGL_ARB 0x2010
#define WGL_DOUBLE_BUFFER_ARB 0x2011
#define WGL_STEREO_ARB 0x2012
#define WGL_PIXEL_TYPE_ARB 0x2013
#define WGL_COLOR_BITS_ARB 0x2014
#define WGL_RED_BITS_ARB 0x2015
#define WGL_RED_SHIFT_ARB 0x2016
#define WGL_GREEN_BITS_ARB 0x2017
#define WGL_GREEN_SHIFT_ARB 0x2018
#define WGL_BLUE_BITS_ARB 0x2019
#define WGL_BLUE_SHIFT_ARB 0x201A
#define WGL_ALPHA_BITS_ARB 0x201B
#define WGL_ALPHA_SHIFT_ARB 0x201C
#define WGL_ACCUM_BITS_ARB 0x201D
#define WGL_ACCUM_RED_BITS_ARB 0x201E
#define WGL_ACCUM_GREEN_BITS_ARB 0x201F
#define WGL_ACCUM_BLUE_BITS_ARB 0x2020
#define WGL_ACCUM_ALPHA_BITS_ARB 0x2021
#define WGL_DEPTH_BITS_ARB 0x2022
#define WGL_STENCIL_BITS_ARB 0x2023
#define WGL_AUX_BUFFERS_ARB 0x2024
#define WGL_NO_ACCELERATION_ARB 0x2025
#define WGL_GENERIC_ACCELERATION_ARB 0x2026
#define WGL_FULL_ACCELERATION_ARB 0x2027
#define WGL_SWAP_EXCHANGE_ARB 0x2028
#define WGL_SWAP_COPY_ARB 0x2029
#define WGL_SWAP_UNDEFINED_ARB 0x202A
#define WGL_TYPE_RGBA_ARB 0x202B
#define WGL_TYPE_COLORINDEX_ARB 0x202C

#define wglGetPixelFormatAttribivARB System::WglGetPixelFormatAttribivARB
#define wglGetPixelFormatAttribfvARB System::WglGetPixelFormatAttribfvARB
#define wglChoosePixelFormatARB System::WglChoosePixelFormatARB

// (ARB 10) WGL_ARB_make_current_read

#define ERROR_INVALID_PIXEL_TYPE_ARB 0x2043
#define ERROR_INCOMPATIBLE_DEVICE_CONTEXTS_ARB 0x2054

#define wglMakeContextCurrentARB System::WglMakeContextCurrentARB
#define wglGetCurrentReadDCARB System::WglGetCurrentReadDCARB

// (ARB 11) WGL_ARB_pbuffer

#define WGL_DRAW_TO_PBUFFER_ARB 0x202D
#define WGL_MAX_PBUFFER_PIXELS_ARB 0x202E
#define WGL_MAX_PBUFFER_WIDTH_ARB 0x202F
#define WGL_MAX_PBUFFER_HEIGHT_ARB 0x2030
#define WGL_PBUFFER_LARGEST_ARB 0x2033
#define WGL_PBUFFER_WIDTH_ARB 0x2034
#define WGL_PBUFFER_HEIGHT_ARB 0x2035
#define WGL_PBUFFER_LOST_ARB 0x2036

#define wglCreatePbufferARB System::WglCreatePbufferARB
#define wglGetPbufferDCARB System::WglGetPbufferDCARB
#define wglReleasePbufferDCARB System::WglReleasePbufferDCARB
#define wglDestroyPbufferARB System::WglDestroyPbufferARB
#define wglQueryPbufferARB System::WglQueryPbufferARB

// (ARB 20) WGL_ARB_render_texture

#define WGL_BIND_TO_TEXTURE_RGB_ARB 0x2070
#define WGL_BIND_TO_TEXTURE_RGBA_ARB 0x2071
#define WGL_TEXTURE_FORMAT_ARB 0x2072
#define WGL_TEXTURE_TARGET_ARB 0x2073
#define WGL_MIPMAP_TEXTURE_ARB 0x2074
#define WGL_TEXTURE_RGB_ARB 0x2075
#define WGL_TEXTURE_RGBA_ARB 0x2076
#define WGL_NO_TEXTURE_ARB 0x2077
#define WGL_TEXTURE_CUBE_MAP_ARB 0x2078
#define WGL_TEXTURE_1D_ARB 0x2079
#define WGL_TEXTURE_2D_ARB 0x207A
#define WGL_MIPMAP_LEVEL_ARB 0x207B
#define WGL_CUBE_MAP_FACE_ARB 0x207C
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB 0x207D
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB 0x207E
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB 0x207F
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB 0x2080
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB 0x2081
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB 0x2082
#define WGL_FRONT_LEFT_ARB 0x2083
#define WGL_FRONT_RIGHT_ARB 0x2084
#define WGL_BACK_LEFT_ARB 0x2085
#define WGL_BACK_RIGHT_ARB 0x2086
#define WGL_AUX0_ARB 0x2087
#define WGL_AUX1_ARB 0x2088
#define WGL_AUX2_ARB 0x2089
#define WGL_AUX3_ARB 0x208A
#define WGL_AUX4_ARB 0x208B
#define WGL_AUX5_ARB 0x208C
#define WGL_AUX6_ARB 0x208D
#define WGL_AUX7_ARB 0x208E
#define WGL_AUX8_ARB 0x208F
#define WGL_AUX9_ARB 0x2090

#define wglBindTexImageARB System::WglBindTexImageARB
#define wglReleaseTexImageARB System::WglReleaseTexImageARB
#define wglSetPbufferAttribARB System::WglSetPbufferAttribARB

// (ARB 39) WGL_ARB_pixel_format_float

#define WGL_TYPE_RGBA_FLOAT_ARB 0x21A0

// (ARB 46) WGL_ARB_framebuffer_sRGB

#define WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB 0x20A9

// (ARB 55) WGL_ARB_create_context

#define WGL_CONTEXT_DEBUG_BIT_ARB 0x0001
#define WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB 0x0002
#define WGL_CONTEXT_MAJOR_VERSION_ARB 0x2091
#define WGL_CONTEXT_MINOR_VERSION_ARB 0x2092
#define WGL_CONTEXT_LAYER_PLANE_ARB 0x2093
#define WGL_CONTEXT_FLAGS_ARB 0x2094
#define ERROR_INVALID_VERSION_ARB 0x2095
#define ERROR_INVALID_PROFILE_ARB 0x2096

#define wglCreateContextAttribsARB System::WglCreateContextAttribsARB

// (ARB 74) WGL_ARB_create_context_profile

#define WGL_CONTEXT_CORE_PROFILE_BIT_ARB 0x00000001
#define WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB 0x00000002
#define WGL_CONTEXT_PROFILE_MASK_ARB 0x9126

// (ARB 102) WGL_ARB_create_context_robustness

#define WGL_CONTEXT_ROBUST_ACCESS_BIT_ARB 0x00000004
#define WGL_LOSE_CONTEXT_ON_RESET_ARB 0x8252
#define WGL_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB 0x8256
#define WGL_NO_RESET_NOTIFICATION_ARB 0x8261

// (ARB 143) WGL_ARB_robustness_application_isolation

#define WGL_CONTEXT_RESET_ISOLATION_BIT_ARB 0x00000008

// (ARB 143) WGL_ARB_robustness_share_group_isolation

#define WGL_CONTEXT_RESET_ISOLATION_BIT_ARB 0x00000008

// (ARB 168) WGL_ARB_context_flush_control

#define WGL_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB 0x0000
#define WGL_CONTEXT_RELEASE_BEHAVIOR_ARB 0x2097
#define WGL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB 0x2098

// EXT 扩展

// (EXT 167) WGL_EXT_display_color_table

#define wglCreateDisplayColorTableEXT System::WglCreateDisplayColorTableEXT
#define wglLoadDisplayColorTableEXT System::WglLoadDisplayColorTableEXT
#define wglBindDisplayColorTableEXT System::WglBindDisplayColorTableEXT
#define wglDestroyDisplayColorTableEXT System::WglDestroyDisplayColorTableEXT

// (EXT 168) WGL_EXT_extensions_string

#define wglGetExtensionsStringEXT System::WglGetExtensionsStringEXT

// (EXT 169) WGL_EXT_make_current_read

#define ERROR_INVALID_PIXEL_TYPE_EXT 0x2043

#define wglMakeContextCurrentEXT System::WglMakeContextCurrentEXT
#define wglGetCurrentReadDCEXT System::WglGetCurrentReadDCEXT

// (EXT 170) WGL_EXT_pixel_format

#define WGL_NUMBER_PIXEL_FORMATS_EXT 0x2000
#define WGL_DRAW_TO_WINDOW_EXT 0x2001
#define WGL_DRAW_TO_BITMAP_EXT 0x2002
#define WGL_ACCELERATION_EXT 0x2003
#define WGL_NEED_PALETTE_EXT 0x2004
#define WGL_NEED_SYSTEM_PALETTE_EXT 0x2005
#define WGL_SWAP_LAYER_BUFFERS_EXT 0x2006
#define WGL_SWAP_METHOD_EXT 0x2007
#define WGL_NUMBER_OVERLAYS_EXT 0x2008
#define WGL_NUMBER_UNDERLAYS_EXT 0x2009
#define WGL_TRANSPARENT_EXT 0x200A
#define WGL_TRANSPARENT_VALUE_EXT 0x200B
#define WGL_SHARE_DEPTH_EXT 0x200C
#define WGL_SHARE_STENCIL_EXT 0x200D
#define WGL_SHARE_ACCUM_EXT 0x200E
#define WGL_SUPPORT_GDI_EXT 0x200F
#define WGL_SUPPORT_OPENGL_EXT 0x2010
#define WGL_DOUBLE_BUFFER_EXT 0x2011
#define WGL_STEREO_EXT 0x2012
#define WGL_PIXEL_TYPE_EXT 0x2013
#define WGL_COLOR_BITS_EXT 0x2014
#define WGL_RED_BITS_EXT 0x2015
#define WGL_RED_SHIFT_EXT 0x2016
#define WGL_GREEN_BITS_EXT 0x2017
#define WGL_GREEN_SHIFT_EXT 0x2018
#define WGL_BLUE_BITS_EXT 0x2019
#define WGL_BLUE_SHIFT_EXT 0x201A
#define WGL_ALPHA_BITS_EXT 0x201B
#define WGL_ALPHA_SHIFT_EXT 0x201C
#define WGL_ACCUM_BITS_EXT 0x201D
#define WGL_ACCUM_RED_BITS_EXT 0x201E
#define WGL_ACCUM_GREEN_BITS_EXT 0x201F
#define WGL_ACCUM_BLUE_BITS_EXT 0x2020
#define WGL_ACCUM_ALPHA_BITS_EXT 0x2021
#define WGL_DEPTH_BITS_EXT 0x2022
#define WGL_STENCIL_BITS_EXT 0x2023
#define WGL_AUX_BUFFERS_EXT 0x2024
#define WGL_NO_ACCELERATION_EXT 0x2025
#define WGL_GENERIC_ACCELERATION_EXT 0x2026
#define WGL_FULL_ACCELERATION_EXT 0x2027
#define WGL_SWAP_EXCHANGE_EXT 0x2028
#define WGL_SWAP_COPY_EXT 0x2029
#define WGL_SWAP_UNDEFINED_EXT 0x202A
#define WGL_TYPE_RGBA_EXT 0x202B
#define WGL_TYPE_COLORINDEX_EXT 0x202C

#define wglGetPixelFormatAttribivEXT System::WglGetPixelFormatAttribivEXT
#define wglGetPixelFormatAttribfvEXT System::WglGetPixelFormatAttribfvEXT
#define wglChoosePixelFormatEXT System::WglChoosePixelFormatEXT

// (EXT 171) WGL_EXT_pbuffer

#define WGL_DRAW_TO_PBUFFER_EXT 0x202D
#define WGL_MAX_PBUFFER_PIXELS_EXT 0x202E
#define WGL_MAX_PBUFFER_WIDTH_EXT 0x202F
#define WGL_MAX_PBUFFER_HEIGHT_EXT 0x2030
#define WGL_OPTIMAL_PBUFFER_WIDTH_EXT 0x2031
#define WGL_OPTIMAL_PBUFFER_HEIGHT_EXT 0x2032
#define WGL_PBUFFER_LARGEST_EXT 0x2033
#define WGL_PBUFFER_WIDTH_EXT 0x2034
#define WGL_PBUFFER_HEIGHT_EXT 0x2035

#define wglCreatePbufferEXT System::WglCreatePbufferEXT
#define wglGetPbufferDCEXT System::WglGetPbufferDCEXT
#define wglReleasePbufferDCEXT System::WglReleasePbufferDCEXT
#define wglDestroyPbufferEXT System::WglDestroyPbufferEXT
#define wglQueryPbufferEXT System::WglQueryPbufferEXT

// (EXT 172) WGL_EXT_swap_control

#define wglSwapIntervalEXT System::WglSwapIntervalEXT
#define wglGetSwapIntervalEXT System::WglGetSwapIntervalEXT

// (EXT 177) WGL_EXT_depth_float

#define WGL_DEPTH_FLOAT_EXT 0x2040

// (EXT 209) WGL_EXT_multisample

#define WGL_SAMPLE_BUFFERS_EXT 0x2041
#define WGL_SAMPLES_EXT 0x2042

// (EXT 328) WGL_EXT_pixel_format_packed_float

#define WGL_TYPE_RGBA_UNSIGNED_FLOAT_EXT 0x20A8

// (EXT 337) WGL_EXT_framebuffer_sRGB

#define WGL_FRAMEBUFFER_SRGB_CAPABLE_EXT 0x20A9

// (EXT 400) WGL_EXT_create_context_es2_profile

#define WGL_CONTEXT_ES2_PROFILE_BIT_EXT 0x00000004

// (EXT 400) WGL_EXT_create_context_es_profile

#define WGL_CONTEXT_ES_PROFILE_BIT_EXT 0x00000004

#endif  // SYSTEM_HELPER_WGL_EXTENSIONS_MACRO_H
