// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 引擎版本：0.0.0.4 (2019/07/31 10:07)

#ifndef ARTIFICIAL_INTELLEGENCE_NO_IMPORT_H
#define ARTIFICIAL_INTELLEGENCE_NO_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_ARTIFICIAL_INTELLEGENCE_NO_IMPORT
  #define BUILDING_ARTIFICIAL_INTELLEGENCE_NO_IMPORT
#endif // BUILDING_ARTIFICIAL_INTELLEGENCE_NO_IMPORT

#endif // ARTIFICIAL_INTELLEGENCE_NO_IMPORT_H