// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
// 
// “˝«Ê∞Ê±æ£∫0.0.0.4 (2019/07/31 10:06)

#ifndef ARTIFICIAL_INTELLEGENCE_DLL_H
#define ARTIFICIAL_INTELLEGENCE_DLL_H

#include "System/Helper/ExportMacro.h"
#include "ArtificialIntellegence/Macro/UserMacro.h"

#if defined(BUILDING_ARTIFICIAL_INTELLEGENCE_NO_IMPORT) || defined(BUILDING_ARTIFICIAL_INTELLEGENCE_STATIC)

  #define ARTIFICIAL_INTELLEGENCE_DEFAULT_DECLARE
  #define ARTIFICIAL_INTELLEGENCE_HIDDEN_DECLARE
  #define ARTIFICIAL_INTELLEGENCE_VISIBLE

#else // !defined(BUILDING_ARTIFICIAL_INTELLEGENCE_NO_IMPORT) && !defined(BUILDING_ARTIFICIAL_INTELLEGENCE_STATIC)

   #if defined(BUILDING_ARTIFICIAL_INTELLEGENCE_EXPORT)
 
        #define ARTIFICIAL_INTELLEGENCE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define ARTIFICIAL_INTELLEGENCE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_ARTIFICIAL_INTELLEGENCE_EXPORT)

		#define ARTIFICIAL_INTELLEGENCE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define ARTIFICIAL_INTELLEGENCE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_ARTIFICIAL_INTELLEGENCE_EXPORT

   #define ARTIFICIAL_INTELLEGENCE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_ARTIFICIAL_INTELLEGENCE_NO_IMPORT) || defined(BUILDING_ARTIFICIAL_INTELLEGENCE_STATIC)

#endif // ARTIFICIAL_INTELLEGENCE_DLL_H