///	Copyright (c) 2010-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎版本：0.5.2.4 (2020/11/26 11:08)

#ifndef MATHEMATICS_NUMERICAL_ANALYSIS_MATRIX3_TOOLS_DETAIL_H
#define MATHEMATICS_NUMERICAL_ANALYSIS_MATRIX3_TOOLS_DETAIL_H

#include "Matrix3Tools.h" 

#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_MATRIX3_TOOLS_ACHIEVE)

    #include "Matrix3ToolsAchieve.h"

#endif  // !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_MATRIX3_TOOLS_ACHIEVE)

#endif // MATHEMATICS_NUMERICAL_ANALYSIS_MATRIX3_TOOLS_DETAIL_H
