/// Copyright (c) 2010-2024
/// Threading Core Render Engine
///
/// 作者：彭武阳，彭晔恩，彭晔泽
/// 联系作者：94458936@qq.com
///
/// 标准：std:c++20
/// 版本：1.0.0.4 (2024/01/12 13:44)

#ifndef MATHEMATICS_NUMERICAL_ANALYSIS_H
#define MATHEMATICS_NUMERICAL_ANALYSIS_H

#include "Algebra/GivensRotationDetail.h"
#include "Algebra/Minimize1Detail.h"
#include "Algebra/MinimizeNDetail.h"
#include "Algebra/OdeEulerDetail.h"
#include "Algebra/OdeMidpointDetail.h"
#include "Algebra/OdeRungeKutta4Detail.h"
#include "Algebra/OdeSolverDetail.h"
#include "Algebra/PolynomialRootDetail.h"
#include "Algebra/SingularInfoDetail.h"
#include "Algebra/SingularValueDecompositionDetail.h"
#include "Bisect1Detail.h"
#include "Bisect1RootDetail.h"
#include "Bisect2Detail.h"
#include "Bisect2RootDetail.h"
#include "Bisect3Detail.h"
#include "Bisect3RootDetail.h"
#include "BlockCholeskyDecompositionDetail.h"
#include "BrentsMethodCalculateDetail.h"
#include "BrentsMethodDetail.h"
#include "BrentsMethodRootDetail.h"
#include "CholeskyDecompositionDetail.h"
#include "CubicRootsQrDetail.h"
#include "EigenDecompositionDetail.h"
#include "Equation.h"
#include "EquationResultConstIteratorDetail.h"
#include "GaussNewtonMinimizerDetail.h"
#include "GaussNewtonMinimizerResultDetail.h"
#include "GaussianQuadratureDetail.h"
#include "IntegrationDetail.h"
#include "LdltDecompositionDetail.h"
#include "LevenbergMarquardtMinimizerDetail.h"
#include "LinearComplementarityProblemSolverDetail.h"
#include "LinearComplementarityProblemSolverSharedDetail.h"
#include "LinearComplementarityProblemSolverVariableDetail.h"
#include "LinearSystemDetail.h"
#include "Matrix3ToolsDetail.h"
#include "Minimize1DataDetail.h"
#include "Minimize1Detail.h"
#include "MinimizeNDataDetail.h"
#include "MinimizeNDetail.h"
#include "NISymmetricEigensolver3x3Detail.h"
#include "NoniterativeEigen3x3Detail.h"
#include "OdeEulerDetail.h"
#include "OdeImplicitEulerDetail.h"
#include "OdeMidpointDetail.h"
#include "OdeRungeKutta4Detail.h"
#include "OdeSolverDetail.h"
#include "PolarDecompositionValueDetail.h"
#include "PolynomialRootsDetail.h"
#include "PolynomialRootsRationalDetail.h"
#include "QDUDecompositionValueDetail.h"
#include "QuarticRootsQrDetail.h"
#include "RombergIntegralDetail.h"
#include "RootsBisection1Detail.h"
#include "RootsBisection2Detail.h"
#include "RootsBisectionDetail.h"
#include "RootsBrentsMethodDetail.h"
#include "RootsCubicDetail.h"
#include "RootsGeneralPolynomialDetail.h"
#include "RootsLinearDetail.h"
#include "RootsPolynomialDetail.h"
#include "RootsQuadraticDetail.h"
#include "RootsQuarticDetail.h"
#include "SingularValueDecompositionDetail.h"
#include "SingularValueDetail.h"
#include "SortEigenstuffDetail.h"
#include "SparseMatrixDetail.h"
#include "SparseMatrixIndex.h"
#include "SymmetricEigensolver2x2Detail.h"
#include "SymmetricEigensolver3x3Detail.h"
#include "SymmetricEigensolverDetail.h"
#include "TrapezoidRuleDetail.h"
#include "UnsymmetricEigenvaluesDetail.h"

#endif  // MATHEMATICS_NUMERICAL_ANALYSIS_H