<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <TargetName>$(ProjectName)StaticD</TargetName>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <Link>
      <AdditionalLibraryDirectories>../../../../Libs/ACE/ACE_wrappers/lib/x64;../../../../Libs/mysql/BuildX64/archive_output_directory/Debug;../../../../Libs/mysql-connector-c++/BuildX64/Debug/;../../../../Libs/protobuf/BuildX64/bin/Debug/;../../../../Libs/freeglut/BuildX64/Debug/;../../../../Libs/vld/src/bin/x64/Debug-v143/;../../../../Libs/OpenXLSX/BuildX64/output/Debug/;../../../../Libs/miniz/BuildX64/Debug/;../../../../Libs/activemq/activemq-cpp/BuildX64/Debug/;$(LibsEnvironmentX64Lib);$(LibsEnvironmentX64DebugLib);../../../$(Platform)/$(Configuration)Windows;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Link>
    <ClCompile>
      <PreprocessorDefinitions>BUILDING_STATIC;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>