///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	版本：0.9.1.0 (2023/06/20 11:01)

#ifndef DISTANCE_ALIGNED_BOXES_CORE_DLL_DLL_H
#define DISTANCE_ALIGNED_BOXES_CORE_DLL_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_DISTANCE_ALIGNED_BOXES_CORE_NO_IMPORT) || defined(BUILDING_DISTANCE_ALIGNED_BOXES_CORE_STATIC)

    #define DISTANCE_ALIGNED_BOXES_CORE_DEFAULT_DECLARE
    #define DISTANCE_ALIGNED_BOXES_CORE_VISIBLE

    #if defined(BUILDING_DISTANCE_ALIGNED_BOXES_CORE_EXPORT)

        #define DISTANCE_ALIGNED_BOXES_CORE_HIDDEN_DECLARE

    #else  // !defined(BUILDING_DISTANCE_ALIGNED_BOXES_CORE_EXPORT)

        #define DISTANCE_ALIGNED_BOXES_CORE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_DISTANCE_ALIGNED_BOXES_CORE_EXPORT

#else  // !defined(BUILDING_DISTANCE_ALIGNED_BOXES_CORE_NO_IMPORT) && !defined(BUILDING_DISTANCE_ALIGNED_BOXES_CORE_STATIC)

    #if defined(BUILDING_DISTANCE_ALIGNED_BOXES_CORE_EXPORT)

        #define DISTANCE_ALIGNED_BOXES_CORE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define DISTANCE_ALIGNED_BOXES_CORE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_DISTANCE_ALIGNED_BOXES_CORE_EXPORT)

        #define DISTANCE_ALIGNED_BOXES_CORE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define DISTANCE_ALIGNED_BOXES_CORE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_DISTANCE_ALIGNED_BOXES_CORE_EXPORT

    #define DISTANCE_ALIGNED_BOXES_CORE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_DISTANCE_ALIGNED_BOXES_CORE_NO_IMPORT) || defined(BUILDING_DISTANCE_ALIGNED_BOXES_CORE_STATIC)

#endif  // DISTANCE_ALIGNED_BOXES_CORE_DLL_DLL_H
