///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.5 (2021/10/28 22:19)

#ifndef CPP_MULTITHREADING_COOKBOOK_DLL_H
#define CPP_MULTITHREADING_COOKBOOK_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_CPP_MULTITHREADING_COOKBOOK_NO_IMPORT) || defined(BUILDING_CPP_MULTITHREADING_COOKBOOK_STATIC)

    #define CPP_MULTITHREADING_COOKBOOK_DEFAULT_DECLARE
    #define CPP_MULTITHREADING_COOKBOOK_VISIBLE

    #if defined(BUILDING_CPP_MULTITHREADING_COOKBOOK_EXPORT)

        #define CPP_MULTITHREADING_COOKBOOK_HIDDEN_DECLARE

    #else  // !defined(BUILDING_CPP_MULTITHREADING_COOKBOOK_EXPORT)

        #define CPP_MULTITHREADING_COOKBOOK_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_CPP_MULTITHREADING_COOKBOOK_EXPORT

#else  // !defined(BUILDING_CPP_MULTITHREADING_COOKBOOK_NO_IMPORT) && !defined(BUILDING_CPP_MULTITHREADING_COOKBOOK_STATIC)

    #if defined(BUILDING_CPP_MULTITHREADING_COOKBOOK_EXPORT)

        #define CPP_MULTITHREADING_COOKBOOK_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define CPP_MULTITHREADING_COOKBOOK_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_CPP_MULTITHREADING_COOKBOOK_EXPORT)

        #define CPP_MULTITHREADING_COOKBOOK_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define CPP_MULTITHREADING_COOKBOOK_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_CPP_MULTITHREADING_COOKBOOK_EXPORT

    #define CPP_MULTITHREADING_COOKBOOK_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_CPP_MULTITHREADING_COOKBOOK_NO_IMPORT) || defined(BUILDING_CPP_MULTITHREADING_COOKBOOK_STATIC)

#endif  // CPP_MULTITHREADING_COOKBOOK_DLL_H
