///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.2 (2021/08/27 22:22)

#ifndef EFFECTIVE_TCP_IP_PROGRAMMING_EXPORT_H
#define EFFECTIVE_TCP_IP_PROGRAMMING_EXPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_EFFECTIVE_TCP_IP_PROGRAMMING_EXPORT
    #define BUILDING_EFFECTIVE_TCP_IP_PROGRAMMING_EXPORT
#endif  // BUILDING_EFFECTIVE_TCP_IP_PROGRAMMING_EXPORT

#endif  // EFFECTIVE_TCP_IP_PROGRAMMING_EXPORT_H
