@echo on
 
start /d %MillenniumHistoryTestingWin32DebugLib% DatabaseGenerateMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingWin32ReleaseLib% DatabaseGenerateMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingX64DebugLib% DatabaseGenerateMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingX64ReleaseLib% DatabaseGenerateMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingStaticWin32DebugLib% DatabaseGenerateMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingStaticWin32ReleaseLib% DatabaseGenerateMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingStaticX64DebugLib% DatabaseGenerateMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingStaticX64ReleaseLib% DatabaseGenerateMiddleLayerTestingStatic.exe

start /d %MillenniumHistoryTestingEngineStaticGameDynamicWin32DebugLib% DatabaseGenerateMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicWin32ReleaseLib% DatabaseGenerateMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicX64DebugLib% DatabaseGenerateMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicX64ReleaseLib% DatabaseGenerateMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticWin32DebugLib% DatabaseGenerateMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticWin32ReleaseLib% DatabaseGenerateMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticX64DebugLib% DatabaseGenerateMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticX64ReleaseLib% DatabaseGenerateMiddleLayerTesting.exe

pause