@echo on
 
start /d %MillenniumHistoryTestingWin32DebugLib% DatabaseServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingWin32ReleaseLib% DatabaseServerMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingX64DebugLib% DatabaseServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingX64ReleaseLib% DatabaseServerMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingStaticWin32DebugLib% DatabaseServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingStaticWin32ReleaseLib% DatabaseServerMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingStaticX64DebugLib% DatabaseServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingStaticX64ReleaseLib% DatabaseServerMiddleLayerTestingStatic.exe

start /d %MillenniumHistoryTestingEngineStaticGameDynamicWin32DebugLib% DatabaseServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicWin32ReleaseLib% DatabaseServerMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicX64DebugLib% DatabaseServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicX64ReleaseLib% DatabaseServerMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticWin32DebugLib% DatabaseServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticWin32ReleaseLib% DatabaseServerMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticX64DebugLib% DatabaseServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticX64ReleaseLib% DatabaseServerMiddleLayerTesting.exe

pause