@echo on
 
start /d %MillenniumHistoryTestingWin32DebugLib% FightingServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingWin32ReleaseLib% FightingServerMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingX64DebugLib% FightingServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingX64ReleaseLib% FightingServerMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingStaticWin32DebugLib% FightingServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingStaticWin32ReleaseLib% FightingServerMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingStaticX64DebugLib% FightingServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingStaticX64ReleaseLib% FightingServerMiddleLayerTestingStatic.exe

start /d %MillenniumHistoryTestingEngineStaticGameDynamicWin32DebugLib% FightingServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicWin32ReleaseLib% FightingServerMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicX64DebugLib% FightingServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicX64ReleaseLib% FightingServerMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticWin32DebugLib% FightingServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticWin32ReleaseLib% FightingServerMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticX64DebugLib% FightingServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticX64ReleaseLib% FightingServerMiddleLayerTesting.exe

pause