@echo on
 
start /d %MillenniumHistoryTestingWin32DebugLib% GatewayServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingWin32ReleaseLib% GatewayServerMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingX64DebugLib% GatewayServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingX64ReleaseLib% GatewayServerMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingStaticWin32DebugLib% GatewayServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingStaticWin32ReleaseLib% GatewayServerMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingStaticX64DebugLib% GatewayServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingStaticX64ReleaseLib% GatewayServerMiddleLayerTestingStatic.exe

start /d %MillenniumHistoryTestingEngineStaticGameDynamicWin32DebugLib% GatewayServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicWin32ReleaseLib% GatewayServerMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicX64DebugLib% GatewayServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicX64ReleaseLib% GatewayServerMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticWin32DebugLib% GatewayServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticWin32ReleaseLib% GatewayServerMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticX64DebugLib% GatewayServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticX64ReleaseLib% GatewayServerMiddleLayerTesting.exe

pause