@echo on
 
start /d %MillenniumHistoryTestingWin32DebugLib% LeaderboardServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingWin32ReleaseLib% LeaderboardServerMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingX64DebugLib% LeaderboardServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingX64ReleaseLib% LeaderboardServerMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingStaticWin32DebugLib% LeaderboardServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingStaticWin32ReleaseLib% LeaderboardServerMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingStaticX64DebugLib% LeaderboardServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingStaticX64ReleaseLib% LeaderboardServerMiddleLayerTestingStatic.exe

start /d %MillenniumHistoryTestingEngineStaticGameDynamicWin32DebugLib% LeaderboardServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicWin32ReleaseLib% LeaderboardServerMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicX64DebugLib% LeaderboardServerMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicX64ReleaseLib% LeaderboardServerMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticWin32DebugLib% LeaderboardServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticWin32ReleaseLib% LeaderboardServerMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticX64DebugLib% LeaderboardServerMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticX64ReleaseLib% LeaderboardServerMiddleLayerTesting.exe

pause