@echo on
 
start /d %MillenniumHistoryTestingWin32DebugLib% MessageClientMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingWin32ReleaseLib% MessageClientMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingX64DebugLib% MessageClientMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingX64ReleaseLib% MessageClientMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingStaticWin32DebugLib% MessageClientMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingStaticWin32ReleaseLib% MessageClientMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingStaticX64DebugLib% MessageClientMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingStaticX64ReleaseLib% MessageClientMiddleLayerTestingStatic.exe

start /d %MillenniumHistoryTestingEngineStaticGameDynamicWin32DebugLib% MessageClientMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicWin32ReleaseLib% MessageClientMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicX64DebugLib% MessageClientMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicX64ReleaseLib% MessageClientMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticWin32DebugLib% MessageClientMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticWin32ReleaseLib% MessageClientMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticX64DebugLib% MessageClientMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticX64ReleaseLib% MessageClientMiddleLayerTesting.exe

pause