@echo on
 
start /d %MillenniumHistoryTestingWin32DebugLib% RobotClientMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingWin32ReleaseLib% RobotClientMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingX64DebugLib% RobotClientMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingX64ReleaseLib% RobotClientMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingStaticWin32DebugLib% RobotClientMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingStaticWin32ReleaseLib% RobotClientMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingStaticX64DebugLib% RobotClientMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingStaticX64ReleaseLib% RobotClientMiddleLayerTestingStatic.exe

start /d %MillenniumHistoryTestingEngineStaticGameDynamicWin32DebugLib% RobotClientMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicWin32ReleaseLib% RobotClientMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicX64DebugLib% RobotClientMiddleLayerTestingStaticD.exe
start /d %MillenniumHistoryTestingEngineStaticGameDynamicX64ReleaseLib% RobotClientMiddleLayerTestingStatic.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticWin32DebugLib% RobotClientMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticWin32ReleaseLib% RobotClientMiddleLayerTesting.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticX64DebugLib% RobotClientMiddleLayerTestingD.exe
start /d %MillenniumHistoryTestingEngineDynamicGameStaticX64ReleaseLib% RobotClientMiddleLayerTesting.exe

pause