// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.0.3 (2019/10/02 13:56)

#ifndef OPENCV_LIB_EXAMPLE_DLL_H
#define OPENCV_LIB_EXAMPLE_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(OPENCV_LIB_EXAMPLE_NO_IMPORT) || defined(BUILDING_OPENCV_LIB_EXAMPLE_STATIC)

  #define OPENCV_LIB_EXAMPLE_DEFAULT_DECLARE
  #define OPENCV_LIB_EXAMPLE_HIDDEN_DECLARE
  #define OPENCV_LIB_EXAMPLE_VISIBLE

#else // !defined(OPENCV_LIB_EXAMPLE_NO_IMPORT) && !defined(OPENCV_LIB_EXAMPLE_STATIC)

   #if defined(OPENCV_LIB_EXAMPLE_EXPORT)
 
        #define OPENCV_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define OPENCV_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(OPENCV_LIB_EXAMPLE_EXPORT)

		#define OPENCV_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define OPENCV_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // OPENCV_LIB_EXAMPLE_EXPORT

   #define OPENCV_LIB_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(OPENCV_LIB_EXAMPLE_NO_IMPORT) || defined(OPENCV_LIB_EXAMPLE_STATIC)

#endif // OPENCV_LIB_EXAMPLE_DLL_H
