///	Copyright (c) 2010-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎版本：0.6.0.0 (2020/12/15 11:08)

#ifndef MATHEMATICS_DISTANCE_DISTANCE_RAY3_RECTANGLE3_DETAIL_H
#define MATHEMATICS_DISTANCE_DISTANCE_RAY3_RECTANGLE3_DETAIL_H

#include "DistanceRay3Rectangle3.h"

#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_DISTANCE_RAY3_RECTANGLE3_ACHIEVE)

    #include "DistanceRay3Rectangle3Achieve.h"

#endif  // !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_DISTANCE_RAY3_RECTANGLE3_ACHIEVE)

#endif  // MATHEMATICS_DISTANCE_DISTANCE_RAY3_RECTANGLE3_DETAIL_H