///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	版本：0.9.1.6 (2023/10/27 16:32)

#ifndef MATHEMATICS_DISTANCE_DISTANCE_LINE3_SEGMENT3_DETAIL_H
#define MATHEMATICS_DISTANCE_DISTANCE_LINE3_SEGMENT3_DETAIL_H

#include "DistanceLine3Segment3.h"

#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_DISTANCE_LINE3_SEGMENT3_ACHIEVE)

    #include "DistanceLine3Segment3Achieve.h"

#endif  // !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_DISTANCE_LINE3_SEGMENT3_ACHIEVE)

#endif  // MATHEMATICS_DISTANCE_DISTANCE_LINE3_SEGMENT3_DETAIL_H
