///	Copyright (c) 2010-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎版本：0.5.2.5 (2020/12/10 12:53)

#ifndef MATHEMATICS_DISTANCE_DISTANCE_RAY3_SEGMENT3_DEATIL_H
#define MATHEMATICS_DISTANCE_DISTANCE_RAY3_SEGMENT3_DEATIL_H 

#include "DistanceRay3Segment3.h" 

#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_DISTANCE_RAY3_SEGMENT3_ACHIEVE)

    #include "DistanceRay3Segment3Achieve.h"

#endif  // !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_DISTANCE_RAY3_SEGMENT3_ACHIEVE)

#endif // MATHEMATICS_DISTANCE_DISTANCE_RAY3_SEGMENT3_DEATIL_H
