///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	版本：0.9.1.2 (2023/07/25 16:16)

#ifndef SCENE_OBJECT_DLL_H
#define SCENE_OBJECT_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_SCENE_OBJECT_NO_IMPORT) || defined(BUILDING_SCENE_OBJECT_STATIC)

    #define SCENE_OBJECT_DEFAULT_DECLARE
    #define SCENE_OBJECT_VISIBLE

    #if defined(BUILDING_SCENE_OBJECT_EXPORT)

        #define SCENE_OBJECT_HIDDEN_DECLARE

    #else  // !defined(BUILDING_SCENE_OBJECT_EXPORT)

        #define SCENE_OBJECT_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_SCENE_OBJECT_EXPORT

#else  // !defined(BUILDING_SCENE_OBJECT_NO_IMPORT) && !defined(BUILDING_SCENE_OBJECT_STATIC)

    #if defined(BUILDING_SCENE_OBJECT_EXPORT)

        #define SCENE_OBJECT_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define SCENE_OBJECT_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_SCENE_OBJECT_EXPORT)

        #define SCENE_OBJECT_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define SCENE_OBJECT_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_SCENE_OBJECT_EXPORT

    #define SCENE_OBJECT_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_SCENE_OBJECT_NO_IMPORT) || defined(BUILDING_SCENE_OBJECT_STATIC)

#endif  // SCENE_OBJECT_DLL_H
