///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	引擎版本：0.9.0.11 (2023/06/08 17:35)

#ifndef MATHEMATICS_APPROXIMATION_ORTHOGONAL_LINT_FIT2_DETAIL_H
#define MATHEMATICS_APPROXIMATION_ORTHOGONAL_LINT_FIT2_DETAIL_H

#include "OrthogonalLineFit2.h"

#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_ORTHOGONAL_LINE_FIT2_ACHIEVE)

    #include "OrthogonalLineFit2Achieve.h"

#endif  //  !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_ORTHOGONAL_LINE_FIT2_ACHIEVE)

#endif  // MATHEMATICS_APPROXIMATION_ORTHOGONAL_LINT_FIT2_DETAIL_H
