///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	版本：0.9.1.6 (2023/10/27 14:21)

#ifndef MATHEMATICS_APPROXIMATION_QUADRATIC_CIRCLE_FIT2_DETAIL_H
#define MATHEMATICS_APPROXIMATION_QUADRATIC_CIRCLE_FIT2_DETAIL_H

#include "QuadraticCircleFit2.h"

#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_QUADRATIC_CIRCLE_FIT2_ACHIEVE)

    #include "QuadraticCircleFit2Achieve.h"

#endif  //  !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_QUADRATIC_CIRCLE_FIT2_ACHIEVE)

#endif  // MATHEMATICS_APPROXIMATION_QUADRATIC_CIRCLE_FIT2_DETAIL_H
