///	Copyright (c) 2010-2022
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎版本：0.8.0.2 (2022/02/17 18:09)

#ifndef MATHEMATICS_APPROXIMATION_QUADRATIC_CIRCLE_FIT2_DETAIL_H
#define MATHEMATICS_APPROXIMATION_QUADRATIC_CIRCLE_FIT2_DETAIL_H

#include "QuadraticCircleFit2.h"

#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_QUADRATIC_CIRCLE_FIT2_ACHIEVE)

    #include "QuadraticCircleFit2Achieve.h"

#endif  //  !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_QUADRATIC_CIRCLE_FIT2_ACHIEVE)

#endif  // MATHEMATICS_APPROXIMATION_QUADRATIC_CIRCLE_FIT2_DETAIL_H
