// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.1.0.1 (2020/04/06 14:20)

#ifndef BOOK_GEOMETRY_DLL_H
#define BOOK_GEOMETRY_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Helper/UserMacro.h"

#if defined(BUILDING_BOOK_GEOMETRY_NO_IMPORT) || defined(BUILDING_BOOK_GEOMETRY_STATIC)

  #define BOOK_GEOMETRY_DEFAULT_DECLARE
  #define BOOK_GEOMETRY_HIDDEN_DECLARE 
  #define BOOK_GEOMETRY_VISIBLE

#else // !defined(BUILDING_BOOK_GEOMETRY_NO_IMPORT) && !defined(BUILDING_BOOK_GEOMETRY_STATIC)
 
   #if defined(BUILDING_BOOK_GEOMETRY_EXPORT)
 
        #define BOOK_GEOMETRY_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define BOOK_GEOMETRY_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_BOOK_GEOMETRY_EXPORT)

		#define BOOK_GEOMETRY_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define BOOK_GEOMETRY_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_BOOK_GEOMETRY_EXPORT

   #define BOOK_GEOMETRY_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_BOOK_GEOMETRY_NO_IMPORT) || defined(BUILDING_BOOK_GEOMETRY_STATIC)
 
#endif // BOOK_GEOMETRY_DLL_H
