///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	版本：0.9.1.2 (2023/07/31 15:25)

#ifndef EFFECT_EDITOR_MACRO_USER_MACRO_H
#define EFFECT_EDITOR_MACRO_USER_MACRO_H

#include "System/Helper/ConfigMacro.h"
#include "CoreTools/Helper/UserMacro.h"

#define EFFECT_EDITOR_ClOSE_BEGIN (0x01)

#define CLOSE_USE_EFFECT_EDITOR (EFFECT_EDITOR_ClOSE_BEGIN)

#define EFFECT_EDITOR_ClOSE_END CLOSE_USE_EFFECT_EDITOR

#define CLOSE_EFFECT_EDITOR_MAX (((EFFECT_EDITOR_ClOSE_END) << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_EFFECT_EDITOR_CLOSE 0x00

static_assert(0 <= COMPILE_EFFECT_EDITOR_CLOSE, "COMPILE_EFFECT_EDITOR_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_EFFECT_EDITOR_CLOSE <= CLOSE_EFFECT_EDITOR_MAX, "COMPILE_EFFECT_EDITOR_CLOSE Must be less than or equal CLOSE_EFFECT_EDITOR_MAX.");

#if !defined(COMPILE_EFFECT_EDITOR_CLOSE) || (COMPILE_EFFECT_EDITOR_CLOSE & CLOSE_USE_EFFECT_EDITOR) != CLOSE_USE_EFFECT_EDITOR

#endif  // !defined(COMPILE_EFFECT_EDITOR_CLOSE) || (COMPILE_EFFECT_EDITOR_CLOSE & CLOSE_USE_EFFECT_EDITOR) != CLOSE_USE_EFFECT_EDITOR

#ifdef BUILDING_STATIC

    #define BUILDING_EFFECT_EDITOR_STATIC

#endif  // BUILDING_STATIC

#endif  // EFFECT_EDITOR_MACRO_USER_MACRO_H
