///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	版本：0.9.1.3 (2023/08/02 14:05)

#ifndef PHYSICS_MACRO_USER_MACRO_H
#define PHYSICS_MACRO_USER_MACRO_H

#include "System/Helper/ConfigMacro.h"
#include "CoreTools/Helper/UserMacro.h"
#include "Mathematics/Helper/UserMacro.h"

#define PHYSICS_ClOSE_BEGIN (0x01)

#define CLOSE_PHYSICS_USE_EXPORT_TEMPLATE (PHYSICS_ClOSE_BEGIN)
#define CLOSE_LCP_SOLVER_LOG (PHYSICS_ClOSE_BEGIN << 1)
#define CLOSE_LCP_POLY_DIST_LOG (PHYSICS_ClOSE_BEGIN << 2)
#define CLOSE_USE_PHYSICS_TEMPLATE_TEST (PHYSICS_ClOSE_BEGIN << 3)  // 默认关闭

#define PHYSICS_ClOSE_END CLOSE_USE_PHYSICS_TEMPLATE_TEST

#define CLOSE_PHYSICS_MAX (((PHYSICS_ClOSE_END) << 1) - 1)

// 编译测试（默认为0x08，最大值为0x0F）
#define COMPILE_PHYSICS_CLOSE 0x00

static_assert(0 <= COMPILE_PHYSICS_CLOSE, "COMPILE_PHYSICS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_PHYSICS_CLOSE <= CLOSE_PHYSICS_MAX, "COMPILE_PHYSICS_CLOSE Must be less than or equal CLOSE_MATHEMATICS_MAX.");

#if !defined(COMPILE_PHYSICS_CLOSE) || (COMPILE_PHYSICS_CLOSE & CLOSE_PHYSICS_USE_EXPORT_TEMPLATE) != CLOSE_PHYSICS_USE_EXPORT_TEMPLATE

    #define PHYSICS_EXPORT_TEMPLATE

#endif  // !defined(COMPILE_PHYSICS_CLOSE) || (COMPILE_PHYSICS_CLOSE & CLOSE_PHYSICS_USE_EXPORT_TEMPLATE) != CLOSE_PHYSICS_USE_EXPORT_TEMPLATE

#ifdef PHYSICS_EXPORT_TEMPLATE

    #define PHYSICS_TEMPLATE_DEFAULT_DECLARE PHYSICS_DEFAULT_DECLARE

#else  // !PHYSICS_EXPORT_TEMPLATE

    #define PHYSICS_TEMPLATE_DEFAULT_DECLARE

#endif  // PHYSICS_EXPORT_TEMPLATE

#if !defined(COMPILE_PHYSICS_CLOSE) || (COMPILE_PHYSICS_CLOSE & CLOSE_LCP_SOLVER_LOG) != CLOSE_LCP_SOLVER_LOG

    #define PHYSICS_LCP_SOLVER_LOG

#endif  // !defined(COMPILE_PHYSICS_CLOSE) || (COMPILE_PHYSICS_CLOSE & CLOSE_LCP_SOLVER_LOG) != CLOSE_LCP_SOLVER_LOG

#if !defined(COMPILE_PHYSICS_CLOSE) || (COMPILE_PHYSICS_CLOSE & CLOSE_LCP_POLY_DIST_LOG) != CLOSE_LCP_POLY_DIST_LOG

    #define PHYSICS_LCP_POLY_DIST_LOG

#endif  // !defined(COMPILE_PHYSICS_CLOSE) || (COMPILE_PHYSICS_CLOSE & CLOSE_LCP_POLY_DIST_LOG) != CLOSE_LCP_POLY_DIST_LOG

// 对于LCPSolver的测试和调试期间消息写入日志文件
#ifdef PHYSICS_LCP_SOLVER_LOG

    #define PHYSICS_LCP_SOLVER_FUNCTION(func) func

#else  // !PHYSICS_LCP_SOLVER_LOG

    #define PHYSICS_LCP_SOLVER_FUNCTION(func)

#endif  // PHYSICS_LCP_SOLVER_LOG

// 对于LCPPolynomialDistance的测试和调试期间消息写入日志文件。如果启用此，在计算距离时显示会显著减慢。
#ifdef PHYSICS_LCP_POLY_DIST_LOG

    #define PHYSICS_LCP_POLY_DIST_FUNCTION(func) func

#else  // !PHYSICS_LCP_POLY_DIST_LOG

    #define PHYSICS_LCP_POLY_DIST_FUNCTION(func)

#endif  // PHYSICS_LCP_POLY_DIST_LOG

#if !defined(COMPILE_PHYSICS_CLOSE) || (COMPILE_PHYSICS_CLOSE & CLOSE_USE_PHYSICS_TEMPLATE_TEST) != CLOSE_USE_PHYSICS_TEMPLATE_TEST

    #ifndef BUILDING_STATIC

        #define PHYSICS_TEMPLATE_TEST static_cast<void>(0)

    #endif  // BUILDING_STATIC

#endif  // !defined(COMPILE_PHYSICS_CLOSE) || (COMPILE_PHYSICS_CLOSE & CLOSE_USE_PHYSICS_TEMPLATE_TEST) != CLOSE_USE_PHYSICS_TEMPLATE_TEST

#ifdef BUILDING_STATIC

    #define BUILDING_PHYSICS_STATIC static_cast<void>(0)

#endif  // BUILDING_STATIC

#endif  // PHYSICS_MACRO_USER_MACRO_H
