///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.0 (2021/01/30 11:03)

#ifndef CRYPTOGRAPHY_FOR_DEVELOPERS_HELPER_USER_MACRO_H
#define CRYPTOGRAPHY_FOR_DEVELOPERS_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define CRYPTOGRAPHY_FOR_DEVELOPERS_ClOSE_BEGIN (0x01)

#define CLOSE_USE_CRYPTOGRAPHY_FOR_DEVELOPERS (CRYPTOGRAPHY_FOR_DEVELOPERS_ClOSE_BEGIN)

#define CRYPTOGRAPHY_FOR_DEVELOPERS_ClOSE_END CLOSE_USE_CRYPTOGRAPHY_FOR_DEVELOPERS

#define CLOSE_CRYPTOGRAPHY_FOR_DEVELOPERS_MAX ((CRYPTOGRAPHY_FOR_DEVELOPERS_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_CRYPTOGRAPHY_FOR_DEVELOPERS_CLOSE 0x00

static_assert(0 <= COMPILE_CRYPTOGRAPHY_FOR_DEVELOPERS_CLOSE, "COMPILE_CRYPTOGRAPHY_FOR_DEVELOPERS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_CRYPTOGRAPHY_FOR_DEVELOPERS_CLOSE <= CLOSE_CRYPTOGRAPHY_FOR_DEVELOPERS_MAX, "COMPILE_CRYPTOGRAPHY_FOR_DEVELOPERS_CLOSE Must be less than or equal CLOSE_CRYPTOGRAPHY_FOR_DEVELOPERS_MAX.");

#if !defined(COMPILE_CRYPTOGRAPHY_FOR_DEVELOPERS_CLOSE) || (COMPILE_CRYPTOGRAPHY_FOR_DEVELOPERS_CLOSE & CLOSE_USE_CRYPTOGRAPHY_FOR_DEVELOPERS) != CLOSE_USE_CRYPTOGRAPHY_FOR_DEVELOPERS

#endif  // !defined(COMPILE_CRYPTOGRAPHY_FOR_DEVELOPERS_CLOSE) || (COMPILE_CRYPTOGRAPHY_FOR_DEVELOPERS_CLOSE & CLOSE_USE_CRYPTOGRAPHY_FOR_DEVELOPERS) != CLOSE_USE_CRYPTOGRAPHY_FOR_DEVELOPERS

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_CRYPTOGRAPHY_FOR_DEVELOPERS_STATIC
#endif  // BUILDING_STATIC

#endif  // CRYPTOGRAPHY_FOR_DEVELOPERS_HELPER_USER_MACRO_H
