///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.1 (2021/03/11 17:52)

#ifndef INSIDE_THE_CPP_OBJECT_MODEL_DLL_H
#define INSIDE_THE_CPP_OBJECT_MODEL_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_INSIDE_THE_CPP_OBJECT_MODEL_NO_IMPORT) || defined(BUILDING_INSIDE_THE_CPP_OBJECT_MODEL_STATIC)

    #define INSIDE_THE_CPP_OBJECT_MODEL_DEFAULT_DECLARE
    #define INSIDE_THE_CPP_OBJECT_MODEL_VISIBLE

    #if defined(BUILDING_INSIDE_THE_CPP_OBJECT_MODEL_EXPORT)

        #define INSIDE_THE_CPP_OBJECT_MODEL_HIDDEN_DECLARE

    #else  // !defined(BUILDING_INSIDE_THE_CPP_OBJECT_MODEL_EXPORT)

        #define INSIDE_THE_CPP_OBJECT_MODEL_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_INSIDE_THE_CPP_OBJECT_MODEL_EXPORT

#else  // !defined(BUILDING_INSIDE_THE_CPP_OBJECT_MODEL_NO_IMPORT) && !defined(BUILDING_INSIDE_THE_CPP_OBJECT_MODEL_STATIC)

    #if defined(BUILDING_INSIDE_THE_CPP_OBJECT_MODEL_EXPORT)

        #define INSIDE_THE_CPP_OBJECT_MODEL_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define INSIDE_THE_CPP_OBJECT_MODEL_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_INSIDE_THE_CPP_OBJECT_MODEL_EXPORT)

        #define INSIDE_THE_CPP_OBJECT_MODEL_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define INSIDE_THE_CPP_OBJECT_MODEL_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_INSIDE_THE_CPP_OBJECT_MODEL_EXPORT

    #define INSIDE_THE_CPP_OBJECT_MODEL_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_INSIDE_THE_CPP_OBJECT_MODEL_NO_IMPORT) || defined(BUILDING_INSIDE_THE_CPP_OBJECT_MODEL_STATIC)

#endif  // INSIDE_THE_CPP_OBJECT_MODEL_DLL_H
