///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.0 (2021/07/18 18:43)

#ifndef NETWORKED_GRAPHICS_BUILDING_NETWORKED_GAMES_AND_VIRTUAL_ENVIRONMENTS_NO_IMPORT_H
#define NETWORKED_GRAPHICS_BUILDING_NETWORKED_GAMES_AND_VIRTUAL_ENVIRONMENTS_NO_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_NETWORKED_GRAPHICS_BUILDING_NETWORKED_GAMES_AND_VIRTUAL_ENVIRONMENTS_NO_IMPORT
    #define BUILDING_NETWORKED_GRAPHICS_BUILDING_NETWORKED_GAMES_AND_VIRTUAL_ENVIRONMENTS_NO_IMPORT
#endif  // BUILDING_NETWORKED_GRAPHICS_BUILDING_NETWORKED_GAMES_AND_VIRTUAL_ENVIRONMENTS_NO_IMPORT

#endif  // NETWORKED_GRAPHICS_BUILDING_NETWORKED_GAMES_AND_VIRTUAL_ENVIRONMENTS_NO_IMPORT_H
