///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.1 (2021/01/08 21:29)

#ifndef EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_EXPORT_H
#define EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_EXPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_EXPORT
    #define BUILDING_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_EXPORT
#endif  // BUILDING_EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_EXPORT

#endif  // EFFICIENT_CPP_PERFORMANCE_PROGRAMMING_TECHNIQUES_EXPORT_H
