// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.1 (2020/01/19 22:19)

#ifndef MATERIAL_EDITOR_DLL_DLL_H
#define MATERIAL_EDITOR_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(BUILDING_MATERIAL_EDITOR_NO_IMPORT) || defined(BUILDING_MATERIAL_EDITOR_STATIC)

  #define MATERIAL_EDITOR_DEFAULT_DECLARE
  #define MATERIAL_EDITOR_HIDDEN_DECLARE
  #define MATERIAL_EDITOR_VISIBLE

#else // !defined(BUILDING_MATERIAL_EDITOR_NO_IMPORT) && !defined(BUILDING_MATERIAL_EDITOR_STATIC)

   #if defined(BUILDING_MATERIAL_EDITOR_EXPORT)
 
        #define MATERIAL_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define MATERIAL_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_MATERIAL_EDITOR_EXPORT)

		#define MATERIAL_EDITOR_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define MATERIAL_EDITOR_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_MATERIAL_EDITOR_EXPORT

   #define MATERIAL_EDITOR_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_MATERIAL_EDITORNO_IMPORT) || defined(BUILDING_MATERIAL_EDITOR_STATIC)

#endif // MATERIAL_EDITOR_DLL_DLL_H
