///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.1 (2021/03/11 17:52)

#ifndef CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_DLL_H
#define CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_NO_IMPORT) || defined(BUILDING_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_STATIC)

    #define CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_DEFAULT_DECLARE
    #define CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_VISIBLE

    #if defined(BUILDING_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_EXPORT)

        #define CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_HIDDEN_DECLARE

    #else  // !defined(BUILDING_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_EXPORT)

        #define CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_EXPORT

#else  // !defined(BUILDING_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_NO_IMPORT) && !defined(BUILDING_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_STATIC)

    #if defined(BUILDING_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_EXPORT)

        #define CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_EXPORT)

        #define CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_EXPORT

    #define CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_NO_IMPORT) || defined(BUILDING_CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_STATIC)

#endif  // CLEAN_CPP_SUSTAINABLE_SOFTWARE_DEVELOPMENT_DLL_H
