///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.1 (2021/02/09 14:57)

#ifndef THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_HELPER_USER_MACRO_H
#define THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_ClOSE_BEGIN (0x01)

#define CLOSE_USE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL (THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_ClOSE_BEGIN)

#define THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_ClOSE_END CLOSE_USE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL

#define CLOSE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_MAX ((THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_CLOSE 0x00

static_assert(0 <= COMPILE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_CLOSE, "COMPILE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_CLOSE <= CLOSE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_MAX, "COMPILE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_CLOSE Must be less than or equal CLOSE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_MAX.");

#if !defined(COMPILE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_CLOSE) || (COMPILE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_CLOSE & CLOSE_USE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL) != CLOSE_USE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL

#endif  // !defined(COMPILE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_CLOSE) || (COMPILE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_CLOSE & CLOSE_USE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL) != CLOSE_USE_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_STATIC
#endif  // BUILDING_STATIC

#endif  // THINKING_LOW_LEVEL_WRITING_HIGH_LEVEL_HELPER_USER_MACRO_H
