// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
// 
// “˝«Ê∞Ê±æ£∫0.0.2.0 (2020/01/02 15:03)

#ifndef SYSTEM_HELPER_GL_20_FLAGS_H
#define SYSTEM_HELPER_GL_20_FLAGS_H

#include "System/Helper/UserMacro.h"

namespace System
{
	enum class GL20Flags
	{
		BlendEquationSeparate,
		DrawBuffers,
		StencilOpSeparate,
		StencilFuncSeparate,
		StencilMaskSeparate,
		AttachShader,
		BindAttribLocation,
		CompileShader,
		CreateProgram,
		CreateShader,
		DeleteProgram,
		DeleteShader,
		DetachShader,
		DisableVertexAttribArray,
		EnableVertexAttribArray,
		GetActiveAttrib,
		GetActiveUniform,
		GetAttachedShaders,
		GetAttribLocation,
		GetProgramiv,
		GetProgramInfoLog,
		GetShaderiv,
		GetShaderInfoLog,
		GetShaderSource,
		GetUniformLocation,
		GetUniformfv,
		GetUniformiv,
		GetVertexAttribdv,
		GetVertexAttribfv,
		GetVertexAttribiv,
		GetVertexAttribPointerv,
		IsProgram,
		IsShader,
		LinkProgram,
		ShaderSource,
		UseProgram,
		Uniform1f,
		Uniform2f,
		Uniform3f,
		Uniform4f,
		Uniform1i,
		Uniform2i,
		Uniform3i,
		Uniform4i,
		Uniform1fv,
		Uniform2fv,
		Uniform3fv,
		Uniform4fv,
		Uniform1iv,
		Uniform2iv,
		Uniform3iv,
		Uniform4iv,
		UniformMatrix2fv,
		UniformMatrix3fv,
		UniformMatrix4fv,
		ValidateProgram,
		VertexAttrib1d,
		VertexAttrib1dv,
		VertexAttrib1f,
		VertexAttrib1fv,
		VertexAttrib1s,
		VertexAttrib1sv,
		VertexAttrib2d,
		VertexAttrib2dv,
		VertexAttrib2f,
		VertexAttrib2fv,
		VertexAttrib2s,
		VertexAttrib2sv,
		VertexAttrib3d,
		VertexAttrib3dv,
		VertexAttrib3f,
		VertexAttrib3fv,
		VertexAttrib3s,
		VertexAttrib3sv,
		VertexAttrib4Nbv,
		VertexAttrib4Niv,
		VertexAttrib4Nsv,
		VertexAttrib4Nub,
		VertexAttrib4Nubv,
		VertexAttrib4Nuiv,
		VertexAttrib4Nusv,
		VertexAttrib4bv,
		VertexAttrib4d,
		VertexAttrib4dv,
		VertexAttrib4f,
		VertexAttrib4fv,
		VertexAttrib4iv,
		VertexAttrib4s,
		VertexAttrib4sv,
		VertexAttrib4ubv,
		VertexAttrib4uiv,
		VertexAttrib4usv,
		VertexAttribPointer,
	};
}

#endif // SYSTEM_HELPER_GL_20_FLAGS_H
