///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.0 (2021/01/30 11:02)

#ifndef INTRODUCTION_TO_ALGORITHMS_THIRD_EDITION_NO_IMPORT_H
#define INTRODUCTION_TO_ALGORITHMS_THIRD_EDITION_NO_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_INTRODUCTION_TO_ALGORITHMS_THIRD_EDITION_NO_IMPORT
    #define BUILDING_INTRODUCTION_TO_ALGORITHMS_THIRD_EDITION_NO_IMPORT
#endif  // BUILDING_INTRODUCTION_TO_ALGORITHMS_THIRD_EDITION_NO_IMPORT

#endif  // INTRODUCTION_TO_ALGORITHMS_THIRD_EDITION_NO_IMPORT_H
