///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.1 (2021/02/09 14:57)

#ifndef PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_EXPORT_H
#define PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_EXPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_EXPORT
    #define BUILDING_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_EXPORT
#endif  // BUILDING_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_EXPORT

#endif  // PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_EXPORT_H
