///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.1 (2021/02/09 14:57)

#ifndef PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_DLL_H
#define PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_NO_IMPORT) || defined(BUILDING_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_STATIC)

    #define PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_DEFAULT_DECLARE
    #define PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_HIDDEN_DECLARE
    #define PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_VISIBLE

#else  // !defined(BUILDING_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_NO_IMPORT) && !defined(BUILDING_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_STATIC)

    #if defined(BUILDING_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_EXPORT)

        #define PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_EXPORT)

        #define PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_EXPORT

    #define PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_NO_IMPORT) || defined(BUILDING_PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_STATIC)

#endif  // PRACTICAL_ALGORITHMS_FOR_PROGRAMMERS_DLL_H
