///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.3 (2021/09/22 21:06)

#ifndef CRYPTOGRAPHY_AND_NETWORK_SECURITY_NO_IMPORT_H
#define CRYPTOGRAPHY_AND_NETWORK_SECURITY_NO_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_CRYPTOGRAPHY_AND_NETWORK_SECURITY_NO_IMPORT
    #define BUILDING_CRYPTOGRAPHY_AND_NETWORK_SECURITY_NO_IMPORT
#endif  // BUILDING_CRYPTOGRAPHY_AND_NETWORK_SECURITY_NO_IMPORT

#endif  // CRYPTOGRAPHY_AND_NETWORK_SECURITY_NO_IMPORT_H
