// Copyright (c) 2011-2019
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.0.3 (2019/10/02 15:09)

#ifndef ZLIB_LIB_EXAMPLE_DLL_H
#define ZLIB_LIB_EXAMPLE_DLL_H

#include "System/Helper/ExportMacro.h"
#include "Macro/UserMacro.h"

#if defined(ZLIB_LIB_EXAMPLE_NO_IMPORT) || defined(BUILDING_ZLIB_LIB_EXAMPLE_STATIC)

  #define ZLIB_LIB_EXAMPLE_DEFAULT_DECLARE
  #define ZLIB_LIB_EXAMPLE_HIDDEN_DECLARE
  #define ZLIB_LIB_EXAMPLE_VISIBLE

#else // !defined(ZLIB_LIB_EXAMPLE_NO_IMPORT) && !defined(ZLIB_LIB_EXAMPLE_STATIC)

   #if defined(ZLIB_LIB_EXAMPLE_EXPORT)
 
        #define ZLIB_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define ZLIB_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(ZLIB_LIB_EXAMPLE_EXPORT)

		#define ZLIB_LIB_EXAMPLE_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define ZLIB_LIB_EXAMPLE_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // ZLIB_LIB_EXAMPLE_EXPORT

   #define ZLIB_LIB_EXAMPLE_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(ZLIB_LIB_EXAMPLE_NO_IMPORT) || defined(ZLIB_LIB_EXAMPLE_STATIC)

#endif // ZLIB_LIB_EXAMPLE_DLL_H
