///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.0 (2021/01/24 13:05)

#ifndef CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_DLL_H
#define CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_NO_IMPORT) || defined(BUILDING_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_STATIC)

    #define CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_DEFAULT_DECLARE
    #define CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_HIDDEN_DECLARE
    #define CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_VISIBLE

#else  // !defined(BUILDING_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_NO_IMPORT) && !defined(BUILDING_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_STATIC)

    #if defined(BUILDING_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_EXPORT)

        #define CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_EXPORT)

        #define CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_EXPORT

    #define CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_NO_IMPORT) || defined(BUILDING_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_STATIC)

#endif  // CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_DLL_H
