///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.0 (2021/01/24 13:05)

#ifndef CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_IMPORT_H
#define CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_IMPORT
    #define BUILDING_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_IMPORT
#endif  // BUILDING_CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_IMPORT

#endif  // CORE_CPP_A_SOFTWARE_ENGINEARING_APPROACH_IMPORT_H
