///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.4 (2021/06/06 21:46)

#ifndef MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_NO_IMPORT_H
#define MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_NO_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_NO_IMPORT
    #define BUILDING_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_NO_IMPORT
#endif  // BUILDING_MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_NO_IMPORT

#endif  // MASTERING_COMPLEXITY_WITH_ACE_AND_PATTERNS_NO_IMPORT_H
