///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.0 (2021/01/30 11:03)

#ifndef DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_DLL_H
#define DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_NO_IMPORT) || defined(BUILDING_DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_STATIC)

    #define DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_DEFAULT_DECLARE
    #define DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_HIDDEN_DECLARE
    #define DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_VISIBLE

#else  // !defined(BUILDING_DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_NO_IMPORT) && !defined(BUILDING_DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_STATIC)

    #if defined(BUILDING_DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_EXPORT)

        #define DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_EXPORT)

        #define DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_EXPORT

    #define DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_NO_IMPORT) || defined(BUILDING_DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_STATIC)

#endif  // DISCRETE_MATHEMATICS_AND_ITS_APPLICATIONS_SEVENTH_EDITION_DLL_H
