///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.4 (2021/06/06 21:47)

#ifndef SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_HELPER_USER_MACRO_H
#define SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_ClOSE_BEGIN (0x01)

#define CLOSE_USE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS (SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_ClOSE_BEGIN)

#define SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_ClOSE_END CLOSE_USE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS

#define CLOSE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_MAX ((SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_CLOSE 0x00

static_assert(0 <= COMPILE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_CLOSE, "COMPILE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_CLOSE <= CLOSE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_MAX, "COMPILE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_CLOSE Must be less than or equal CLOSE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_MAX.");

#if !defined(COMPILE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_CLOSE) || (COMPILE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_CLOSE & CLOSE_USE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS) != CLOSE_USE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS

#endif  // !defined(COMPILE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_CLOSE) || (COMPILE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_CLOSE & CLOSE_USE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS) != CLOSE_USE_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS

#ifdef BUILDING_STATIC
    #define BUILDING_SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_STATIC
#endif  // BUILDING_STATIC

#endif  // SYSTEMATIC_REUSE_WITH_ACE_AND_FRAMEWORKS_HELPER_USER_MACRO_H
