// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.0 (2020/01/05 19:04)

#ifndef INPUT_OUTPUT_TOOLSET_DLL_DLL_H
#define INPUT_OUTPUT_TOOLSET_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "InputOutput/Helper/UserMacro.h"

#if defined(BUILDING_INPUT_OUTPUT_TOOLSET_NO_IMPORT) || defined(BUILDING_INPUT_OUTPUT_STATIC)

  #define INPUT_OUTPUT_TOOLSET_DEFAULT_DECLARE
  #define INPUT_OUTPUT_TOOLSET_HIDDEN_DECLARE
  #define INPUT_OUTPUT_TOOLSET_VISIBLE

#else // !defined(BUILDING_INPUT_OUTPUT_TOOLSET_NO_IMPORT) && !defined(BUILDING_INPUT_OUTPUT_STATIC)

   #if defined(BUILDING_INPUT_OUTPUT_TOOLSET_EXPORT)
 
        #define INPUT_OUTPUT_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define INPUT_OUTPUT_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_INPUT_OUTPUT_TOOLSET_EXPORT)

		#define INPUT_OUTPUT_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define INPUT_OUTPUT_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_INPUT_OUTPUT_TOOLSET_EXPORT

   #define INPUT_OUTPUT_TOOLSET_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_INPUT_OUTPUT_TOOLSET_NO_IMPORT) || defined(BUILDING_INPUT_OUTPUT_STATIC)

#endif // INPUT_OUTPUT_TOOLSET_DLL_DLL_H
