///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.0 (2021/07/18 18:43)

#ifndef MULTIPLAYER_GAME_PROGRAMMING_DLL_H
#define MULTIPLAYER_GAME_PROGRAMMING_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_MULTIPLAYER_GAME_PROGRAMMING_NO_IMPORT) || defined(BUILDING_MULTIPLAYER_GAME_PROGRAMMING_STATIC)

    #define MULTIPLAYER_GAME_PROGRAMMING_DEFAULT_DECLARE
    #define MULTIPLAYER_GAME_PROGRAMMING_VISIBLE

    #if defined(BUILDING_MULTIPLAYER_GAME_PROGRAMMING_EXPORT)

        #define MULTIPLAYER_GAME_PROGRAMMING_HIDDEN_DECLARE

    #else  // !defined(BUILDING_MULTIPLAYER_GAME_PROGRAMMING_EXPORT)

        #define MULTIPLAYER_GAME_PROGRAMMING_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_MULTIPLAYER_GAME_PROGRAMMING_EXPORT

#else  // !defined(BUILDING_MULTIPLAYER_GAME_PROGRAMMING_NO_IMPORT) && !defined(BUILDING_MULTIPLAYER_GAME_PROGRAMMING_STATIC)

    #if defined(BUILDING_MULTIPLAYER_GAME_PROGRAMMING_EXPORT)

        #define MULTIPLAYER_GAME_PROGRAMMING_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define MULTIPLAYER_GAME_PROGRAMMING_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_MULTIPLAYER_GAME_PROGRAMMING_EXPORT)

        #define MULTIPLAYER_GAME_PROGRAMMING_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define MULTIPLAYER_GAME_PROGRAMMING_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_MULTIPLAYER_GAME_PROGRAMMING_EXPORT

    #define MULTIPLAYER_GAME_PROGRAMMING_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_MULTIPLAYER_GAME_PROGRAMMING_NO_IMPORT) || defined(BUILDING_MULTIPLAYER_GAME_PROGRAMMING_STATIC)

#endif  // MULTIPLAYER_GAME_PROGRAMMING_DLL_H
