///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	千年史策版本：0.9.0.12 (2023/06/12 21:49)

#ifndef DATABASE_GENERATE_SERVER_CORE_IMPORT_H
#define DATABASE_GENERATE_SERVER_CORE_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_DATABASE_GENERATE_SERVER_CORE_IMPORT

    #define BUILDING_DATABASE_GENERATE_SERVER_CORE_IMPORT

#endif  // BUILDING_DATABASE_GENERATE_SERVER_CORE_IMPORT

#endif  // DATABASE_GENERATE_SERVER_CORE_IMPORT_H