///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.1 (2021/01/08 21:29)

#ifndef CPP_STRATEGIES_AND_TACTICS_HELPER_USER_MACRO_H
#define CPP_STRATEGIES_AND_TACTICS_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define CPP_STRATEGIES_AND_TACTICS_ClOSE_BEGIN (0x01)

#define CLOSE_USE_CPP_STRATEGIES_AND_TACTICS (CPP_STRATEGIES_AND_TACTICS_ClOSE_BEGIN)

#define CPP_STRATEGIES_AND_TACTICS_ClOSE_END CLOSE_USE_CPP_STRATEGIES_AND_TACTICS

#define CLOSE_CPP_STRATEGIES_AND_TACTICS_MAX ((CPP_STRATEGIES_AND_TACTICS_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_CPP_STRATEGIES_AND_TACTICS_CLOSE 0x00

static_assert(0 <= COMPILE_CPP_STRATEGIES_AND_TACTICS_CLOSE, "COMPILE_CPP_STRATEGIES_AND_TACTICS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_CPP_STRATEGIES_AND_TACTICS_CLOSE <= CLOSE_CPP_STRATEGIES_AND_TACTICS_MAX, "COMPILE_CPP_STRATEGIES_AND_TACTICS_CLOSE Must be less than or equal CLOSE_CPP_STRATEGIES_AND_TACTICS_MAX.");

#if !defined(COMPILE_CPP_STRATEGIES_AND_TACTICS_CLOSE) || (COMPILE_CPP_STRATEGIES_AND_TACTICS_CLOSE & CLOSE_USE_CPP_STRATEGIES_AND_TACTICS) != CLOSE_USE_CPP_STRATEGIES_AND_TACTICS

#endif  // !defined(COMPILE_CPP_STRATEGIES_AND_TACTICS_CLOSE) || (COMPILE_CPP_STRATEGIES_AND_TACTICS_CLOSE & CLOSE_USE_CPP_STRATEGIES_AND_TACTICS) != CLOSE_USE_CPP_STRATEGIES_AND_TACTICS

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_CPP_STRATEGIES_AND_TACTICS_STATIC
#endif  // BUILDING_STATIC

#endif  // CPP_STRATEGIES_AND_TACTICS_HELPER_USER_MACRO_H
