///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	版本：0.9.1.1 (2023/07/18 22:25)

#ifndef DATABASE_GENERATE_SERVER_MIDDLE_LAYER_EXPORT_H
#define DATABASE_GENERATE_SERVER_MIDDLE_LAYER_EXPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_DATABASE_GENERATE_SERVER_MIDDLE_LAYER_EXPORT

    #define BUILDING_DATABASE_GENERATE_SERVER_MIDDLE_LAYER_EXPORT

#endif  // BUILDING_DATABASE_GENERATE_SERVER_MIDDLE_LAYER_EXPORT

#endif  // DATABASE_GENERATE_SERVER_MIDDLE_LAYER_EXPORT_H