///	Copyright (c) 2010-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.0 (2020/12/26 23:18)

#ifndef ESSENTIAL_CPP_HELPER_USER_MACRO_H
#define ESSENTIAL_CPP_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define ESSENTIAL_CPP_ClOSE_BEGIN (0x01)

#define CLOSE_USE_ESSENTIAL_CPP (ESSENTIAL_CPP_ClOSE_BEGIN)

#define ESSENTIAL_CPP_ClOSE_END CLOSE_USE_ESSENTIAL_CPP

#define CLOSE_ESSENTIAL_CPP_MAX ((ESSENTIAL_CPP_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_ESSENTIAL_CPP_CLOSE 0x00

static_assert(0 <= COMPILE_ESSENTIAL_CPP_CLOSE, "COMPILE_ESSENTIAL_CPP_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_ESSENTIAL_CPP_CLOSE <= CLOSE_ESSENTIAL_CPP_MAX, "COMPILE_ESSENTIAL_CPP_CLOSE Must be less than or equal CLOSE_ESSENTIAL_CPP_MAX.");

#if !defined(COMPILE_ESSENTIAL_CPP_CLOSE) || (COMPILE_ESSENTIAL_CPP_CLOSE & CLOSE_USE_ESSENTIAL_CPP) != CLOSE_USE_ESSENTIAL_CPP

#endif  // !defined(COMPILE_ESSENTIAL_CPP_CLOSE) || (COMPILE_ESSENTIAL_CPP_CLOSE & CLOSE_USE_ESSENTIAL_CPP) != CLOSE_USE_ESSENTIAL_CPP

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_ESSENTIAL_CPP_STATIC
#endif  // BUILDING_STATIC

#endif  // ESSENTIAL_CPP_HELPER_USER_MACRO_H
