///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.0 (2021/01/30 11:03)

#ifndef INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_HELPER_USER_MACRO_H
#define INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_ClOSE_BEGIN (0x01)

#define CLOSE_USE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION (INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_ClOSE_BEGIN)

#define INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_ClOSE_END CLOSE_USE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION

#define CLOSE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_MAX ((INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_CLOSE 0x00

static_assert(0 <= COMPILE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_CLOSE, "COMPILE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_CLOSE <= CLOSE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_MAX, "COMPILE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_CLOSE Must be less than or equal CLOSE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_MAX.");

#if !defined(COMPILE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_CLOSE) || (COMPILE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_CLOSE & CLOSE_USE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION) != CLOSE_USE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION

#endif  // !defined(COMPILE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_CLOSE) || (COMPILE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_CLOSE & CLOSE_USE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION) != CLOSE_USE_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_STATIC
#endif  // BUILDING_STATIC

#endif  // INTRODUCTION_TO_ALGORITHMS_SECOND_EDITION_HELPER_USER_MACRO_H
