// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 引擎版本：0.0.0.2 (2019/07/16 14:27)

#ifndef SOUND_EFFECT_MACRO_USER_MACRO_H
#define SOUND_EFFECT_MACRO_USER_MACRO_H

#include "CoreTools/Helper/UserMacro.h"

#define CLOSE_USE_OPENAL (0x01) 
#define CLOSE_SOUND_EFFECT_MAX (((CLOSE_USE_OPENAL) << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_SOUND_EFFECT_CLOSE 0x00

static_assert(0 <= COMPILE_SOUND_EFFECT_CLOSE, "COMPILE_SOUND_EFFECT_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_SOUND_EFFECT_CLOSE <= CLOSE_SOUND_EFFECT_MAX, "COMPILE_SOUND_EFFECT_CLOSE Must be less than or equal CLOSE_SOUND_EFFECT_MAX.");

// 是否编译为静态库
#ifdef BUILDING_STATIC
	#define  BUILDING_SOUND_EFFECT_STATIC
#endif // BUILDING_STATIC

#if !defined(COMPILE_SOUND_EFFECT_CLOSE) || (COMPILE_SOUND_EFFECT_CLOSE & CLOSE_USE_OPENAL) != CLOSE_USE_OPENAL
	#define SOUND_EFFECT_USE_OPENAL
#endif // !defined(COMPILE_SOUND_EFFECT_CLOSE) || (COMPILE_SOUND_EFFECT_CLOSE & CLOSE_USE_OPENAL) != CLOSE_USE_OPENAL  
 
#endif // SOUND_EFFECT_MACRO_USER_MACRO_H
