///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.1 (2021/01/08 21:28)

#ifndef THE_CPP_PROGRAMMING_LANGUAGE_FOURTH_EDITION_IMPORT_H
#define THE_CPP_PROGRAMMING_LANGUAGE_FOURTH_EDITION_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_THE_CPP_PROGRAMMING_LANGUAGE_FOURTH_EDITION_IMPORT
    #define BUILDING_THE_CPP_PROGRAMMING_LANGUAGE_FOURTH_EDITION_IMPORT
#endif  // BUILDING_THE_CPP_PROGRAMMING_LANGUAGE_FOURTH_EDITION_IMPORT

#endif  // THE_CPP_PROGRAMMING_LANGUAGE_FOURTH_EDITION_IMPORT_H
