///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.5 (2021/10/28 22:19)

#ifndef MULTITHREADING_APPLICATIONS_IN_WIN32_DLL_H
#define MULTITHREADING_APPLICATIONS_IN_WIN32_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_MULTITHREADING_APPLICATIONS_IN_WIN32_NO_IMPORT) || defined(BUILDING_MULTITHREADING_APPLICATIONS_IN_WIN32_STATIC)

    #define MULTITHREADING_APPLICATIONS_IN_WIN32_DEFAULT_DECLARE
    #define MULTITHREADING_APPLICATIONS_IN_WIN32_VISIBLE

    #if defined(BUILDING_MULTITHREADING_APPLICATIONS_IN_WIN32_EXPORT)

        #define MULTITHREADING_APPLICATIONS_IN_WIN32_HIDDEN_DECLARE

    #else  // !defined(BUILDING_MULTITHREADING_APPLICATIONS_IN_WIN32_EXPORT)

        #define MULTITHREADING_APPLICATIONS_IN_WIN32_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_MULTITHREADING_APPLICATIONS_IN_WIN32_EXPORT

#else  // !defined(BUILDING_MULTITHREADING_APPLICATIONS_IN_WIN32_NO_IMPORT) && !defined(BUILDING_MULTITHREADING_APPLICATIONS_IN_WIN32_STATIC)

    #if defined(BUILDING_MULTITHREADING_APPLICATIONS_IN_WIN32_EXPORT)

        #define MULTITHREADING_APPLICATIONS_IN_WIN32_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define MULTITHREADING_APPLICATIONS_IN_WIN32_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_MULTITHREADING_APPLICATIONS_IN_WIN32_EXPORT)

        #define MULTITHREADING_APPLICATIONS_IN_WIN32_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define MULTITHREADING_APPLICATIONS_IN_WIN32_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_MULTITHREADING_APPLICATIONS_IN_WIN32_EXPORT

    #define MULTITHREADING_APPLICATIONS_IN_WIN32_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_MULTITHREADING_APPLICATIONS_IN_WIN32_NO_IMPORT) || defined(BUILDING_MULTITHREADING_APPLICATIONS_IN_WIN32_STATIC)

#endif  // MULTITHREADING_APPLICATIONS_IN_WIN32_DLL_H
