///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.1 (2021/01/01 14:25)

#ifndef COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_HELPER_USER_MACRO_H
#define COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_ClOSE_BEGIN (0x01)

#define CLOSE_USE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS (COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_ClOSE_BEGIN)

#define COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_ClOSE_END CLOSE_USE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS

#define CLOSE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_MAX ((COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_CLOSE 0x00

static_assert(0 <= COMPILE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_CLOSE, "COMPILE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_CLOSE <= CLOSE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_MAX, "COMPILE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_CLOSE Must be less than or equal CLOSE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_MAX.");

#if !defined(COMPILE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_CLOSE) || (COMPILE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_CLOSE & CLOSE_USE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS) != CLOSE_USE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS

#endif  // !defined(COMPILE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_CLOSE) || (COMPILE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_CLOSE & CLOSE_USE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS) != CLOSE_USE_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_STATIC
#endif  // BUILDING_STATIC

#endif  // COMPUTING_CONCEPTS_WITH_CPP_ESSENTIALS_HELPER_USER_MACRO_H
