///	Copyright (c) 2010-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎版本：0.6.0.0 (2020/12/16 11:12)

#ifndef MATHEMATICS_INTERSECTION_STATIC_INTERSECTOR_DETAIL_H
#define MATHEMATICS_INTERSECTION_STATIC_INTERSECTOR_DETAIL_H

#include "StaticIntersector.h"
 
#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_STATIC_INTERSECTOR_ACHIEVE)

    #include "StaticIntersectorAchieve.h"

#endif  // !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_STATIC_INTERSECTOR_ACHIEVE)

#endif // MATHEMATICS_INTERSECTION_STATIC_INTERSECTOR_DETAIL_H