/// Copyright (c) 2010-2023
/// Threading Core Render Engine
///
/// 作者：彭武阳，彭晔恩，彭晔泽
/// 联系作者：94458936@qq.com
///
/// 标准：std:c++20
/// 版本：1.0.0.1 (2023/11/25 20:42)

#ifndef RECHARGE_SERVER_MIDDLE_LAYER_EXPORT_H
#define RECHARGE_SERVER_MIDDLE_LAYER_EXPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_RECHARGE_SERVER_MIDDLE_LAYER_EXPORT

    #define BUILDING_RECHARGE_SERVER_MIDDLE_LAYER_EXPORT

#endif  // BUILDING_RECHARGE_SERVER_MIDDLE_LAYER_EXPORT

#endif  // RECHARGE_SERVER_MIDDLE_LAYER_EXPORT_H