///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.7 (2021/12/06 21:22)

#ifndef OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_MACRO_USER_MACRO_H
#define OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_MACRO_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_ClOSE_BEGIN (0x01)

#define CLOSE_USE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION (OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_ClOSE_BEGIN)

#define OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_ClOSE_END CLOSE_USE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION

#define CLOSE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_MAX ((OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_CLOSE 0x00

static_assert(0 <= COMPILE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_CLOSE, "COMPILE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_CLOSE <= CLOSE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_MAX, "COMPILE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_CLOSE Must be less than or equal CLOSE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_MAX.");

#if !defined(COMPILE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_CLOSE) || (COMPILE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_CLOSE & CLOSE_USE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION) != CLOSE_USE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION

#endif  // !defined(COMPILE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_CLOSE) || (COMPILE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_CLOSE & CLOSE_USE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION) != CLOSE_USE_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_STATIC
#endif  // BUILDING_STATIC

#endif  // OPERATING_SYSTEMS_DESIGN_AND_IMPLEMENTATION_MACRO_USER_MACRO_H
