///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.2 (2021/08/27 22:22)

#ifndef COMPUTER_NETWORKS_HELPER_USER_MACRO_H
#define COMPUTER_NETWORKS_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define COMPUTER_NETWORKS_ClOSE_BEGIN (0x01)

#define CLOSE_USE_COMPUTER_NETWORKS (COMPUTER_NETWORKS_ClOSE_BEGIN)

#define COMPUTER_NETWORKS_ClOSE_END CLOSE_USE_COMPUTER_NETWORKS

#define CLOSE_COMPUTER_NETWORKS_MAX ((COMPUTER_NETWORKS_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_COMPUTER_NETWORKS_CLOSE 0x00

static_assert(0 <= COMPILE_COMPUTER_NETWORKS_CLOSE, "COMPILE_COMPUTER_NETWORKS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_COMPUTER_NETWORKS_CLOSE <= CLOSE_COMPUTER_NETWORKS_MAX, "COMPILE_COMPUTER_NETWORKS_CLOSE Must be less than or equal CLOSE_COMPUTER_NETWORKS_MAX.");

#if !defined(COMPILE_COMPUTER_NETWORKS_CLOSE) || (COMPILE_COMPUTER_NETWORKS_CLOSE & CLOSE_USE_COMPUTER_NETWORKS) != CLOSE_USE_COMPUTER_NETWORKS

#endif  // !defined(COMPILE_COMPUTER_NETWORKS_CLOSE) || (COMPILE_COMPUTER_NETWORKS_CLOSE & CLOSE_USE_COMPUTER_NETWORKS) != CLOSE_USE_COMPUTER_NETWORKS

#ifdef BUILDING_STATIC
    #define BUILDING_COMPUTER_NETWORKS_STATIC
#endif  // BUILDING_STATIC

#endif  // COMPUTER_NETWORKS_HELPER_USER_MACRO_H
