// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 最后的霸王版本：0.0.0.0 (2019/10/10 14:42)

#ifndef ROBOT_CLIENT_MIDDLE_LAYER_EXPORT_H
#define ROBOT_CLIENT_MIDDLE_LAYER_EXPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_ROBOT_CLIENT_MIDDLE_LAYER_EXPORT
  #define BUILDING_ROBOT_CLIENT_MIDDLE_LAYER_EXPORT
#endif // BUILDING_ROBOT_CLIENT_MIDDLE_LAYER_EXPORT

#endif // ROBOT_CLIENT_MIDDLE_LAYER_EXPORT_H
