// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
// 
// 最后的霸王版本：0.0.0.0 (2019/10/10 14:43)

#ifndef ROBOT_CLIENT_MIDDLE_LAYER_NO_IMPORT_H
#define ROBOT_CLIENT_MIDDLE_LAYER_NO_IMPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_ROBOT_CLIENT_MIDDLE_LAYER_NO_IMPORT
  #define BUILDING_ROBOT_CLIENT_MIDDLE_LAYER_NO_IMPORT
#endif // BUILDING_ROBOT_CLIENT_MIDDLE_LAYER_NO_IMPORT

#endif // ROBOT_CLIENT_MIDDLE_LAYER_NO_IMPORT_H
