///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.3 (2021/05/03 15:37)

#ifndef PROGRAMMING_WINDOWS_SIXTH_EDITION_IMPORT_H
#define PROGRAMMING_WINDOWS_SIXTH_EDITION_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_PROGRAMMING_WINDOWS_SIXTH_EDITION_IMPORT
    #define BUILDING_PROGRAMMING_WINDOWS_SIXTH_EDITION_IMPORT
#endif  // BUILDING_PROGRAMMING_WINDOWS_SIXTH_EDITION_IMPORT

#endif  // PROGRAMMING_WINDOWS_SIXTH_EDITION_IMPORT_H
