///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	版本：0.9.1.2 (2023/07/31 10:56)

#ifndef SOUND_EFFECT_EXAMPLE_HELPER_USER_MACRO_H
#define SOUND_EFFECT_EXAMPLE_HELPER_USER_MACRO_H

#include "System/Helper/ConfigMacro.h"
#include "CoreTools/Helper/UserMacro.h"

#define SOUND_EFFECT_EXAMPLE_ClOSE_BEGIN (0x01)

#define CLOSE_USE_SOUND_EFFECT_EXAMPLE (SOUND_EFFECT_EXAMPLE_ClOSE_BEGIN)

#define SOUND_EFFECT_EXAMPLE_ClOSE_END CLOSE_USE_SOUND_EFFECT_EXAMPLE

#define CLOSE_SOUND_EFFECT_EXAMPLE_MAX (((SOUND_EFFECT_EXAMPLE_ClOSE_END) << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_SOUND_EFFECT_EXAMPLE_CLOSE 0x00

static_assert(0 <= COMPILE_SOUND_EFFECT_EXAMPLE_CLOSE, "COMPILE_SOUND_EFFECT_EXAMPLE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_SOUND_EFFECT_EXAMPLE_CLOSE <= CLOSE_SOUND_EFFECT_EXAMPLE_MAX, "COMPILE_SOUND_EFFECT_EXAMPLE_CLOSE Must be less than or equal CLOSE_SOUND_EFFECT_EXAMPLE_MAX.");

#if !defined(COMPILE_SOUND_EFFECT_EXAMPLE_CLOSE) || (COMPILE_SOUND_EFFECT_EXAMPLE_CLOSE & CLOSE_USE_XXX) != CLOSE_USE_XXX

#endif  // !defined(COMPILE_SOUND_EFFECT_EXAMPLE_CLOSE) || (COMPILE_SOUND_EFFECT_EXAMPLE_CLOSE & CLOSE_USE_XXX) != CLOSE_USE_XXX

#ifdef BUILDING_STATIC

    #define BUILDING_SOUND_EFFECT_EXAMPLE_STATIC

#endif  // BUILDING_STATIC

#endif  // SOUND_EFFECT_EXAMPLE_HELPER_USER_MACRO_H
