/// Copyright (c) 2010-2023
/// Threading Core Render Engine
///
/// 作者：彭武阳，彭晔恩，彭晔泽
/// 联系作者：94458936@qq.com
///
/// 标准：std:c++20
/// 版本：1.0.0.2 (2023/12/17 19:26)

#ifndef DATABASE_SERVER_MIDDLE_LAYER_IMPORT_H
#define DATABASE_SERVER_MIDDLE_LAYER_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_DATABASE_SERVER_MIDDLE_LAYER_IMPORT

    #define BUILDING_DATABASE_SERVER_MIDDLE_LAYER_IMPORT

#endif  // BUILDING_DATABASE_SERVER_MIDDLE_LAYER_IMPORT

#endif  // DATABASE_SERVER_MIDDLE_LAYER_IMPORT_H