// Copyright (c) 2011-2020
// Threading Core Render Engine
// ◊˜’ﬂ£∫≈ÌŒ‰—Ù£¨≈ÌÍ ∂˜£¨≈ÌÍ ‘Û
//
// “˝«Ê∏®÷˙∞Ê±æ£∫0.0.2.0 (2020/01/05 19:29)

#ifndef RESOURCE_MANAGER_TOOLSET_DLL_DLL_H
#define RESOURCE_MANAGER_TOOLSET_DLL_DLL_H

#include "System/Helper/ExportMacro.h"
#include "ResourceManager/Helper/UserMacro.h"

#if defined(BUILDING_RESOURCE_MANAGER_TOOLSET_NO_IMPORT) || defined(BUILDING_RESOURCE_MANAGER_STATIC)

  #define RESOURCE_MANAGER_TOOLSET_DEFAULT_DECLARE
  #define RESOURCE_MANAGER_TOOLSET_HIDDEN_DECLARE
  #define RESOURCE_MANAGER_TOOLSET_VISIBLE

#else // !defined(BUILDING_RESOURCE_MANAGER_TOOLSET_NO_IMPORT) && !defined(BUILDING_RESOURCE_MANAGER_STATIC)

   #if defined(BUILDING_RESOURCE_MANAGER_TOOLSET_EXPORT)
 
        #define RESOURCE_MANAGER_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define RESOURCE_MANAGER_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

   #else // !defined(BUILDING_RESOURCE_MANAGER_TOOLSET_EXPORT)

		#define RESOURCE_MANAGER_TOOLSET_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define RESOURCE_MANAGER_TOOLSET_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

   #endif // BUILDING_RESOURCE_MANAGER_TOOLSET_EXPORT

   #define RESOURCE_MANAGER_TOOLSET_VISIBLE TCRE_SYMBOL_VISIBLE

#endif // defined(BUILDING_RESOURCE_MANAGER_TOOLSET_NO_IMPORT) || defined(BUILDING_RESOURCE_MANAGER_STATIC)

#endif // RESOURCE_MANAGER_TOOLSET_DLL_DLL_H
