///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.3 (2021/09/08 21:15)

#ifndef COMPUTER_NETWORKS_A_SYSTEM_APPROACH_EXPORT_H
#define COMPUTER_NETWORKS_A_SYSTEM_APPROACH_EXPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_COMPUTER_NETWORKS_A_SYSTEM_APPROACH_EXPORT
    #define BUILDING_COMPUTER_NETWORKS_A_SYSTEM_APPROACH_EXPORT
#endif  // BUILDING_COMPUTER_NETWORKS_A_SYSTEM_APPROACH_EXPORT

#endif  // COMPUTER_NETWORKS_A_SYSTEM_APPROACH_EXPORT_H
