///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	引擎游戏版本：0.9.0.12 (2023/06/16 17:03)

#ifndef CHARACTER_INFORMATION_DLL_H
#define CHARACTER_INFORMATION_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_CHARACTER_INFORMATION_NO_IMPORT) || defined(BUILDING_CHARACTER_INFORMATION_STATIC)

    #define CHARACTER_INFORMATION_DEFAULT_DECLARE
    #define CHARACTER_INFORMATION_HIDDEN_DECLARE
    #define CHARACTER_INFORMATION_VISIBLE


    #if defined(BUILDING_USER_INFO_EXPORT)

        #define USER_INFO_HIDDEN_DECLARE

    #else  // !defined(BUILDING_USER_INFO_EXPORT)

        #define USER_INFO_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_USER_INFO_EXPORT

#else  // !defined(BUILDING_CHARACTER_INFORMATION_NO_IMPORT) && !defined(BUILDING_CHARACTER_INFORMATION_STATIC)

    #if defined(BUILDING_CHARACTER_INFORMATION_EXPORT)

        #define CHARACTER_INFORMATION_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define CHARACTER_INFORMATION_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_CHARACTER_INFORMATION_EXPORT)

        #define CHARACTER_INFORMATION_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define CHARACTER_INFORMATION_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_CHARACTER_INFORMATION_EXPORT

    #define CHARACTER_INFORMATION_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_CHARACTER_INFORMATION_NO_IMPORT) || defined(BUILDING_CHARACTER_INFORMATION_STATIC)

#endif  // CHARACTER_INFORMATION_DLL_H
