// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
//
// 引擎游戏版本：0.0.0.1 (2019/10/04 21:29)

#ifndef CHARACTER_INFORMATION_NO_IMPORT_H
#define CHARACTER_INFORMATION_NO_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_CHARACTER_INFORMATION_NO_IMPORT
  #define BUILDING_CHARACTER_INFORMATION_NO_IMPORT
#endif // BUILDING_CHARACTER_INFORMATION_NO_IMPORT

#endif // CHARACTER_INFORMATION_NO_IMPORT_H
