///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.1 (2021/03/11 17:52)

#ifndef CROSS_PLATFORM_DEVELOPMENT_IN_CPP_DLL_H
#define CROSS_PLATFORM_DEVELOPMENT_IN_CPP_DLL_H

#include "Helper/UserMacro.h"
#include "System/Helper/ExportMacro.h"

#if defined(BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_NO_IMPORT) || defined(BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_STATIC)

    #define CROSS_PLATFORM_DEVELOPMENT_IN_CPP_DEFAULT_DECLARE
    #define CROSS_PLATFORM_DEVELOPMENT_IN_CPP_VISIBLE

    #if defined(BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_EXPORT)

        #define CROSS_PLATFORM_DEVELOPMENT_IN_CPP_HIDDEN_DECLARE

    #else  // !defined(BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_EXPORT)

        #define CROSS_PLATFORM_DEVELOPMENT_IN_CPP_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_EXPORT

#else  // !defined(BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_NO_IMPORT) && !defined(BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_STATIC)

    #if defined(BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_EXPORT)

        #define CROSS_PLATFORM_DEVELOPMENT_IN_CPP_DEFAULT_DECLARE TCRE_SYMBOL_EXPORT
        #define CROSS_PLATFORM_DEVELOPMENT_IN_CPP_HIDDEN_DECLARE TCRE_SYMBOL_NO_EXPORT

    #else  // !defined(BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_EXPORT)

        #define CROSS_PLATFORM_DEVELOPMENT_IN_CPP_DEFAULT_DECLARE TCRE_SYMBOL_IMPORT
        #define CROSS_PLATFORM_DEVELOPMENT_IN_CPP_HIDDEN_DECLARE TCRE_SYMBOL_NO_IMPORT

    #endif  // BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_EXPORT

    #define CROSS_PLATFORM_DEVELOPMENT_IN_CPP_VISIBLE TCRE_SYMBOL_VISIBLE

#endif  // defined(BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_NO_IMPORT) || defined(BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_STATIC)

#endif  // CROSS_PLATFORM_DEVELOPMENT_IN_CPP_DLL_H
