///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.1.1 (2021/03/11 17:51)

#ifndef CROSS_PLATFORM_DEVELOPMENT_IN_CPP_NO_IMPORT_H
#define CROSS_PLATFORM_DEVELOPMENT_IN_CPP_NO_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_NO_IMPORT
    #define BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_NO_IMPORT
#endif  // BUILDING_CROSS_PLATFORM_DEVELOPMENT_IN_CPP_NO_IMPORT

#endif  // CROSS_PLATFORM_DEVELOPMENT_IN_CPP_NO_IMPORT_H
