// Copyright (c) 2011-2020
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
//
// 引擎辅助版本：0.0.2.2 (2020/01/27 14:58)

#ifndef ASSIST_TOOLS_EXAMPLE_MACRO_USER_MACRO_H
#define ASSIST_TOOLS_EXAMPLE_MACRO_USER_MACRO_H

#include "System/Helper/ConfigMacro.h"
#include "CoreTools/Helper/UserMacro.h" 

#define CLOSE_USE_XXX (0x01) 
#define CLOSE_ASSIST_TOOLS_EXAMPLE_MAX (((CLOSE_USE_XXX) << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_ASSIST_TOOLS_EXAMPLE_CLOSE 0x00

static_assert(0 <= COMPILE_ASSIST_TOOLS_EXAMPLE_CLOSE, "COMPILE_ASSIST_TOOLS_EXAMPLE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_ASSIST_TOOLS_EXAMPLE_CLOSE <= CLOSE_ASSIST_TOOLS_EXAMPLE_MAX, "COMPILE_ASSIST_TOOLS_EXAMPLE_CLOSE Must be less than or equal CLOSE_ASSIST_TOOLS_EXAMPLE_MAX.");

// 是否编译为静态库
#ifdef BUILDING_STATIC
	#define  BUILDING_ASSIST_TOOLS_EXAMPLE_STATIC
#endif // BUILDING_STATIC

#if !defined(COMPILE_ASSIST_TOOLS_EXAMPLE_CLOSE) || (COMPILE_ASSIST_TOOLS_EXAMPLE_CLOSE & CLOSE_USE_XXX) != CLOSE_USE_XXX

#endif // !defined(COMPILE_ASSIST_TOOLS_EXAMPLE_CLOSE) || (COMPILE_ASSIST_TOOLS_EXAMPLE_CLOSE & CLOSE_USE_XXX) != CLOSE_USE_XXX 
 
#endif // ASSIST_TOOLS_EXAMPLE_MACRO_USER_MACRO_H
