/// Copyright (c) 2010-2023
/// Threading Core Render Engine
///
/// 作者：彭武阳，彭晔恩，彭晔泽
/// 联系作者：94458936@qq.com
///
/// 标准：std:c++20
/// 版本：0.9.1.3 (2023/08/21 10:42)

#ifndef WORLD_SERVER_CORE_HELPER_USER_MACRO_H
#define WORLD_SERVER_CORE_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define WORLD_SERVER_CORE_ClOSE_BEGIN (0x01)

#define CLOSE_USE_WORLD_SERVER_CORE (WORLD_SERVER_CORE_ClOSE_BEGIN)

#define WORLD_SERVER_CORE_ClOSE_END CLOSE_USE_WORLD_SERVER_CORE

#define CLOSE_WORLD_SERVER_CORE_MAX (((WORLD_SERVER_CORE_ClOSE_END) << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_WORLD_SERVER_CORE_CLOSE 0x00

static_assert(0 <= COMPILE_WORLD_SERVER_CORE_CLOSE, "COMPILE_WORLD_SERVER_CORE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_WORLD_SERVER_CORE_CLOSE <= CLOSE_WORLD_SERVER_CORE_MAX, "COMPILE_WORLD_SERVER_CORE_CLOSE Must be less than or equal CLOSE_WORLD_SERVER_CORE_MAX.");

#if !defined(COMPILE_WORLD_SERVER_CORE_CLOSE) || (COMPILE_WORLD_SERVER_CORE_CLOSE & CLOSE_USE_WORLD_SERVER_CORE) != CLOSE_USE_WORLD_SERVER_CORE

#endif  // !defined(COMPILE_WORLD_SERVER_CORE_CLOSE) || (COMPILE_WORLD_SERVER_CORE_CLOSE & CLOSE_USE_WORLD_SERVER_CORE) != CLOSE_USE_WORLD_SERVER_CORE

#ifdef BUILDING_STATIC

    #define BUILDING_WORLD_SERVER_CORE_STATIC (static_cast<void>(0))

#endif  // BUILDING_STATIC

#endif  // WORLD_SERVER_CORE_HELPER_USER_MACRO_H
