///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.0 (2021/01/30 11:03)

#ifndef THE_ART_OF_COMPUTER_PROGRAMMING_IMPORT_H
#define THE_ART_OF_COMPUTER_PROGRAMMING_IMPORT_H

#include "Helper/UserMacro.h"

#ifndef BUILDING_THE_ART_OF_COMPUTER_PROGRAMMING_IMPORT
    #define BUILDING_THE_ART_OF_COMPUTER_PROGRAMMING_IMPORT
#endif  // BUILDING_THE_ART_OF_COMPUTER_PROGRAMMING_IMPORT

#endif  // THE_ART_OF_COMPUTER_PROGRAMMING_IMPORT_H
