///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助测试版本：0.7.2.3 (2021/09/24 8:50)

#ifndef BOOK_NETWORK_PROGRAMMING_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_SUITE_H
#define BOOK_NETWORK_PROGRAMMING_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_SUITE_H

#include "ConfiguringWindowsServerPlaceholderTesting.h"

#endif  // BOOK_NETWORK_PROGRAMMING_CONFIGURING_WINDOWS_SERVER_2008_NETWORK_INFRASTRUCTURE_SUITE_H
