///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.3 (2021/09/22 21:07)

#ifndef TCP_IP_PROTOCOL_SUITE_HELPER_USER_MACRO_H
#define TCP_IP_PROTOCOL_SUITE_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define TCP_IP_PROTOCOL_SUITE_ClOSE_BEGIN (0x01)

#define CLOSE_USE_TCP_IP_PROTOCOL_SUITE (TCP_IP_PROTOCOL_SUITE_ClOSE_BEGIN)

#define TCP_IP_PROTOCOL_SUITE_ClOSE_END CLOSE_USE_TCP_IP_PROTOCOL_SUITE

#define CLOSE_TCP_IP_PROTOCOL_SUITE_MAX ((TCP_IP_PROTOCOL_SUITE_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_TCP_IP_PROTOCOL_SUITE_CLOSE 0x00

static_assert(0 <= COMPILE_TCP_IP_PROTOCOL_SUITE_CLOSE, "COMPILE_TCP_IP_PROTOCOL_SUITE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_TCP_IP_PROTOCOL_SUITE_CLOSE <= CLOSE_TCP_IP_PROTOCOL_SUITE_MAX, "COMPILE_TCP_IP_PROTOCOL_SUITE_CLOSE Must be less than or equal CLOSE_TCP_IP_PROTOCOL_SUITE_MAX.");

#if !defined(COMPILE_TCP_IP_PROTOCOL_SUITE_CLOSE) || (COMPILE_TCP_IP_PROTOCOL_SUITE_CLOSE & CLOSE_USE_TCP_IP_PROTOCOL_SUITE) != CLOSE_USE_TCP_IP_PROTOCOL_SUITE

#endif  // !defined(COMPILE_TCP_IP_PROTOCOL_SUITE_CLOSE) || (COMPILE_TCP_IP_PROTOCOL_SUITE_CLOSE & CLOSE_USE_TCP_IP_PROTOCOL_SUITE) != CLOSE_USE_TCP_IP_PROTOCOL_SUITE

#ifdef BUILDING_STATIC
    #define BUILDING_TCP_IP_PROTOCOL_SUITE_STATIC
#endif  // BUILDING_STATIC

#endif  // TCP_IP_PROTOCOL_SUITE_HELPER_USER_MACRO_H
