///	Copyright (c) 2010-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎版本：0.5.2.2 (2020/11/06 10:08)

#ifndef DATABASE_DATABASE_MACRO_USER_MACRO_H
#define DATABASE_DATABASE_MACRO_USER_MACRO_H

#include "CoreTools/Helper/UserMacro.h"

#define DATABASE_ClOSE_BEGIN (0x01)

#define CLOSE_USE_MYSQL (DATABASE_ClOSE_BEGIN)
#define CLOSE_USE_MYSQL_C_API (DATABASE_ClOSE_BEGIN << 1)
#define CLOSE_USE_MYSQL_CPP_CONNECTOR (DATABASE_ClOSE_BEGIN << 2)
#define CLOSE_USE_SQL_SERVER (DATABASE_ClOSE_BEGIN << 3)

#define DATABASE_ClOSE_END CLOSE_USE_SQL_SERVER

#define CLOSE_DATABASE_MAX (((DATABASE_ClOSE_END) << 1) - 1)

// 编译测试（默认为0，最大值为0x0F）
#define COMPILE_DATABASE_CLOSE 0x00

static_assert(0 <= COMPILE_DATABASE_CLOSE, "COMPILE_DATABASE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_DATABASE_CLOSE <= CLOSE_DATABASE_MAX, "COMPILE_DATABASE_CLOSE Must be less than or equal CLOSE_DATABASE_MAX.");

#if !defined(COMPILE_DATABASE_CLOSE) || (COMPILE_DATABASE_CLOSE & CLOSE_USE_MYSQL) != CLOSE_USE_MYSQL
    #define DATABASE_USE_MYSQL static_cast<void>(0)
#endif  // !defined(COMPILE_DATABASE_CLOSE) || (COMPILE_DATABASE_CLOSE & CLOSE_USE_MYSQL) != CLOSE_USE_MYSQL

#ifdef DATABASE_USE_MYSQL

    #if !defined(COMPILE_DATABASE_CLOSE) || (COMPILE_DATABASE_CLOSE & CLOSE_USE_MYSQL_C_API) != CLOSE_USE_MYSQL_C_API
        #define DATABASE_USE_MYSQL_C_API static_cast<void>(0)
    #endif  // !defined(COMPILE_DATABASE_CLOSE) || (COMPILE_DATABASE_CLOSE & CLOSE_USE_MYSQL_C_API) != CLOSE_USE_MYSQL_C_API

    #if !defined(COMPILE_DATABASE_CLOSE) || (COMPILE_DATABASE_CLOSE & CLOSE_USE_MYSQL_CPP_CONNECTOR) != CLOSE_USE_MYSQL_CPP_CONNECTOR
        #define DATABASE_USE_MYSQL_CPP_CONNECTOR static_cast<void>(0)
    #endif  // !defined(COMPILE_DATABASE_CLOSE) || (COMPILE_DATABASE_CLOSE & CLOSE_USE_MYSQL_CPP_CONNECTOR) != CLOSE_USE_MYSQL_CPP_CONNECTOR

#endif  // DATABASE_USE_MYSQL

#if !defined(COMPILE_DATABASE_CLOSE) || (COMPILE_DATABASE_CLOSE & CLOSE_USE_SQL_SERVER) != CLOSE_USE_SQL_SERVER
    #define DATABASE_USE_SQL_SERVER static_cast<void>(0)
#endif  // !defined(COMPILE_DATABASE_CLOSE) || (COMPILE_DATABASE_CLOSE & CLOSE_USE_SQL_SERVER) != CLOSE_USE_SQL_SERVER

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_DATABASE_STATIC static_cast<void>(0)
#endif  // BUILDING_STATIC

#endif  // DATABASE_DATABASE_MACRO_USER_MACRO_H
