///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.1 (2021/02/09 14:57)

#ifndef LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_HELPER_USER_MACRO_H
#define LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_ClOSE_BEGIN (0x01)

#define CLOSE_USE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS (LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_ClOSE_BEGIN)

#define LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_ClOSE_END CLOSE_USE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS

#define CLOSE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_MAX ((LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_CLOSE 0x00

static_assert(0 <= COMPILE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_CLOSE, "COMPILE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_CLOSE <= CLOSE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_MAX, "COMPILE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_CLOSE Must be less than or equal CLOSE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_MAX.");

#if !defined(COMPILE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_CLOSE) || (COMPILE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_CLOSE & CLOSE_USE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS) != CLOSE_USE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS

#endif  // !defined(COMPILE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_CLOSE) || (COMPILE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_CLOSE & CLOSE_USE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS) != CLOSE_USE_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_STATIC
#endif  // BUILDING_STATIC

#endif  // LINEAR_ALGEBRA_AND_ITS_APPLICATIONS_HELPER_USER_MACRO_H
