///	Copyright (c) 2010-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.6.0.0 (2020/12/23 20:51)

#ifndef THINKING_IN_CPP_VOLUME_TWO_MACRO_USER_MACRO_H
#define THINKING_IN_CPP_VOLUME_TWO_MACRO_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define THINKING_IN_CPP_VOLUME_TWO_ClOSE_BEGIN (0x01)

#define CLOSE_USE_THINKING_IN_CPP_VOLUME_TWO (THINKING_IN_CPP_VOLUME_TWO_ClOSE_BEGIN)

#define THINKING_IN_CPP_VOLUME_TWO_ClOSE_END CLOSE_USE_THINKING_IN_CPP_VOLUME_TWO

#define CLOSE_THINKING_IN_CPP_VOLUME_TWO_MAX ((THINKING_IN_CPP_VOLUME_TWO_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_THINKING_IN_CPP_VOLUME_TWO_CLOSE 0x00

static_assert(0 <= COMPILE_THINKING_IN_CPP_VOLUME_TWO_CLOSE, "COMPILE_THINKING_IN_CPP_VOLUME_TWO_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_THINKING_IN_CPP_VOLUME_TWO_CLOSE <= CLOSE_THINKING_IN_CPP_VOLUME_TWO_MAX, "COMPILE_THINKING_IN_CPP_VOLUME_TWO_CLOSE Must be less than or equal CLOSE_THINKING_IN_CPP_VOLUME_TWO_MAX.");

#if !defined(COMPILE_THINKING_IN_CPP_VOLUME_TWO_CLOSE) || (COMPILE_THINKING_IN_CPP_VOLUME_TWO_CLOSE & CLOSE_USE_THINKING_IN_CPP_VOLUME_ONE) != CLOSE_USE_THINKING_IN_CPP_VOLUME_ONE

#endif  // !defined(COMPILE_THINKING_IN_CPP_VOLUME_TWO_CLOSE) || (COMPILE_THINKING_IN_CPP_VOLUME_TWO_CLOSE & CLOSE_USE_THINKING_IN_CPP_VOLUME_ONE) != CLOSE_USE_THINKING_IN_CPP_VOLUME_ONE

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_THINKING_IN_CPP_VOLUME_TWO_STATIC
#endif  // BUILDING_STATIC

#endif  // THINKING_IN_CPP_VOLUME_TWO_MACRO_USER_MACRO_H
