///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.2.4 (2021/10/07 23:22)

#ifndef ADVANCED_WINDOWS_DEBUGGING_HELPER_USER_MACRO_H
#define ADVANCED_WINDOWS_DEBUGGING_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define ADVANCED_WINDOWS_DEBUGGING_ClOSE_BEGIN (0x01)

#define CLOSE_USE_ADVANCED_WINDOWS_DEBUGGING (ADVANCED_WINDOWS_DEBUGGING_ClOSE_BEGIN)

#define ADVANCED_WINDOWS_DEBUGGING_ClOSE_END CLOSE_USE_ADVANCED_WINDOWS_DEBUGGING

#define CLOSE_ADVANCED_WINDOWS_DEBUGGING_MAX ((ADVANCED_WINDOWS_DEBUGGING_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_ADVANCED_WINDOWS_DEBUGGING_CLOSE 0x00

static_assert(0 <= COMPILE_ADVANCED_WINDOWS_DEBUGGING_CLOSE, "COMPILE_ADVANCED_WINDOWS_DEBUGGING_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_ADVANCED_WINDOWS_DEBUGGING_CLOSE <= CLOSE_ADVANCED_WINDOWS_DEBUGGING_MAX, "COMPILE_ADVANCED_WINDOWS_DEBUGGING_CLOSE Must be less than or equal CLOSE_ADVANCED_WINDOWS_DEBUGGING_MAX.");

#if !defined(COMPILE_ADVANCED_WINDOWS_DEBUGGING_CLOSE) || (COMPILE_ADVANCED_WINDOWS_DEBUGGING_CLOSE & CLOSE_USE_ADVANCED_WINDOWS_DEBUGGING) != CLOSE_USE_ADVANCED_WINDOWS_DEBUGGING

#endif  // !defined(COMPILE_ADVANCED_WINDOWS_DEBUGGING_CLOSE) || (COMPILE_ADVANCED_WINDOWS_DEBUGGING_CLOSE & CLOSE_USE_ADVANCED_WINDOWS_DEBUGGING) != CLOSE_USE_ADVANCED_WINDOWS_DEBUGGING

#ifdef BUILDING_STATIC
    #define BUILDING_ADVANCED_WINDOWS_DEBUGGING_STATIC
#endif  // BUILDING_STATIC

#endif  // ADVANCED_WINDOWS_DEBUGGING_HELPER_USER_MACRO_H
