//	Copyright (c) 2011-2020
//	Threading Core Render Engine
//
//	作者：彭武阳，彭晔恩，彭晔泽
//	联系作者：94458936@qq.com
//
//	标准：std:c++17
//	引擎版本：0.5.0.0 (2020/08/29 0:09)

#ifndef MATHEMATICS_ALGEBRA_AVECTOR_ORTHONORMA_BASIS_DETAIL_H
#define MATHEMATICS_ALGEBRA_AVECTOR_ORTHONORMA_BASIS_DETAIL_H

#include "AVectorOrthonormalBasis.h"

#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_AVECTOR_ORTHONORMAL_BASIS_ACHIEVE)

    #include "AVectorOrthonormalBasisAchieve.h"

#endif  // !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_AVECTOR_ORTHONORMAL_BASIS_ACHIEVE)

#endif // MATHEMATICS_ALGEBRA_AVECTOR_ORTHONORMA_BASIS_DETAIL_H