///	Copyright (c) 2011-2020
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎版本：0.5.2.2 (2020/11/03 18:26)

#ifndef MATHEMATICS_ALGEBRA_AVECTOR_ORTHONORMALIZE_DETAIL_H
#define MATHEMATICS_ALGEBRA_AVECTOR_ORTHONORMALIZE_DETAIL_H

#include "AVectorOrthonormalize.h"

#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_AVECTOR_ORTHONORMALIZE_ACHIEVE)

    #include "AVectorOrthonormalizeAchieve.h"

#endif  // !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_AVECTOR_ORTHONORMALIZE_ACHIEVE)

#endif  // MATHEMATICS_ALGEBRA_AVECTOR_ORTHONORMALIZE_DETAIL_H
