///	Copyright (c) 2010-2022
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎版本：0.8.0.2 (2022/02/01 23:53)

#ifndef MATHEMATICS_ALGEBRA_VECTOR_2D_ORTHONORMA_BASIS_DETAIL_H
#define MATHEMATICS_ALGEBRA_VECTOR_2D_ORTHONORMA_BASIS_DETAIL_H

#include "Vector2OrthonormalBasis.h"

#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_VECTOR2_ORTHONORMAL_BASIS_ACHIEVE)

    #include "Vector2OrthonormalBasisAchieve.h"

#endif  // !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_VECTOR2_ORTHONORMAL_BASIS_ACHIEVE)

#endif  // MATHEMATICS_ALGEBRA_VECTOR_2D_ORTHONORMA_BASIS_DETAIL_H