///	Copyright (c) 2010-2023
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++20
///	引擎版本：0.9.0.11 (2023/06/01 10:26)

#ifndef MATHEMATICS_ALGEBRA_VECTOR3_ORTHONORMAL_BASIS_DETAIL_H
#define MATHEMATICS_ALGEBRA_VECTOR3_ORTHONORMAL_BASIS_DETAIL_H

#include "Vector3OrthonormalBasis.h"

#if !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_VECTOR3_ORTHONORMAL_BASIS_ACHIEVE)

    #include "Vector3OrthonormalBasisAchieve.h"

#endif  // !defined(MATHEMATICS_EXPORT_TEMPLATE) || defined(MATHEMATICS_INCLUDED_VECTOR3_ORTHONORMAL_BASIS_ACHIEVE)

#endif  // MATHEMATICS_ALGEBRA_VECTOR3_ORTHONORMAL_BASIS_DETAIL_H