// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
//
// 最后的霸王版本：0.0.0.1 (2019/10/13 18:06)

#ifndef BACKGROUND_SERVER_CORE_NO_IMPORT_H
#define BACKGROUND_SERVER_CORE_NO_IMPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_BACKGROUND_SERVER_CORE_NO_IMPORT
  #define BUILDING_BACKGROUND_SERVER_CORE_NO_IMPORT
#endif // BUILDING_BACKGROUND_SERVER_CORE_NO_IMPORT

#endif // BACKGROUND_SERVER_CORE_NO_IMPORT_H
