// Copyright (c) 2011-2019
// Threading Core Render Engine
// 作者：彭武阳，彭晔恩，彭晔泽
//
// 最后的霸王版本：0.0.0.1 (2019/10/13 18:06)

#ifndef BACKGROUND_SERVER_CORE_EXPORT_H
#define BACKGROUND_SERVER_CORE_EXPORT_H

#include "Macro/UserMacro.h"

#ifndef BUILDING_BACKGROUND_SERVER_CORE_EXPORT
  #define BUILDING_BACKGROUND_SERVER_CORE_EXPORT
#endif // BUILDING_BACKGROUND_SERVER_CORE_EXPORT

#endif // BACKGROUND_SERVER_CORE_EXPORT_H
