///	Copyright (c) 2010-2021
///	Threading Core Render Engine
///
///	作者：彭武阳，彭晔恩，彭晔泽
///	联系作者：94458936@qq.com
///
///	标准：std:c++17
///	引擎辅助版本：0.7.0.1 (2021/02/09 14:57)

#ifndef UNDERSTANDING_THE_MACHINE_HELPER_USER_MACRO_H
#define UNDERSTANDING_THE_MACHINE_HELPER_USER_MACRO_H

#include "Framework/Helper/UserMacro.h"

#define UNDERSTANDING_THE_MACHINE_ClOSE_BEGIN (0x01)

#define CLOSE_USE_UNDERSTANDING_THE_MACHINE (UNDERSTANDING_THE_MACHINE_ClOSE_BEGIN)

#define UNDERSTANDING_THE_MACHINE_ClOSE_END CLOSE_USE_UNDERSTANDING_THE_MACHINE

#define CLOSE_UNDERSTANDING_THE_MACHINE_MAX ((UNDERSTANDING_THE_MACHINE_ClOSE_END << 1) - 1)

// 编译测试（默认为0，最大值为0x01）
#define COMPILE_UNDERSTANDING_THE_MACHINE_CLOSE 0x00

static_assert(0 <= COMPILE_UNDERSTANDING_THE_MACHINE_CLOSE, "COMPILE_UNDERSTANDING_THE_MACHINE_CLOSE Must be greater than or equal 0.");
static_assert(COMPILE_UNDERSTANDING_THE_MACHINE_CLOSE <= CLOSE_UNDERSTANDING_THE_MACHINE_MAX, "COMPILE_UNDERSTANDING_THE_MACHINE_CLOSE Must be less than or equal CLOSE_UNDERSTANDING_THE_MACHINE_MAX.");

#if !defined(COMPILE_UNDERSTANDING_THE_MACHINE_CLOSE) || (COMPILE_UNDERSTANDING_THE_MACHINE_CLOSE & CLOSE_USE_UNDERSTANDING_THE_MACHINE) != CLOSE_USE_UNDERSTANDING_THE_MACHINE

#endif  // !defined(COMPILE_UNDERSTANDING_THE_MACHINE_CLOSE) || (COMPILE_UNDERSTANDING_THE_MACHINE_CLOSE & CLOSE_USE_UNDERSTANDING_THE_MACHINE) != CLOSE_USE_UNDERSTANDING_THE_MACHINE

// 是否编译为静态库
#ifdef BUILDING_STATIC
    #define BUILDING_UNDERSTANDING_THE_MACHINE_STATIC
#endif  // BUILDING_STATIC

#endif  // UNDERSTANDING_THE_MACHINE_HELPER_USER_MACRO_H
